JetBrains/kotlin-web-site

_data/oss-projects.yml
Framework is in early stage of development. Ignore this request if you consider code quality insufficient. I am Kotlin novice.
=> Proposing to add Yested framework to the list.

_data/oss-projects.yml
I have added library that generates hashes from numbers (YouTube-like)
It is port hashids library was written on javascript (http://hashids.org) by Ivan Akimov
=> Kotlin-Hashids library is added

docs/reference/null-safety.md
Replaced with Wikipedia article that references it, perhaps there is a better link out there on the web for this instead?  The previous one was dead.
=> Fixed dead link.

docs/reference/delegated-properties.md
=> Typo: Matadata -> Metadata

docs/reference/control-flow.md
=> minor updates to documentation on 'when'

contribute.md
- Add missing words
- Small grammar fix
=> Contribute.md fixes

.idea/kotlin-web-site.iml, docs/reference/using-gradle.md
Re-structuring a bit the sections and adding information regarding kotlin2js based on recent issue
=> Changes to gradle

docs/reference/java-interop.md
So it matches the examples above it.
=> Add ` around List

docs/tutorials/mixing-java-kotlin-intellij.md
I added a constructor to the `Customer` class so calling `println(customer.getName())` wouldn't throw a NPE.
=> Fix NPE in example code

_data/events.yml
=> Added slides from IT Letnik

_data/oss-projects.yml
I would love to add [Fuel](https://github.com/kittinunf/Fuel) into the list.
:sparkles:
=> Add Fuel into OSS Kotlin list

docs/reference/using-gradle.md
I got confused by this when trying to set up my first Kotlin Gradle project
=> Make folder structure slightly clearer

docs/reference/ranges.md
Just a bunch of grammatical changes which hopefully improve readability.
=> Various grammar changes.

_data/events.yml
Two talks for our Manchester Meetup
=> Manchester Meetup

docs/reference/classes.md
fix in example for sealed classes
=> fix example

_data/events.yml
added Matt Wear's talk on DroidCon Montreal 2015 (video)
=> DroidCon Montreal 2015 (video)

_data/events.yml
added video for DroidCon Greece 2015
=> video for DroidCon Greece 2015

docs/reference/idioms.md
A very useful idioms that is hard to learn about from current documentation  is using the 'with' function for calling multiple methods on an object instance
=> 'with' use case

code/tutorials/spring-boot-restful/build.gradle, code/tutorials/spring-boot-restful/gradlew, code/tutorials/spring-boot-restful/spring-boot-restful.iml, code/tutorials/spring-boot-restful/src/main/kotlin/Application.kt, code/tutorials/spring-boot-restful/src/main/kotlin/GreetingController.kt, code/tutorials/spring-boot-restful/src/main/kotlin/kotlin/demo/Application.kt, code/tutorials/spring-boot-restful/src/main/kotlin/kotlin/demo/Greeting.kt, code/tutorials/spring-boot-restful/src/main/kotlin/kotlin/demo/GreetingController.kt
Kotlin update: M14, 0.14.449
Spring Boot update: 1.2.7.RELEASE
Disclaimer. I don't have much experience in contributing on GitHub, so if anything is amiss in this Pull Request, please don't hesitate to comment, I'll try to improve the PR accordingly.
=> Updates spring-boot-restful demo to use latest Kotlin and Spring Boot

README.md
=> Do not run INSTALL.sh with sh

code/tutorials/spring-boot-restful/src/main/kotlin/kotlin/demo/Greeting.kt, code/tutorials/spring-boot-restful/src/main/kotlin/kotlin/demo/GreetingController.kt, docs/tutorials/spring-boot-restful.md
Consistently remove the redundant public modifiers everywhere.
=> Update spring-boot kotlin tutorial with changes for kotlin beta.

_data/companies-using-kotlin.yml
Added 3D Robotics to the list of companies using Kotlin in a production Android app.
=> Added 3D Robotics to companies

docs/reference/basic-syntax.md
'size():Int' is deprecated. Use property 'size" instead
=> replace .size():Int method to .size property

docs/reference/operator-overloading.md
See http://stackoverflow.com/questions/33758880/can-i-add-operators-to-existing-classes/
=> Remove outdated suggestion to declare equals as extension

_data/oss-projects.yml
Please add my DB access library to the list. https://kotlinlang.org/docs/resources.html
=> Add KotliQuery to the list of OSS projects

_data/companies-using-kotlin.yml
The Android app is still in beta, early testers can go here to try it out: http://rgr.im/beta
=> Add Roger Android app to companies :smile:

_data/videos.yml
General Overviews is a section for introduction sessions longer than `Get Started`
=> added `General Overviews` section

docs/reference/collections.md
clarified on creating collections
fixed two typos
one note on stylistics
=> clarified on creating collections

_layouts/resources.html
increased the number of OSS kotlin projects from 400 to 2000
=> increased the number of OSS kotlin projects

_data/oss-projects.yml
Stew is a simple soup.io app for Android
=> Add Stew to list of OSS projects using Kotlin

_data/companies-using-kotlin.yml
Congrats on releasing Kotlin 1.0!!
=> Add StyleShare to companies using kotlin

docs/reference/null-safety.md
We are not eliminating nulls, we are making them harmless
=> Null safety: Wording fixed

docs/reference/using-gradle.md
`compileTest` should be `testCompile`.
=> Fixed gradle scope reference

docs/reference/data-classes.md
When I read this, it felt a bit awkward. I thought I'd take a shot at making it a little better.
=> Simplify the description of a "data" class

README.md
=> Fixed link to Rake repo

_data/oss-projects.yml
Add Android library in Kotlin.
=> Add Zipangu to list of OSS projects

docs/reference/using-gradle.md
Because it is not obvious that a sequence of steps is needed, not just the plugin setup 
Initial SO question: http://stackoverflow.com/questions/36226278/setup-kotlin-project-with-gradle
=> added summary

docs/resources.md
I move project from javaby to kotlinby https://kotlinby.github.io/awesome-kotlin/
And also attach it to nice domain kotlin.link
=> Update link to awesome kotlin

docs/reference/idioms.md
Example for using of `reified`. It's quite frequently asked at https://kotlinlang.slack.com/
=> Idioms: using of `reified` for convenient overloads of generic functions

docs/reference/idioms.md
Just a little syntactic pedantry.
=> Plural, not contraction or possessive

docs/reference/coding-conventions.md
a summary of the conventions used in stdlib
=> added property-over-function section

_data/companies-using-kotlin.yml
Mentioning apps written in Kotlin at Maxwell Forest.
=> Add Maxwell Forest to companies using Kotlin

docs/reference/using-gradle.md
- Add note about mixes Java/Kotlin code under Android
- Add kotlin-test-junit
- Add section on kapt
=> Update gradle page

_data/companies-using-kotlin.yml
Added Infinum to list of companies using Kotlin in production.
=> Update to list of companies using Kotlin

_data/oss-projects.yml
Adding Fuse - The simple generic LRU memory/disk cache for Android written in Kotlin
Repo: https://github.com/kittinunf/Fuse
=> Update OSS projects adding Fuse

docs/reference/faq.md
"Where I can get a logo" is a very frequently asked question. This info should be somewhere on the site and searchable.
=> added a link to the logos resourse

_data/companies-using-kotlin.yml
=> Added Lunar Labs to companies using Kotlin

docs/reference/idioms.md
https://github.com/yole/kotlin-style-guide/issues/18
=> nullable Boolean

docs/reference/object-declarations.md
the initial SO question: http://stackoverflow.com/questions/37262468/static-initialisation-block-in-kotlin
maybe it is worth it to describe the "static init" use case in more detail in the corresponding section and/or the idiom section
=> clarified the semantics for companion object initialisation

docs/reference/generics.md
"Type parameters" is an incorrect term here
=> Rephrase sentence in "Generic functions"

docs/reference/comparison-to-scala.md
Analog to https://kotlinlang.org/docs/reference/reflection.html#function-references:
```
def isOdd(x: Int) = x % 2 != 0
// isOdd: (x: Int)Boolean
val numbers = List(1, 2, 3)
// numbers: List[Int] = List(1, 2, 3)
println(numbers.filter(isOdd))
// List(1, 3)
```
=> Remove member references

docs/reference/faq.md
If it is some kind of a wordplay, I don't get it, but "Objected-Oriented" is an accepted term.
=> Typo in FAQ

docs/reference/index.md
the references use two different styles - html and markdown. I used html, but feel free to clean it up
the description for the book is copied from leanpub
=> added "Modern Web Development with Kotlin" book

docs/reference/annotations.md
Remove `public` modifier from `annotations.md`.
=> Remove redundant visibility modifier from annotations.md

data/events.yml
The request adds:
1. GOTO Copenhagen 2016
2. DevCongress Meetup
3. Mobius 2016
4. Droidcon Berlin
5. Tech Shock Meetup
6. TopConf Tallinn 2016
7. BelarusKUG Meetup 2
8. BelarusKUG Meetup 2
=> Add 8 talks

data/events.yml
I've added 4 talks
1. Build Stuff 2016
2. AnDevCon
3. Curso Presencial
4. Training
and submitted some fixes to the previous talks descriptions
=> Add 4 talks

data/events.yml
13 talks are added
"Kotlin Night in London" (3 talks)
"NY JavaSIG"
"Android Meetup #7"
"MOPCON 2016"
"JOKER 2016"
"SpaceR International Competition"
"JCConf Taiwan 2016"
"GOTO Copenhagen 2016"
"SPA2016"
"BangaloreJUG"
"Kotlin Night in San Francisco"
some videos and slides are added to the old content
=> add_13_talks

data/events.yml
GDG devfest siberia
GDG Pilsen
F(By) 2 talks
NoSlidesConf 2016
Advanced Java Estonia
GDG KPI
+ slides, video to Pixel Camp
=> add_7_talks

data/events.yml
added
2 videos from Droidcon NYC 2016
Slides from "An evening with Industry Engineers @Square NYC"
=> events_update

data/companies-using-kotlin.yml
Thanks a lot!
Kotlin makes our works more happy!
=> Add Connehito Inc

pages/docs/tutorials/getting-started.md
=> typo correction

pages/docs/reference/using-maven.md
at least from my checks tests did not run
=> there was a mistake in the tests location

data/events.yml
1. Kotlin Night Oslo (2)
2. Live Webinar 
Content: JUG IL, F(by), Geek breakfast Toulouse
=> 3 talks & content 

data/events.yml
1. Mobilization 2016
2. Android в лицах
3. Android DevConference 2016
4. GeekOUT 2016
5. Codemotion Milan 2016
Content: Retty tech cafe, GOTO 2016
=> 5 talks & content

pages/docs/reference/lambdas.md
https://youtrack.jetbrains.com/issue/KT-15702
=> Document how a value is returned from a lambda

data/events.xml
1. Guatemala Kotlin Meetup
2. MobileTech Conference
3. CTO Roundtable. Berlin
4. Lyon Kotlin User Group
5. Kotlin user group Berlin
6. GDG Cincinnati
7. GOTO Chicago
8. SpringOne Platform 2016
9. Kotlin User Group Bucharest
=> Add talks to events.xml.

pages/docs/reference/collections.md
Original sentence did flow well when I read it initially.
=> Reconstruct sentence for clarity

data/events.xml
My fault, my previous (merged) PR contained wrong date.
=> Fix event date

data/cities.yml, data/events.xml
1. Kotlin Belgium
2. Toronto Java User group
3. Tech at Agoda
4. JavaLand 2017 (2)
5. Kotlin para desarrolladores Android
6. Mobile Tea #14: Mobile and the City
7. Kotlin en Acción para Android Developers
8. Functional Miners - 02.2017
9. JUG SAXONY CAMP Leipzig 2017
10. Devoxx France
11. ACCU 2017
12. DroidKaigi 2017 (3)
13. Monthly Kotlin users get-together
14. Kotlin user group Berlin
15. Japan Java User Group
16. Android Developer Group Nürnberg
17. GDG Bologna
18. Mobile Tea #14: Mobile and the City
=> Add 19 talks 

pages/docs/reference/whatsnew11.md
Add more API usage examples, and subsections about Map.minus and takeUnless.
=> What's new in stdlib 1.1

data/cities.yml, data/events.xml, pages/community/user-groups.md
Talks
1. Kotlin Night in Warsaw
2. Kotlin Night Riga (3)
3. Kotlin Night São Paulo 2017 (3)
4. Riga DevDays 2017 
5. Grand Rapids Java Users Group 
6. CodeJam: A Cup Full of JVM
7. Android Talks @Cookpad 
8. Android Developer meetup (2) 
9. Kotlin User Group Serbia 
10. Mobile Dev Meetup 
11. GDG Rhein-Main
Content
1. Kotlin social graph - Roberto Franchini, video
2. Ruslan Ibragimov - Fullstack Web with Kotlin, video
3. Mario Arias - Functional Programming in Kotlin with funKTionale, video 
4. 194. WJUG - Flash talks (Kotlin, Android, Spock, Java 9), slides
5. Introducción a Programación Funcional en Kotlin  Juan Liska, slides
6. Android Developers Presentation: Be More Productive with Kotlin  Brandon Wever, slides
7. The Three Laws of TDD  Robert Martin, video
Czech Kotlin User Group
=> Add 16 talks, content, 1 user group

pages/docs/reference/ranges.md
Add necessary casting in functions and change -1.0 to -1L
=> Correct ranges.md

pages/docs/reference/compatibility.md
Fix issues as following snapshots:
---
---
---
moreover: make tables aligned even in markdown text.
=> fix table columns and italic text in compatibility.html

data/cities.yml, data/events.xml, pages/community/user-groups.md
Baku
Toulouse
Vancouver
Minneapolis
=> Add 4 User Groups

data/companies-using-kotlin.yml
Adding Hootsuite to the list of Companies using Kotlin
=> Adding Hootsuite to List of Companies using Kotlin

pages/docs/reference/delegated-properties.md
Very small change but I believe it makes more sense now.
=> Small change to the wording of map example

pages/docs/reference/type-safe-builders.md
Use destructuring to make the renderAttributes function more elegant and remove some redundant brackets. That's all :)
=> Minor improve on the demo code

static/css/reset.scss
See https://youtrack.jetbrains.com/issue/KT-16543
=> Use subpixel font smoothing instead of antialiased

pages/community/user-groups.md
Submitted the KUG form to @meilalina, this is to add Sydney KUG to the list of user groups with updated URL.
=> Add Sydney to user groups

data/events.xml
1 correction (links) 
3 additions.
=> Past events updated.

data/companies-using-kotlin.yml
Adding Tiendeo to the list of Companies using Kotlin
=> Adding Tiendeo to List of Companies using Kotlin

pages/docs/tutorials/coroutines-basic-jvm.md
=> Update kotlinx.coroutines version and include configuration for JCenter

data/testimonials.yml
Fix Android word in home of kotling.org
=> Fix Android word

pages/docs/reference/operator-overloading.md
Introduce more sections so that the links to them could be created easily
=> Restructure operator overloading page

pages/docs/reference/index.md
=> Fix grammar in index.md

pages/community/slackccugl.md
This is a minor detail, but I don't think it is a good idea for any instruction to read `Perform threats of violence`, ever. I added the repeating negations so that even without the contexts the phrases could not be misunderstood.
=> Added the negations to the `not to do` chapter

data/cities.yml, data/events.xml, pages/community/user-groups.md
Add 65 Talks
1. Studenckie Grupy .NET
2. KeepCoding®
3. Java User Group Łódź
4. Kotlin Toronto
5. Lumesse Tech Ideas Worth Spreading
6. Android Dev Perú
7. Kotlin User Group Munich - KUG Munich
8. GDG Munich Android
9. Java User Group Argentina
10. Kotlin Nights CDMX
11. Kotlin User Group of Bangladesh
12. React NYC
13. GDG Leeds
14. Java User Group Japan
15. Google Developer Group Omaha
16. Kotlin読書勉強会
17. JEE Conf
18. DAM-MG | Desenvolvimento App Móveis MG | 
19. The Jacksonville Software Architecture SIG<
20. I/O Extended 2017 GlobalLogic BA
21. Android Talks @ Cookpad #2
22. Post I/O Holywar
23. Comaqa Spring 2017
24. 集まれSwift好き！Swift愛好会 vol19
25. Kotlin 101
26. Google Developer Group TechBite Warszawa #3
27. GDG Berlin Android
28. The Sonora Software Developers Group
29. GDG Montreal …
=> Add 65 talks

pages/docs/reference/functions.md
Either go that way or add three dots to the body of the function see `fun powerOf(...)` below.
=> make return value of the fun double(...) explicit

pages/docs/reference/collections.md
=> Minor grammar fix

pages/docs/reference/returns.md
In order to draw attention to the criticial point, added comments to the code. Also fixed 1 typo regarding "anonymous"
=> Added code comments, fixed 1 typo

pages/docs/reference/functions.md
=> Array's size is a property

pages/docs/tutorials/spring-boot-restful.md
I have also submitted a pull request on kotlin-examples with these changes: https://github.com/JetBrains/kotlin-examples/pull/49
=> Update to idiomatic Spring Boot + Kotlin application

pages/docs/tutorials/android-frameworks.md, pages/docs/tutorials/android-plugin.md
Minor code cleanups to follow coding convention in android tutorials. :)
=> Minor coding convention cleanups

data/cities.yml, data/events.xml, pages/community/user-groups.md
1. JDD Сonference 2017
2. Cyber Agent
3. Android Meetup - Rio de Janeiro
4. Auckland Android Community
5. Google Developers Group Dusseldorf
6. South Bay JVM User Group
7. Twin Cities Kotlin User Group
8. Columbus Kotlin User Group
9. Austin Android Developers Meetup
10. Google Developers Buenos Aires
11. My Heritage Hosts: Cross Technologies Challenges
12. Chicago Kotlin Users Group
13. Kotlin TLV
14. Google Developers Group Iasi
15. Kotlin Rhein-Main (2)
16. Tech Talks Kotlin (2)
17. Belarus Kotlin User Group (2)
18. Kotlin Toronto
19. Developer User Group
20. Android Developer Group Poznan
21. Kotlin User Group Berlin
22. Kotlin Budapest User Group (2)
=> Add 27 talks, 4 UGs

pages/docs/reference/sealed-classes.md
see https://discuss.kotlinlang.org/t/sealed-classes-and-when-expressions/3980
=> clarify expressions vs statements for checking

data/cities.yml, data/events.xml, pages/community/user-groups.md
1. JVM language summit
2. Kotlin TLV
3. JavaOne 2017 (2)
4. Motor City CocoaHeads
5. Kotlin読書勉強会
6. #AndroidSofia
7. GDG Dnipro
8. Noun Kotlin User Group
9. Google Developers Group - Cloud Vancouver
10. Orange County Kotlin
11. Nashville Mobile Developers User Group
12. The London Android Group
13. GDG Android Bolivia
14. GeekNight Kampala: July 2017
15. GDG Cairo
16. GO-JEK &amp; JVM User Group
17. Kotlin DFW
18. Kotlin User Group Munich
19. The Developer Conference São Paulo 2017
20. SPTCC 2017
21. Japan Android Group
22. Kotlin User Group Cologne
23. GDG Hamburg Android
24. AlmeriaJS
25. Kotlin South Florida User Group
26. Japan Kotlin User Group
27. Code Youngstown
28. potatotips #42 (iOS/Android開発Tips共有会)
29. Java User Group Cologne
30. Centro de Treinamento da Novatec
31. Android …
=> Add 37 talks 

pages/docs/reference/java-interop.md
=> Fix Kotlin class things in java-interop.md

pages/docs/reference/classes.md
=> Corrected the sample in "Overriding Properties"

pages/docs/reference/javascript-dce.md
Add H1 heading as the title of javascript-dce.md, as other page did.
=> Add H1 heading as the title of javascript-dce.md

pages/docs/reference/lambdas.md
sortBy doesn't return anything and works only on mutable lists
=> Change sortBy to sortedBy

pages/docs/reference/operator-overloading.md
Mentioned property delegation operator functions in Operator overloading.
=> Metioned property delegation operators in Operator overloading

pages/docs/reference/basic-types.md, pages/docs/reference/equality.md
[KT-17639](https://youtrack.jetbrains.com/issue/KT-17639)
=> Document floating point comparisons

pages/docs/reference/data-classes.md
https://youtrack.jetbrains.com/issue/KT-19468 
https://youtrack.jetbrains.com/issue/KT-20099
=> Document data class members clashes and inheritance

pages/docs/reference/data-classes.md
Many people think data-classes are just DTOs, stupid bags with data.
Attempting to say that `data` modifier brings some functionality.
I'd be glad to see some suggestions how to make this more clear.
=> Attempt to show that data-classes are not just DTOs

pages/docs/reference/delegated-properties.md
Make the first example to be easier to modify into a compilable code after copy-paste
=> Modified sample in "Providing a delegate"

pages/docs/reference/basic-syntax.md
I was unable to find explicit mention of top-level variables.
This is the simplest fix.
=> Mentioned top-level variables

pages/docs/reference/native-overview.md
=> Fix incorrect markdown indents in native-overview.md

pages/docs/reference/data-classes.md
=> Fixed small spelling mistake in data-classes.md

data/cities.yml, data/events.xml, pages/community/user-groups.md
Talks:
1. Google Developer Group Nice
2. Ciklum Ukraine/Belarus knowledge-sharing community
3. Kotlin User Group Hamburg
4. Spring Meetup Paris
5. Android Camp Bolivia 2017
6. GDG Toulouse
7. Kyiv Kotlin UG: First Blood
8. GDG DevFest Coimbra
9. Brooklyn Kotlin
10. GDG Nuremberg Android
11. OKC JUG
12. Umeå Java User Group
13. Women Who Code Berlin
14. Google Developer Group Salt Lake
15. St. Petersburg Kotlin User Group (2)
16. Phoenix Software Engineering Reading Group
17. Madrid Android Developer Group
18. Kotlin Programlama Diline Giriş
19. Kyiv Kotlin UG: First Blood
20. Software Freedom Day 2017 | MUFIX Community
21. Die nächsten Treffen unseres Expertenkreises Java
22. BITSathy Developers Fest
23. javaBin Bergen
24. Kotlin Paris Meetup (2)
25. Google Developer Group Silicon Valley …
=> Add 62 Talks, 5 UGs

pages/docs/reference/equality.md
to put more important information to the front.
Inspired by https://stackoverflow.com/questions/48472082/how-to-explain-these-kotlin-codes-about-int-type
=> Clarify the meaning of `===` for non-object types; reorder sections

pages/docs/reference/returns.md
https://youtrack.jetbrains.com/issue/KT-22646
=> Improve code examples in manual section "Return at Labels" (#KT-22646)

pages/docs/reference/data-classes.md
https://youtrack.jetbrains.com/issue/KT-22377
=> Updated data class documentation to explain excluding properties.

pages/docs/reference/object-declarations.md
1. Speaking not so loud about singleton usefulness. Singletons should be used with caution, if ever used.
2. Note about thread-safety. As I can see, the question about thread-safety is asked frequently.
=> object declarations clarifications

pages/docs/reference/classes.md, pages/docs/reference/null-safety.md
Issue [KT-22725](https://youtrack.jetbrains.com/issue/KT-22725)
* Add a section on initialization order of the base class describing the pitfall of uninitialized state;
* Minor edits in terminology and phrasing
* Format a few paragraphs as notes
* Add a link from Null Safety where it tells when an NPE can still occur in Kotlin
=> Update Derived Classes

pages/docs/reference/android-overview.md
=> Add operator to snippet 

data/cities.yml, data/events.xml, pages/community/talks.md, pages/community/user-groups.md, pages/docs/reference/index.md
Add 98 Kotlin talks
1. Richmond Java Users Group
2. Phoenix Software Engineering Reading Group
3. The Dutch Android User Group
4. Chicago Kotlin Users Group
5. Kotlin Utah
6. Kotlin user group Berlin (3)
7. KGDG Kampala
8. The JVM Thing (3)
9. Java User Group Görlitz
10. Richmond Java Users Group
11. 日本Kotlinユーザグループ
12. APP BUILDERS SWITZERLAND 2018
13. ioScrum
14. Istanbul Kotlin User Group
15. droidcon italy (5)
16. Android Makers Paris| 2018 (8)
17. Mobius (3)
18. OpenValue
19. Columbus Kotlin User Group
20. Kotlin User Group Bucharest
21. GDG London
22. Kotlin London
23. GDG Berlin Android
24. GDG Santo Domingo
25. Tech Talent South - Dallas
26. Nantes Java User Group
27. Eastside Android Development Meetup
28. GDG VUT
29. JetBrains Day Chennai
30. Cork Java User Group
31. Jalandhar …
=> Kotlin community section update

pages/docs/reference/js-modules.md
=> Fix typo and add comma

pages/docs/reference/index.md
It was missing and inconsistent with other sentences on this page.
=> Add a missing full stop

pages/docs/reference/js-interop.md
I believe it is a typo, could be wrong though.
=> fix: fix typo

pages/docs/reference/lambdas.md
I'm a beginner with Kotlin, and I didn't know the method "repeat()" of CharSequence in Kotlin. First time I saw code like this:
val repeat: String.(Int) -> String = { times -> repeat(times) }
consider it as a recursive function type certainly, and I was confused: how does it recurse? There even wasn't a recursive condition.
This mistake last a while till I found out that method "repeat()" belongs to CharSequence in Kotlin. It might happen to some other new guys like me.
This is not a good sample. If you want to explain something, focus on that point only, try to avoid things which can bring misunderstanding.
=> Refactor name to avoid misunderstanding

pages/docs/reference/using-ant.md
* Add monospace style to "${kotlin.lib}"
=> Minor changes

templates/pages/books.html
This PR fixes the positioning of the last book on the docs/books.html page.
=> Fix book header positioning

pages/docs/tutorials/mixing-java-kotlin-intellij.md
Small spelling fix in the description: -> This tutorials = This tutorial
=> Small spelling fix

pages/docs/reference/collections.md
Added explanation about covariance
=> Added explanation about covariance

pages/docs/reference/generics.md
It's not clear for the first time, where is the problem in the original code.
Now it's more intuitive.
=> Refine compiler's error message

pages/docs/tutorials/native/apple-framework.md, pages/docs/tutorials/native/dynamic-libraries.md, pages/docs/tutorials/native/gradle-for-kotlin-native.md, pages/docs/tutorials/native/mapping-primitive-data-types-from-c.md, pages/docs/tutorials/native/targeting-multiple-platforms.md
Update tutorial to include missing features
=> Update kn tutorials for 0.9.2

pages/docs/tutorials/native/apple-framework.md, pages/docs/tutorials/native/basic-kotlin-native-app.md, pages/docs/tutorials/native/dynamic-libraries.md, pages/docs/tutorials/native/interop-with-c.md, pages/docs/tutorials/native/mapping-function-pointers-from-c.md, pages/docs/tutorials/native/mapping-primitive-data-types-from-c.md, pages/docs/tutorials/native/mapping-strings-from-c.md, pages/docs/tutorials/native/mapping-struct-union-types-from-c.md, pages/docs/tutorials/native/targeting-multiple-platforms.md, pages/docs/tutorials/native/working-with-klib.md
Removed `you` and `here` from tutorial texts to make the style aligned
=> Kn fix english

pages/docs/reference/whatsnew13.md
=> Fixed cobfusingly mixed variable names 'x' and 's'

pages/docs/reference/whatsnew13.md
Make receiver nullable, fixing type error
=> Fix code sample in whatsnew13.md

pages/docs/tutorials/multiplatform-library.md
fix indents. (macosTest-kotlin was broken tree)
=> fix(mpplib): file tree indent

pages/docs/tutorials/kotlin-android.md
- also remove '3.0' version within page to improve readability
- also remove extra whitespace
=> docs(android): Improve accessibility (alt attributes)

package.json, yarn.lock
=> fix: increase extend version

pages/docs/reference/js-modules.md
=> Standard maven declaration order

pages/docs/reference/experimental.md
small suggestions to the wording. Not much though.
=> Watson Proof

data/_nav.yml, pages/docs/reference/coding-conventions.md, pages/docs/reference/idioms.md, pages/docs/reference/scope-functions.md
added documentation on scope functions.
=> docs: scope functions

data/_nav.yml, pages/docs/reference/experimental.md, pages/docs/reference/generics.md
Added documentation on @Experimental and @useExperimental annotations.
=> docs: Doc on @Experimental

package.json, yarn.lock
https://youtrack.jetbrains.com/issue/TPV-374
=> chore(deps): drop cross-env

kotlin-website.py
https://youtrack.jetbrains.com/issue/ADM-29583
https://youtrack.jetbrains.com/issue/JS-9001
=> fix drop search params from static folder

pages/docs/reference/null-safety.md
=> Fix explaining comment when using let

pages/docs/reference/index.md
Fixed typos and rephrased some sentences.
=> fix: texts on the main doc page

pages/docs/reference/using-gradle.md, pages/docs/reference/using-maven.md
Please merge when 1.3.30 comes out.
=> docs: Add JVM targets 9..12 available since 1.3.30

pages/docs/tutorials/native/apple-framework.md
In "There are some small differences, though. In Kotlin *any object has the only one instance.*"
=> Update apple-framework.md - grammatic error

pages/docs/tutorials/android-frameworks.md
Removed the dependency according to [KT-28790](https://youtrack.jetbrains.com/issue/KT-28790)
Fixed line breaks in samples.
=> docs: removed the kapt dependency for DataBinding

pages/docs/reference/ranges.md
In the comment it says that the range will go to 10. But the code says it should go to 4. I changed the comment.
=> Corrected comment

pages/docs/reference/list-operations.md
Add output to removing section in list specific operations
=> Add output to removing section

pages/docs/reference/extensions.md
a lowercase L may be confused with the number 1
=> renamed variable in example code

pages/docs/tutorials/native/mpp-ios-android.md
The tutorial was updated and simplified. Newer Gradle DSL MPP syntax is used.
=> Improving Multiplatofrm iOS and Android tutorial

pages/docs/reference/keyword-reference.md
With this change a list of keywords becomes complete (exhaustive).
=> Add reserved keyword typeof

pages/docs/reference/idioms.md
Using `in` instead of `contains`
=> Idiom to check if collection contains an element

pages/docs/reference/compiler-plugins.md
Matching the groovy configuration to the example and Maven configuration
=> Update sam-with-receiver section

pages/docs/tutorials/command-line.md
=> Added a Chocolatey install option.

pages/docs/reference/idioms.md
IMHO this is a very unambiguous idiom. (Can't think of any reason not do use it.)
=> Added idiom TODO()

pages/docs/reference/classes.md
correct indentations.
delete extra whitespaces for visibility.
=> Update classes.md modifications in indentations

pages/docs/reference/idioms.md
Added an example for use of `apply` to configure properties of an object.
=> Added `apply` idiom

pages/docs/tutorials/quick-run.md
line 31 -- make a software unit? It was compose a software unit, but I don't know if this is the right term, google couldn't help.
=> proofed Watson

pages/docs/tutorials/command-line.md
This update adds a sample for the reader to understand how to pass a command line argument containing a `-` to a kotlin script.
=> Adds demo for passing arguments to kts files

pages/docs/reference/basic-types.md
Edited the grammar for a sentence:
changed  "... more that 6-7 decimal digits, it will be rounded" 
to "... more than 6-7 decimal digits, it will be rounded"
=> Edited wording for a sentence

pages/docs/reference/javascript-dce.md
Because Kotlin 1.3 is released.
=> Update javascript-dce.md for Kotlin version 1.3

pages/docs/reference/null-safety.md
It's a good practice to refer HTTPS sites if available.
=> Switch Wikipedia link from HTTP to HTTPS

pages/docs/tutorials/getting-started.md
It seems more relevant to start with IntelliJ IDEA related instructions first.
=> Reword content of getting-started.md

pages/docs/reference/server-overview.md
Micronaut is a young prospect in the league of server-side frameworks, offering modern features and outstanding performance out of the box. I think the documentation should mention it, that's why I made this PR.
=> Update server-overview.md with Micronaut

static/js/com/head-banner.js, templates/inc/nav/header-banner-nav.html
Reverts JetBrains/kotlin-web-site#1650
=> Revert "feat(banner): add info about Try obsolete"

pages/docs/reference/classes.md
=> Non-canonical modifiers order.

data/_nav.yml, pages/docs/reference/building-mpp-with-gradle.md, pages/docs/reference/mpp-dsl-reference.md
Add a new page: DSL reference for MPP Gradle plugin
Staging build: https://branch-mpp-dsl-reference.kotlin-web-site.labs.jb.gg/
=> feat: MPP Gradle DSL reference

pages/docs/reference/delegated-properties.md
Added detailed info and examples of delegated properties as discussed in [this PR](https://github.com/JetBrains/kotlin-web-site/pull/1552)
=> chore: clarified creation of delegated properties

pages/docs/reference/null-safety.md
Comments added in the sample code for both null references and non-null references
=> Comments added : sample code for reference types

pages/docs/reference/basic-types.md, pages/docs/reference/control-flow.md
https://youtrack.jetbrains.com/issue/KT-39176
=> chore: clarify object identity for nullable references

pages/docs/tutorials/javascript/setting-up.md
Juts a few wording and typo fix proposals. :)
=> Fix wording and minor typos in turotials/javascript/setting-up.md

pages/docs/reference/whatsnew14.md
Staging: https://branch-explicit-api-mode.kotlin-web-site.labs.jb.gg/docs/reference/whatsnew14.html
=> feat: add explicit API mode to whatsnew14.md

data/releases.yml, pages/eap/configure-build-for-eap.md, pages/eap/index.md
Added 1.4-M3 build details to the EAP table, introduced EAP variables, updated their values for 1.4-M3
=> update: 1.4-M3 build details

data/_nav.yml, pages/education/why-teach-kotlin.md, src/processors/processors.py, static/css/com/_bits/_hr.scss, static/css/com/_page-content/_page-content.scss, static/css/com/page-content/page-content-v2.scss, static/js/components/kto-qoute/kto-quotes.scss, static/js/page/education/education.scss, templates/pages/education/index.html
=> Why Teach Kotlin

pages/docs/reference/js-overview.md
Added "Kotlin/JS, Today and Tomorrow" video
=> Kotlin/JS, Today and Tomorrow

pages/docs/reference/collection-aggregate.md, pages/docs/reference/collection-elements.md, pages/docs/reference/list-operations.md, pages/docs/tutorials/native/mapping-strings-from-c.md
Update docs according to this list of deprecations and stabilizations in 1.4: https://jetbrains.quip.com/wmawAbqodCFk/14-Experimental-and-deprecated-API-review
=> feat: 1.4 new stable API, deprecations of old API

pages/docs/reference/java-to-kotlin-interop.md, pages/docs/reference/whatsnew14.md
Doc update for new -Xjvm-default modes added in 1.4
=> update: 1.4 new -Xjvm-default modes

pages/docs/reference/whatsnew14.md
Added What's new about a new type inference algorithm & callable reference improvements
=> feat: new type inference algorithm & callable reference improvements

data/releases.yml, pages/eap/index.md
Added 1.4-rc build details to EAP table; updated variables
=> 1.4-rc build details

pages/docs/reference/functions.md, pages/docs/reference/whatsnew14.md
Added what's new about mixing named and positional arguments; updated functions documentation on this topic
=> feat: mixing positional and named arguments

pages/security.md, src/processors/processors.py, static/css/com/_typo/typo.scss, static/css/com/page-content/page-content-v2.scss, static/css/config/_base.scss, static/js/page/community/community.scss, templates/inc/footer.html
added Kotlin Security page.
reviewed by: Nikolay Krasko, Stas Erokhin, Egor Tolstoy
=> added kotlin security

pages/docs/reference/whatsnew14.md
* Added a trailing comma to What's new in Kotlin 1.4.
* Fixed formatting and links
=> feat: trailing comma what's new

pages/docs/reference/whatsnew14.md
Updated based on feedback of David Winer from Google
=> update: IR JVM BE what's new

pages/docs/reference/faq.md
https://discuss.kotlinlang.org/t/what-does-the-acronym-oss-mean/18556?u=wasabi375
Especially for new programmers the term OSS might not be well known. Also it's most often used as a noun and not as an adjective. Because of that it's even more confusing.
=> Update FAQ - changed OSS acronym to open source

pages/docs/reference/whatsnew14.md
Add descriptions on K/N features to **What's New in Kotlin 1.4**
Staging: https://branch-1.4-native-whatsnew.kotlin-web-site.labs.jb.gg/docs/reference/whatsnew14.html#kotlinnative
=> feat: add Kotlin/Native what's new

data/cities.yml, data/events.xml, pages/user-groups/user-group-list.md
Closes #1781 without conflicts
=> Events update in July 2020

pages/docs/reference/compatibility-guide-14.md
- https://youtrack.jetbrains.com/issue/KT-37280
- https://youtrack.jetbrains.com/issue/KT-32126
- https://youtrack.jetbrains.com/issue/KT-31670
- https://youtrack.jetbrains.com/issue/KT-34975
- https://youtrack.jetbrains.com/issue/KT-25175
- https://youtrack.jetbrains.com/issue/KT-18541
=> feat: add more new inference & tailrec changes

pages/docs/reference/whatsnew14.md
add what's new about null-check optimizations from [this blog post](https://blog.jetbrains.com/kotlin/2019/08/kotlin-1-3-50-released/)
=> feat: add what's new about null checks

pages/docs/reference/whatsnew14.md
adapted description from [this blog post](https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/#kotlin-jvm)
=> feat: add whatsnew about type annotations in the JVM bytecode

.idea/kotlin-web-site.iml, .idea/misc.xml, data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) August 2020, part 2

data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) August 2020, part 3

pages/docs/reference/compiler-reference.md
https://youtrack.jetbrains.com/issue/KT-41303
https://youtrack.jetbrains.com/issue/KT-41300
=> update: add info about using quotes with CLI utils on Windows

pages/security.md
updated a link to create a security issue and removed irrelevan information in Kotlin Security as agreed with Sergei Pecherkin.
=> fix: updated a way to create a security problem

pages/docs/reference/android-overview.md, pages/docs/reference/multiplatform.md, pages/docs/reference/native-overview.md, templates/inc/pages/index/intro.html
* updated a link to the KMM landing page
* added a few links to KMM pages to the Multiplatform overview
=> update: added and updated KMM links

pages/docs/reference/compatibility-guide-14.md
https://youtrack.jetbrains.com/issue/KT-41482
=> update: add fallback option for unified null checks to Compatibilty Guide

data/cities.yml, data/events.xml
=> chore (events) August 2020, part 4

pages/docs/reference/classes.md, pages/docs/reference/coding-conventions.md, pages/docs/reference/functions.md
add trailing commas to Coding Conventions (coding-conventions.md)
=> feature: add trailing commas

data/events.xml
=> chore (events) September 2020, part 1

data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) September 2020, part 2

pages/docs/reference/reflection.md
fix for [KT-41280 Reflection documentation is missing the dependencies coordinates](https://youtrack.jetbrains.com/issue/KT-41280)
=> update: add info about reflection dependencies

data/events.xml
=> chore (events) September 2020, part 3

data/cities.yml, data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) September 2020, part 4

pages/docs/reference/collection-ordering.md
missing indentation which (probably) causes a new line in preview
=> Missing indentation

data/_nav.yml, pages/releases.md, pages/roadmap.md
* Added Kotlin Roadmap roadmap.md
* Rearranged tree elements: from now on releases.md is a part of the tree
=> feature: add Kotlin Roadmap

data/_nav.yml, pages/roadmap.md
fix: add explicit icons for postponed items
=> fix: add explicit icons for postponed items

data/events.xml
=> chore (events) October 2020, part 1

pages/docs/reference/whatsnew14.md, pages/docs/tutorials/coroutines/coroutines-basic-jvm.md
=> Use sumOf instead of map+sum

data/cities.yml, data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) October 2020, part 2

pages/docs/reference/migrating-multiplatform-project-to-14.md, pages/docs/reference/mpp-publish-lib.md
updated mpp publication structure; updated the topic structure; added about gradle-bintray-plugin
=> update: MPP publication structure

data/cities.yml, data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) November 2020, part 1

pages/docs/reference/properties.md
This is based on the forum discussion here: https://discuss.kotlinlang.org/t/property-vs-field/8179/10?u=wasabi375
=> Clarified the usage of fields in kotlin

pages/kotlin-pdf.md
Added a Kotlin PDF page to conduct a survey on PDF usage.
=> update: added a Kotlin PDF page 

pages/docs/reference/mpp-publish-lib.md
* Updated a note on publishing a multiplatform library based on user's feedback.
=> update: updated a note on publishing a multiplatform library

data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) November 2020, part 2

pages/docs/reference/mpp-build-native-binaries.md, pages/docs/reference/mpp-configure-compilations.md, pages/docs/reference/mpp-dsl-reference.md, pages/docs/reference/mpp-set-up-targets.md
=> fix minor typo

data/events.xml
=> chore (events) December 2020, part 1

data/cities.yml, data/events.xml
=> chore (events) December 2020, part 2

pages/docs/reference/idioms.md
I had an abstract class with 2 abstract methods. Now I wanted to instantiate this anonymously and implement the 2 methods. Android Studio did not provide any help on this. Frustrating. It is important to specify "object :".
The documentation (especially for Java pros) could be improved here. My contribution is a start. I would like to see a Classes overview page (above https://kotlinlang.org/docs/reference/classes.html ) where all the keywords around classes are mentioned shortly! (class, data class, open class and especially object!)
=> instantiate abstract class (new idiom)

pages/foundation/kotlin-foundation.md
* Maxim Shafirov replaces Andrey Breslav as president.
* Roman Elizarov replaces Andrey Breslav as lead language designer and in a JetBrains seat on the board.
* Grace Kloba replaces Stephanie Saad Cuthbertson in a Google seat on the board.
=> Updated Kotlin Found Board members:

pages/docs/reference/js-interop.md
The previous link for dukat gave a 404 error, just added the right(?) link to fix it
=> Update js-interop.md -- Dukat link

pages/roadmap.md
Added to a missing item to Libraries in the roadmap
=> fix: added a missing item to the roadmap

pages/roadmap.md
Added a missing postponed item to Kotlin/Native in the roadmap
=> fix: added a missing postponed item to the roadmap

pages/docs/reference/using-gradle.md
Add doc section about Gradle configuration cache.
=> update: gradle configuration cache

pages/docs/reference/sealed-classes.md
Doc update for:
- [KT-20423 Support sealed interfaces](https://youtrack.jetbrains.com/issue/KT-20423)
- [KT-13495 Sealed class hierarchy and nesting should allow more freedom](https://youtrack.jetbrains.com/issue/KT-13495)
[KEEP](https://github.com/Kotlin/KEEP/blob/sealed-interface-freedom/proposals/sealed-interface-freedom.md)
=> update: sealed interface doc

docs/topics/sealed-classes.md
Transfer changes of https://github.com/JetBrains/kotlin-web-site/pull/2011/files to WebHelp
=> update: sealed interfaces and package-wide hierarchies in WebHelp

docs/cfg/buildprofiles.xml, docs/topics/classes.md, docs/topics/object-declarations.md, docs/topics/packages.md, docs/topics/properties.md
* Added GitHub URL override for coroutines docs in buildprofiles.xml
* Added custom IDs to avoid clashes
=> fix: added GitHub URL override for coroutines docs

pages/docs/reference/classes.md
fix variable  never used.
https://pl.kotl.in/G5JBG6mk
=> fix variable `d` never used.

docs/topics/collection-aggregate.md, docs/topics/whatsnew14.md
To make sure I do everything as expected. Is there enough info?
BTW, added a snippet from [What's new 1.4](https://kotlinlang.org/docs/whatsnew14.html#new-functions-for-arrays-and-collections) but changed `mutableListOf` to `listOf`.
=> update: Describe runningFold and runningReduce

docs/topics/collection-aggregate.md
Not sure if we need to keep `sumBy` and `sumByDouble` when `sumOf` handles different types. 🤔
=> update: Collection operations (sumOf, maxOf, minOf)

docs/cfg/buildprofiles.xml
Fix for the issue https://youtrack.jetbrains.com/issue/KT-44966
=> fix: coroutines links KT-44966

docs/topics/mpp/mpp-dsl-reference.md
=> Fix tab name

docs/topics/js/js-ir-compiler.md
Non-linked and linked words duplicated each other.
=> Remove duplicate words

docs/topics/eclipse.md, docs/topics/mpp/migrating-multiplatform-project-to-14.md, docs/topics/mpp/mpp-publish-lib.md
Remove mentioning of Bintray repo and Gradle plugin from docs
=> update: remove Bintray from docs

data/cities.yml, data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) February 2021, part 1

docs/topics/jvm/jvm-test-using-junit.md
I added missing double quote in docs/topics/jvm/jvm-test-using-junit.md
=> Add missing double quote

docs/topics/kotlin-foundation.md
Update Secretary of Kotlin Foundation
=> Update Secretary of Kotlin Foundation

docs/topics/properties.md
Fix for https://youtrack.jetbrains.com/issue/KT-34171
=> fix: KT-34171 Document that setter is not called upon initialization

data/cities.yml, data/events.xml, pages/community/events.md
=> chore (events) March 2021, part 1

docs/topics/native/native-faq.md
Make the link to build instructions clickable.
=> update: native-faq.md

docs/topics/mpp/mpp-add-dependencies.md
https://youtrack.jetbrains.com/issue/KT-44911
=> update: clarified the place where to put a dependency

docs/topics/jvm/jvm-spring-boot-restful-db.md, docs/topics/jvm/jvm-spring-boot-restful.md
add videos and fix code highlighting problem
=> update: update spring boot tutorials

docs/topics/compiler-reference.md, docs/topics/faq.md, docs/topics/gradle.md, docs/topics/maven.md, docs/v.list
also add a new variable with the default jvmTarget version
=> feature: update jvmTarget, apiVersion, languageVersion versions

data/cities.yml, data/events.xml, pages/user-groups/user-group-list.md
added new events and fixing of user groups
=> chore (events) March 2021, part 2 

docs/topics/gradle.md, docs/topics/mpp/migrating-multiplatform-project-to-14.md, docs/topics/mpp/mpp-discover-project.md, docs/v.list
Update min Gradle version to 6.1. ([KT-54340](https://youtrack.jetbrains.com/issue/KT-45340)).
Add variable minGradleVersion.
=> update: min Gradle version to 6.1

docs/topics/jvm/jvm-spring-boot-restful.md
update the Spring Boot version 2.4.3 -> 2.4.5
=> update: update jvm-spring-boot-restful.md

docs/topics/sealed-classes.md
Update doc as per https://youtrack.jetbrains.com/issue/KT-45842
=> feat: KT-45842 sealed class inheritance in MPP

docs/topics/getting-started.md
=> update: update getting-started.md

data/cities.yml, data/events.xml, pages/user-groups/user-group-list.md
=>  chore (events) April 2021, part 2

docs/topics/basic-syntax.md
=> fix: fix codeblock in basic-syntax.md

.github/workflows/verify-snippets-on-push.yml
Need to open 'Issues' for the repository
=> Configure verifying workflow

docs/topics/components-stability.md
See:
- https://blog.jetbrains.com/kotlin/2021/02/new-language-features-preview-in-kotlin-1-4-30/#inline-value-classes-stabilization
- https://blog.jetbrains.com/kotlin/2021/05/kotlin-1-5-0-released/#stable-language-features
=> Inline classes are stable now

data/cities.yml, data/events.xml, pages/user-groups/user-group-list.md
added new events, videos and user group
=> chore (events) April 2021, part 3

pages/community/events.md, templates/inc/pages/index/why-section.html, templates/pages/education/index.html
[YouTrack issue](https://youtrack.jetbrains.com/issue/KTL-364)
=> KTL-364 L SEP on the homepage

docs/topics/js/js-ir-compiler.md
=> fix: KT-45870 js modes examples

docs/topics/js/js-ir-compiler.md
=> chore: KT-45550 lazy init in JS IR

README.md
Context: https://kotlinlang.slack.com/archives/C01GGPPCAA0/p1622410349001500
=> README: refer to ticket regarding adding support for local testing

docs/project.ihp, kotlin-website.py, src/search.py
- [Youtrack issue](https://youtrack.jetbrains.com/issue/KTL-329)
- [UI](https://staging.kotlinlang.org/docs/home.html)
=> KTL-329 Remove product version of search index builder and docs configuration

docs/project.ihp, kotlin-website.py, src/search.py
Reverts JetBrains/kotlin-web-site#2282
=> Revert "KTL-329 Remove product version of search index builder and docs configuration"

docs/topics/object-declarations.md, docs/topics/packages.md, docs/topics/properties.md
https://youtrack.jetbrains.com/issue/KTL-371
=> KTL-371 kotlinlang.org - docs test failed with "Element ID not unique" error

data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) May 2021, part 1

docs/topics/kotlin-doc.md
It makes it harder to miss the most important part of the section.
=> Add emphasis for heading requirement

docs/topics/data-science-overview.md
Minor correction - ggplot2 is part of the tidyverse of R packages. Some references:
- https://ggplot2.tidyverse.org/
- https://www.tidyverse.org/
=> ggplot2 is an R package

docs/topics/mpp/mpp-intro.md
Mutliplatform -> Multiplatform
=> fix: Fix typo in multiplatform intro

src/search.py
Some chapter now has other headering level
=> ktl-396: Some parts of page gradle.md doesn't exist in index

data/events.xml, pages/user-groups/user-group-list.md
=> chore (events) June 2021, part 1

docs/topics/whatsnew13.md
Should be "into a variable", not "into variable".
=> Add missing article to whatsnew13

package.json, templates/base.html, templates/pages/index.html, yarn.lock
- [KTL-379](https://youtrack.jetbrains.com/issue/KTL-379)
- [KTL-395](https://youtrack.jetbrains.com/issue/KTL-395)
- [UI](https://branch-ktl-395-header-updates.kotlin-web-site.labs.jb.gg)
=> ktl-395 fix dropdown menu highlighting and remove external link for KMM

kotlin-website.py, package.json, src/navigation.py, templates/base.html, yarn.lock
- [KTL-377](https://youtrack.jetbrains.com/issue/KTL-377)
- [KTL-378](https://youtrack.jetbrains.com/issue/KTL-378)
- [UI](https://branch-ktl-377-header-active-link.kotlin-web-site.labs.jb.gg/) (See "Teach" and "Community" pages)
=> ktl-377 fix: highlight active link in header

data/events.xml
=> chore (events) June 2021, part 2

docs/kr.tree, docs/topics/js/js-ir-compiler.md, docs/topics/js/js-ir-migration.md, docs/topics/js/js-overview.md
@kalibrov520 @dromanov-jb please check the draft too.
=> feat: JS IR migration guide

docs/topics/apple-framework.md
Makes it slightly easier to read
=> Improve English in Kotlin/Native as an Apple framework tutorial

docs/topics/jvm/java-to-kotlin-interop.md
=> fix: fix space

data/last-news.yml, data/universities.yml
Kotlin Features Survey Edition #2
=> news update 30.06.2021

SECURITY.md
https://youtrack.jetbrains.com/issue/KTL-421
=> KTL-421 Kotlinlang - add security.md

docs/topics/mpp/multiplatform.md
chore: change the width of the picture
=> chore: update multiplatform.md

docs/topics/data-classes.md, docs/topics/functions.md, docs/topics/generics.md, docs/topics/object-declarations.md
Except generics.md.
@shadrina please add this file when you're done with it.
=> chore: MKT-16782 Proofread Kotlin docs 3

templates/pages/education/index.html
YouTrack issue - [KTL-438](https://youtrack.jetbrains.com/issue/KTL-438)
=> KTL-438 Kotlinlang - add a link for "Kotlin curriculum for beginners"

data/testimonials.yml, static/js/page/index/index.scss, static/js/page/index/kotlin-highlights-section.scss, static/js/page/index/kotlin-why-section.scss, templates/inc/pages/index/why-section.html, templates/pages/index.html
- [Issue](https://youtrack.jetbrains.com/issue/KTL-413)
- [UI](https://branch-ktl-413-update-why-kotlin-on-main-page.kotlin-web-site.labs.jb.gg/)
=> KTL-413 Kotlinlang - New visual style - Main - Update "Why Kotlin" section

templates/inc/pages/index/intro.html, templates/inc/pages/index/why-section.html
[KTL-433](https://youtrack.jetbrains.com/issue/KTL-433)
=> KTL-433 Kotlinlang - remove external links

static/js/components/-vars-spaces.scss, static/js/components/kto-text.scss, static/js/page/index/kotlin-banner-section.scss, static/js/page/index/kotlin-highlights-section.scss, static/js/page/index/kotlin-news-section.scss, static/js/page/index/kotlin-why-section.scss, templates/pages/index.html
[KTL-415](https://youtrack.jetbrains.com/issue/KTL-415)
[UI](https://branch-ktl-415-update-latest-from-kotlin.kotlin-web-site.labs.jb.gg/)
=> KTL-415 Kotlinlang - New visual style - Main - Update "Latest from Kotlin" section

docs/topics/gradle.md
See how it was: https://kotlinlang.org/docs/gradle.html#incremental-compilation
Before:
=> fix: fix broken rendering of the list in gradle.md

data/schemas/user-groups.json, data/user-groups.yml, scripts/user_groups_geolocator.py
Issue: https://youtrack.jetbrains.com/issue/KT-47068
This is a prerequisite prior to adding a map that visualizes them.
The positions were obtained by:
1. Putting all KUGs on a Google map (https://www.google.com/maps/d/u/0/edit?mid=1fz4Bs85kWUjHUBkZFXICXGNyP4Q5DtI4&usp=sharing). Google's geocoding algorithm was used, by
simply searching for a given city and using the placemark suggested
by Google. Sometimes, minor adjustments were needed that required
logical thinking - I hope I got it correct, it can be always fixed
iteratively.
2. Using such Kotlin script to modify `user-groups.yml`:
```kotlin
import com.charleskorn.kaml.Yaml
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import org.w3c.dom.Document …
```
=> KT-47068: Backfill user groups positions and make position mandatory

docs/topics/install-eap-plugin.md, docs/topics/jvm/jvm-test-using-junit.md
**What does this PR do**
Fix dead or broken links in this docs page, making navigation easy for others.
=> Fix broken links in docs

static/js/page/community/community.js, static/js/page/community/community.scss, templates/pages/user-groups/user-group-list.html
Issue: https://youtrack.jetbrains.com/issue/KT-47068
Locally:
=> KT-47068: Display a map of user groups

kotlin-features/concise.md, kotlin-features/interoperable.md, kotlin-features/safe.md, static/js/page/index/index.scss, static/js/page/index/kotlin-code-examples-section.scss, templates/inc/pages/index/code-examples.html
[KTL-414](https://youtrack.jetbrains.com/issue/KTL-414)
=> KTL-414: Main - Update "Try Kotlin" section

data/schemas/user-groups.json, data/user-groups.yml, templates/pages/user-groups/user-group-list.html
[YouTrack issue](https://youtrack.jetbrains.com/issue/KTL-289)
[UI](https://branch-ktl-289-add-new-virtual-kug.kotlin-web-site.labs.jb.gg)
=> KTL-289 Please add a new type of user group to the community section

docs/topics/gradle.md, docs/topics/kapt.md
https://youtrack.jetbrains.com/issue/KT-43095
https://youtrack.jetbrains.com/issue/KT-45611
https://youtrack.jetbrains.com/issue/KT-45757
=> 1 5 30 build tools: Java toolchain, setting JDK home, Kotlin daemon's JVM args

data/user-groups.yml
=> Update URL to Tricity Kotlin User Group

docs/topics/js/js-ir-migration.md
Update in react-wrappers:
RState -> State
RProps -> Props 
cc @kalibrov520
=> update: rename react-wrappers interfaces in js-ir-migration.md

data/cities.yml, data/events.xml, static/js/page/events/event/Event.js, static/js/page/events/event/EventsStore.js, static/js/page/events/event/styles.scss, static/js/page/events/event/view.twig, static/js/page/events/map/Map.js
https://youtrack.jetbrains.com/issue/KTL-32
adding `<online>true</online>` prop for an event in the events.xml add green badge to the list:
=> KTL-32 Add "online" mark to Kotlin talks description on kotlinlang.org

static/js/com/search/search.scss
YouTrack issue: [KTL-505](https://youtrack.jetbrains.com/issue/KTL-505)
Related to #1054
=> KTL-505 Kotlinlang - replace negative z-index prop

static/js/page/community/community.js, static/js/page/education/education.js, static/js/page/events/event/EventsStore.js, static/js/page/events/map/Map.js, templates/pages/community.html
YouTrack issue: [KTL-506](https://youtrack.jetbrains.com/issue/KTL-506)
=> KTL-506 Kotlinlang - KUG map is empty

.github/workflows/close-stale-pr.yml
https://youtrack.jetbrains.com/issue/KTL-510
=> ktl-510 chore: GitHub workflow for close stale PRs

docs/topics/scope-functions.md, docs/topics/sealed-classes.md
Provide real-life use case for sealed hierarchies as per request in:
https://youtrack.jetbrains.com/issue/KT-48004
https://youtrack.jetbrains.com/issue/KT-48242
UPD: clarify rules of indirect inheritance: https://youtrack.jetbrains.com/issue/KT-48542
=> fix: kt-48004 sealed hierarchy example

docs/topics/native/native-command-line-compiler.md
I added installation instructions to native-command-line-compiler markdown file.
=> native-command-line-compiler.md edited

README.md, docs/topics/components-stability.md, docs/topics/getting-started.md, docs/topics/home.md, docs/topics/mpp/mpp-create-lib.md, docs/topics/mpp/mpp-share-on-platforms.md, docs/topics/mpp/mpp-tutorials.md, docs/topics/mpp/multiplatform-library.md, docs/topics/mpp/multiplatform.md, docs/topics/native/native-improving-compilation-time.md, docs/topics/native/native-overview.md, pages/docs/tutorials/native/mpp-ios-android.md
- merge KMM components stability into Kotlin components stability table.
- make all links from Kotlin docs to KMM docs local.
=> update: kmm stability and links

docs/topics/compatibility-guide-15.md
* KT-46378 IR backend reorders JVM fields
=> Updated compatibility guide for JVM/IR backend

pages/education/why-teach-kotlin.md, templates/pages/education/index.html
https://youtrack.jetbrains.com/issue/KTL-514
=> KTL-514 Add links to JetBrains Academy Kotlin Basics track to Education page

docs/topics/async-programming.md
Makes the call to action easier to click.
=> async-programming.md: Add link to coroutines page

docs/topics/collection-aggregate.md, docs/topics/collection-transformations.md, docs/topics/collections-overview.md, docs/topics/jvm/java-to-kotlin-idioms-strings.md
Some edits regarding collections.
=> update: different minor changes

pages/community/kotlin-nights/branding.md, pages/community/kotlin-nights/guidelines.md
https://youtrack.jetbrains.com/issue/KTL-534
=> KTL-534 Kotlin Night Materials download link is broken

docs/topics/kug-branding.md, pages/user-groups/branding.md
https://youtrack.jetbrains.com/issue/KTL-548
=> KTL-548 Unavailable branding materials

data/_nav.yml, static/js/ktl-component/courses/components/courses-list.scss
https://youtrack.jetbrains.com/issue/KTL-558
=> KTL-558 Kotlinlang - New visual style - fixes

Dockerfile, build-devserver.sh, docker-compose.yml, kotlin-website.py, mysettings.py, webpack.config.js
https://youtrack.jetbrains.com/issue/KTL-554
=> ktl-554 feat: change flask port

docs/topics/functions.md
https://youtrack.jetbrains.com/issue/KT-18541
=> Tail recursion is not allowed on open functions

static/css/base.scss, static/js/ktl-component/courses/index.scss, static/js/ktl-component/teach/components/teach-cta-block/teach-cta-block.jsx
https://youtrack.jetbrains.com/issue/KTL-561
=> Kotlinlang - New visual style - Teach - fix buttons font family

package.json, yarn.lock
=> feat(ktl-41): add link "open in playground"

static/js/ktl-component/teach/index.jsx, static/js/ktl-component/teach/style.scss, static/js/ktl-component/why-teach/quotes.json, templates/pages/education/why-teach-kotlin.html
https://youtrack.jetbrains.com/issue/KTL-561
=> KTL-561 Kotlinlang - New visual style - Teach - fixes

data/schemas/user-groups.json, data/user-groups.yml, scripts/user_groups_geolocator.py
https://youtrack.jetbrains.com/issue/KTL-572
https://youtrack.jetbrains.com/issue/KT-49574
Use "Hide whitespace" settings  to ignore indent changes on the PR :)
How the validation now looks in the IDEA:
=> KTL-572 Kotlinlang.org - new KUGs are missing on the map

static/js/ktl-component/teach/index.jsx
https://branch-ktl-567-teach-add-youtube-playlist.kotlin-web-site.labs.jb.gg
https://youtrack.jetbrains.com/issue/KTL-567
=> Ktl 567 teach add youtube playlist

docs/topics/classes.md
=> Update classes.md to remove unnecessary curly braces in example

docs/topics/contribute.md
* add info on the Kotlin plugin contributing process
* divide Kotlin compiler/stdlib and tooling
* clean up
=> update: add Kotlin plugin contributing info

docs/topics/components-stability.md, docs/topics/getting-started.md, docs/topics/js/js-overview.md
* eliminate Compose Multiplatform Alpha info
* fix the status of KMM plugin for AS
=> update: bump Compose Multiplatform to Stable

docs/topics/data-science-overview.md
Details are here: https://youtrack.jetbrains.com/issue/KT-50049
=> fix: KT-50049 substitute the broken link for data science

data/cities.yml, data/events.xml, data/universities.yml
=> chore (events) November 2021, part 2

docs/topics/set-operations.md
https://youtrack.jetbrains.com/issue/KT-50011
=> chore: clearer explanation about set operations on lists

data/cities.yml, data/events.xml, data/universities.yml
=> chore (events) December 2021, part 1

docs/topics/ranges.md
The notation can be a little bit confusing to new programmers in the comment for the until function example, especially for new programmers reading the doc with no prior experience in mathematical square brackets and parenthesis inclusion/exclusion rules.
=> Update until function example in ranges.md

docs/topics/all-open-plugin.md
Listed here: https://github.com/JetBrains/kotlin/blob/1dad549c811acf183f0b566c30d0869fef756c6a/plugins/allopen/allopen-cli/src/AllOpenPlugin.kt#L35-L54
=> List additional supported presets

docs/topics/competitive-programming.md
Used the second person – “you” instead of "we" when not meaning the Kotlin team have done or are doing something.
=> fix: use the second person

data/events.xml, data/user-groups.yml
=> chore (events) January 2022, part 1

package.json, static/js/ktl-component/teach/components/subscription-form/index.js, yarn.lock
https://youtrack.jetbrains.com/issue/KTL-656
=> KTL-656 Kotlinlang - subscription form failed with CORS error

docs/topics/home.xml
* update: new link to online event 2020 -> 2021
* update: eliminate KMM
=> update: update home.xml

docs/topics/jvm/java-interop.md
java.lang.Annotation -> java.lang.annotation.Annotation
=> Fix the reference to java Annotation

package.json, yarn.lock
https://youtrack.jetbrains.com/issue/KTL-676
=> KTL-676 Global Navigation: add "Multiplatform for other platforms"

docs/cfg/buildprofiles.xml
https://youtrack.jetbrains.com/issue/KTL-679
https://branch-ktl-679-mpp-intro-redirect.kotlin-web-site.labs.jb.gg/docs/getting-started.html
=> KTL-679 Kotlinlang: Get started with Kotlin Multiplatform page is not indexed

docs/topics/idioms.md
I've added an idiom to get a value from a code block if another value is null
=> Add "Execute a code block if null" idiom

docs/topics/ksp/ksp-faq.md, docs/topics/ksp/ksp-overview.md
1. Updated links to slack workspace and KSP github issue page.
2. Updated list of libraries that support KSP
=> Update KSP docs

static/js/page/index/kotlin-why-section.scss, templates/inc/pages/index/why-section.html
https://youtrack.jetbrains.com/issue/KTL-693
=> KTL-693 Kotlinlang - remove horizontal scroll on mobile

docs/topics/multiplatform/multiplatform-build-native-binaries.md
=> fix: raising a note to a warning

docs/topics/multiplatform/multiplatform-dsl-reference.md, docs/topics/native/native-overview.md
=> fix: xcode required for kotlin native

docs/topics/multiplatform/multiplatform-add-dependencies.md
=> fix: adding library dependencies instructions

docs/topics/multiplatform-mobile/multiplatform-mobile-understand-project-structure.md
=> fix: how to switch to the project view

docs/topics/competitive-programming.md
=> fix: competitive programming options for earlier kotlin versions

docs/topics/data-science-overview.md
Updates the description of KMath. Also fixes the links to DL4J and ND4J.
=> Update the description of KMath

docs/topics/js/js-ir-migration.md
=> Soften wording on IR compiler migration guide re nullable Booleans

docs/topics/multiplatform/multiplatform-library.md
=> update: mutiplatform library publication

data/cities.yml, data/events.xml, data/user-groups.yml
Added following changes:
1. fixed Yemen geo tegs;
2. fixed Belfast KUG, Edinburgh KUG, from now on ones belong to United Kingdom;
3. Porto Alegre KUG transferred to South America section.
=> chore (user groups) April 2022, part 2

.eslintrc, .idea/misc.xml, .prettierignore, .prettierrc.json, package.json, yarn.lock
https://youtrack.jetbrains.com/issue/KTL-719
=> ktl-719 feat: add prettier

docs/topics/multiplatform/multiplatform-share-on-platforms.md
* [KT-51135](https://youtrack.jetbrains.com/issue/KT-51135/Add-examples-of-code-sharing)
=> update: what's next section

docs/topics/extensions.md
There is no explicit information whether extensions can be provided on interfaces. 
This makes it clearer to the new reader.
=> Update receiver type description.

blocks/community/community-banner/community-banner.tsx, blocks/community/layout/community-layout.tsx, pages/_app.jsx, pages/community/events/index.tsx, pages/community/index.tsx, pages/community/user-groups/index.tsx
https://youtrack.jetbrains.com/issue/KTL-755/Add-Google-Analytics-scripts
=> KTL-755 Add Google Analytics scripts

docs/topics/js/js-ir-compiler.md
Documents https://youtrack.jetbrains.com/issue/KT-51735/KJS-IR-Minimize-member-names-in-production-mode
=> Include paragraph on Minification of member names

docs/topics/scope-functions.md
"adam.age = 20" suggestion does not work here as `adam` is not defined yet in the `apply` block.
=> Removed incorrect "or adam.age = 20" suggestion

docs/topics/coding-conventions.md
KT-52583 https://youtrack.jetbrains.com/issue/KT-52583
=> update: update source file names conventions

docs/topics/gradle.md, docs/v.list
update minimal Gradle and Android Gradle plugin versions
add microformat markup
=> update: bump the minimal Gradle versions

docs/topics/enum-classes.md
* addressing comments in #3056
=> chore: enum classes description

package.json, yarn.lock
https://youtrack.jetbrains.com/issue/KTL-767/Mobile-nav-container-issue
=> KTL-767 Mobile nav container issue

data/last-news.yml
https://youtrack.jetbrains.com/issue/KTL-787/Update-Latest-from-Kotlin-section-on-kotlinlangorg
=> KTL-787 Update 'Latest from Kotlin' section on kotlinlang.org

data/last-news.yml
https://youtrack.jetbrains.com/issue/KTL-798/Update-news-on-kotlinlangorg
=> KTL-798 Update news on kotlinlang.org

.gitignore, .teamcity/README, .teamcity/pom.xml, .teamcity/settings.kts
Check #3053 to see how it looks like.
=> KTL-744 CI Test Configuration as Code

static/js/ktl-component/teach/components/subscription-form/index.js
https://youtrack.jetbrains.com/issue/KTL-801/Kotlinlang-fix-Teachs-subscription-form
=> KTL-801 Kotlinlang - fix Teach's subscription form

docs/topics/native/native-get-started.md
* KT-53213: made building instructions clearer
=> update: run instructions

docs/topics/multiplatform/multiplatform-discover-project.md
* KT-53245: replaced with an example of the actual structure
=> update: source sets code

docs/topics/data-science-overview.md
Suggest adding kotlin_in_datalore.png to https://github.com/JetBrains/kotlin-web-site/tree/master/docs/images/data-science
and using the commented-out <img/>
=> Kotlin in Datalore

.teamcity/builds/apiReferences/BuildApiReferencesProject.kt, .teamcity/builds/apiReferences/buildTypes/DokkaReferenceTemplate.kt, .teamcity/builds/apiReferences/buildTypes/KotlinxCoroutines.kt, .teamcity/builds/apiReferences/buildTypes/PrepareCustomDokkaTemplates.kt, dokka-templates/readme.md
https://youtrack.jetbrains.com/issue/KTL-695/kotlinlangorg-customize-Dokkas-Footer
=> KTL-695 kotlinlang.org: customize Dokka's templates (Part 1)

docs/topics/getting-started.md
add information about the installation of Kotlin
=> feature: update getting-started.md

src/search.py
https://youtrack.jetbrains.com/issue/KTL-810/Kotlinlang-fix-search-index-builder
=> KTL-810 Kotlinlang -fix search index builder

docs/cfg/buildprofiles.xml
https://youtrack.jetbrains.com/issue/KTL-578
=> KTL-578 Kotlinlang: update search params

src/search.py
https://youtrack.jetbrains.com/issue/KTL-817/Fix-search-builder-an-error-occurred-and-new-pages-are-skipped
=> KTL-817 Fix search builder: an error occurred during docs indexation

docs/topics/inline-classes.md
=> feat: generic inline classes

docs/topics/multiplatform/multiplatform-build-native-binaries.md
=> feat: customizing info.plst

docs/topics/multiplatform-mobile/multiplatform-mobile-getting-started.md
=> chore: update the Join the community section

docs/kr.tree, docs/topics/koans.md
=> chore: Koans description update and small fixes

docs/topics/object-declarations.md
https://youtrack.jetbrains.com/issue/KT-4107
=> Add section on data objects

docs/topics/lombok.md
=> Fix link to Lombok README

docs/topics/multiplatform-mobile/multiplatform-mobile-create-first-app.md
reverting -> reversing in the context of the `reversed()` function
=> Fixed spelling error in KMM First app

redirects/pages.yml, requirements.txt, src/search.py
* **fix**: Add redirect for [dropped](https://github.com/JetBrains/kotlin-web-site/pull/2913/files#diff-c81630bb0ada7c9f9a6c68dec3a6abb7dfc9d77f31e22b868663d3b95f8fdaba) urls
* **fix**: replace index instead append data
=> KTL-802: empty pages

pages/community/index.tsx
https://youtrack.jetbrains.com/issue/KTL-856/Update-the-link-on-the-Community-page
=> KTL-856 Update the link on the Community page

package.json, yarn.lock
https://youtrack.jetbrains.com/issue/KTL-773/Footer-fonts-styling-bug
=> KTL-773 Footer fonts styling bug

docs/kr.tree, docs/topics/whatsnew-eap.md
A pull request to add a What's new page for 1.8.0-Beta.
=> Add What's new page for 1.8.0-Beta

docs/topics/maven.md
=> Remove old stdlib artifacts for JDK 7 and 8

docs/topics/functions.md
Scala 3 supports Top level definition.
=> Update document about `Function scope`.

docs/topics/kotlin-ide.md
https://youtrack.jetbrains.com/issue/KT-54740
=> update: update info on Kotlin for Eclipse

docs/topics/functions.md
Add changes suggested in #3200
=> Update functions page

docs/topics/multiplatform-mobile/multiplatform-mobile-upgrade-app.md
Following along with this tutorial I was confused which file to edit and whether to add a new plugin section.
=> Corrected the build filename, improved clarity.

docs/topics/multiplatform-mobile/multiplatform-mobile-upgrade-app.md, docs/topics/multiplatform-mobile/multiplatform-mobile-wrap-up.md
https://youtrack.jetbrains.com/issue/KT-54946
=> fix: fix typos in Multiplatform Mobile onboarding

docs/topics/native/native-cocoapods-dsl-reference.md, docs/topics/native/native-cocoapods.md
* [KT-53340](https://youtrack.jetbrains.com/issue/KT-53340/Change-default-linking-type-for-frameworks-registered-by-cocoapods-plugin)
=> update: framework linking type

docs/topics/advent-of-code.md
[KT-55054](https://youtrack.jetbrains.com/issue/KT-55054) Add Advent of Code 2021 solutions to docs
=> feature: add all Advent of Code 2021 events

README.md
Clean up the README.md:
* Update some articles
* Add new sources to the table
* Fix some typos
=> update: clean up README.md

data/events.yml
Please add info about Cyprus KUG meetup to events
=> Add Cyprus KUG meetup to events

docs/topics/multiplatform-mobile/multiplatform-mobile-upgrade-app.md
I think it should be `GreetingView` instead of `Greeting`, otherwise it can not be compiled :-)
=> Fix typo on multiplatform-mobile-upgrade-app.md

.teamcity/builds/apiReferences/templates/PrepareDokkaTemplate.kt
https://youtrack.jetbrains.com/issue/KTL-933/Build-sometimes-fails-due-to-sharps-package-problem
I've run it several times, and no one failed.
=> KTL-933 Build sometimes fails due to sharp's package problem

docs/topics/js/js-project-setup.md
* add info on yarn.lock reporting
* fix indents
=> update: Kotlin/JS add info on yarn.lock reporting

templates/inc/pages/index/code-examples.html
A small change that aligns three comment lines like other code comments that are aligned.
=> Improve alignment of some comments in code examples

docs/topics/whatsnew18.md
Cosmetic change to align with the code style.
=> Add missing space in What's New Page

docs/topics/gradle/gradle-configure-project.md
=> fix: <MAJOR_JDK_VERSION> as Integer, not String

docs/kr.tree, docs/topics/kapt.md
add the new Compiler and plugins section
=> feature: rearrange items in the TOC

static/js/page/index/index.js, static/js/page/index/index.scss, static/js/page/index/kotlin-intro-section.scss, templates/inc/pages/index/code-examples.html, templates/inc/pages/index/kotlin-values.html, templates/inc/pages/index/latest-news.html, templates/inc/pages/index/why-section.html, templates/pages/index.html
https://youtrack.jetbrains.com/issue/KTL-963/Onboarding-Experiment-with-Kotlin-values-on-the-main-page
=> KTL-963 Onboarding: Experiment with Kotlin values on the main page

templates/inc/pages/index/intro.html
https://youtrack.jetbrains.com/issue/KTL-971/Remove-Kotlin-JS-from-the-main-menu-and-tiles-on-kotlinlang.org
=> KTL-971 Remove Kotlin/JS from the main menu and tiles on kotlinlang.org

docs/topics/control-flow.md
Add an if-else-if example to the [Conditions and loops](https://kotlinlang.org/docs/control-flow.html) page to resolve [KWHF-789.](https://youtrack.jetbrains.com/issue/KWHF-789)
=> Add if-else-if example to Conditions and loops page

docs/topics/scope-functions.md
Update based on suggestions in #2912.
=> Minor edits to scope functions

static/js/page/index/kotlin-intro-section.scss, templates/inc/pages/index/intro.html
https://youtrack.jetbrains.com/issue/KTL-1013/Update-the-tagline-on-the-main-page
=> KTL-1013 Update the tagline on the main page

docs/v.list
1.5.4 has compatibility issues with Kotlin 1.8
=> Use SQLDelight 1.5.5

static/js/page/index/index.scss, static/js/page/index/kotlin-code-examples-section.scss, templates/inc/pages/index/kotlin-values.html, templates/pages/index.html
https://youtrack.jetbrains.com/issue/KTL-1015/Onboarding-A-B-experiment-with-new-samples
=> KTL-1015 Onboarding: A/B experiment with new samples

data/user-groups.yml
update a bunch of KUG information
=> update: KUG list

docs/topics/gradle/gradle-configure-project.md
according to https://issuetracker.google.com/issues/260059413#comment10
=> update: fix comment about AGP

.teamcity/builds/kotlinlang/buidTypes/BuildReferenceDocs.kt, package.json, yarn.lock
https://youtrack.jetbrains.com/issue/KTL-1039/Update-Global-navigation-Multiplatform-updates
=> KTL-1039 Update Global navigation: Multiplatform updates

data/events.yml
SprintHacks is an 18 hour hackathon organized by the Developer Student Circuit with endless creativity. 
The focus is on innovation and creativity as participants work together to develop unique solutions using the latest technology.  With opportunities for networking and exciting prizes, this hackathon challenges participants to push their limits and create the next innovative product.
Venue: KIET Group Of Institutions, Ghaziabad
Website : https://sprinthacks.devfolio.co/
Organizers : https://dsckiet.com/
=> SprintHacks 2023

docs/topics/multiplatform-mobile/multiplatform-mobile-setup.md
...since users aren't actually using a "tool" here, but just their regular old CLI.
=> Clearer phrasing for multiplatform-mobile-setup.md

docs/topics/jvm/java-interop.md
[KT-56313](https://youtrack.jetbrains.com/issue/KT-56313) [Docs][Language] Preview of Java synthetic property references
=> Add Java synthetic property references

docs/snippets/multiplatform-mobile-tutorial/Entity.kt, docs/topics/multiplatform-mobile/multiplatform-mobile-ktor-sqldelight.md, docs/v.list
* [KT-56238](https://youtrack.jetbrains.com/issue/KT-56238)
=> update: following project update

docs/topics/wasm/wasm-get-started.md
[KT-57761](https://youtrack.jetbrains.com/issue/KT-57761)
=> chore: update information on Kotlin/Wasm

data/release-banner.yml, static/js/ktl-component/index.js, static/js/ktl-component/release-banner/index.jsx, static/js/ktl-component/release-banner/index.scss, templates/inc/pages/index/latest-news.html
https://youtrack.jetbrains.com/issue/KTL-1027/Kotlinlang-make-HTML-release-banner
=> KTL-1027 Kotlinlang - make HTML release banner

README.md, docs/kr.tree
Probably, this PR should be used instead of #3525
Done by example from #3374
=> feature: add api-guidelines docs

docs/topics/js/js-react.md
* [KT-55857](https://youtrack.jetbrains.com/issue/KT-55857)
=> update: kotlin version and file name

docs/topics/multiplatform/multiplatform-full-stack-app.md
Hi, I just went through the Kotlin multiplatform guide to create a full stack web app (it was very helpful!) and noticed some slight formatting tweaks
=> Multiplatform fullstack webapp guide tweaks

templates/inc/head.html, templates/pages/index.html
https://youtrack.jetbrains.com/issue/KTL-1036/The-meta-description-on-kotlinlang.org-is-missing.-Please-add
=> KTL-1036 The meta description on kotlinlang.org is missing. Please add

data/user-groups.yml
=> update: Added Vilnius Kotlin User Group.

.teamcity/builds/apiReferences/BuildApiReferencesProject.kt, .teamcity/builds/apiReferences/stdlib/BuildStdlibApiReference.kt, .teamcity/builds/apiReferences/stdlib/StdlibPrepareDokkaTemplates.kt, .teamcity/builds/kotlinlang/buidTypes/BuildReferenceDocs.kt
https://youtrack.jetbrains.com/issue/KTL-1093/Stdlib-documentation-beta-version-update-build-configuration
=> KTL-1093 Stdlib documentation: beta version - update build configuration

data/user-groups.yml
=> Add Tbilisi KUG

README.md, docs/topics/android-overview.md, docs/topics/cross-platform-frameworks.md, docs/topics/cross-platform-mobile-development.md, docs/topics/getting-started.md, docs/topics/multiplatform-mobile/multiplatform-mobile-getting-started.md, docs/topics/multiplatform-mobile/multiplatform-mobile-introduce-your-team.md, docs/topics/multiplatform-mobile/multiplatform-mobile-upgrade-app.md, docs/topics/native-and-cross-platform.md, docs/topics/native/native-overview.md, templates/inc/pages/index/intro.html, templates/inc/pages/index/why-section.html
https://youtrack.jetbrains.com/issue/KTL-1074/Change-lp-mobile-url-to-multiplatform
=> KTL-1074 Change /lp/mobile url to multiplatform

data/user-groups.yml
=> Add Zhengzhou KUG

docs/topics/gradle/gradle-configure-project.md
[KT-58565](https://youtrack.jetbrains.com/issue/KT-58565) Write a notice in Kotlin docs that java files shouldn't be in src/main/kotlin
=> chore: add a note about Kotlin and Java source files

docs/topics/multiplatform-mobile/multiplatform-mobile-plugin-releases.md
Prepare release notes for KMM AS plugin 0.6.0
=> KMM AS plugin 0.6.0

docs/topics/eap.md, docs/topics/whatsnew-eap.md, docs/v.list
This PR adds details about the 1.9.0-RC EAP release.
=> feat: 1.9.0-RC release

docs/topics/coding-conventions.md, docs/topics/idioms.md, docs/topics/jvm/java-to-kotlin-collections-guide.md, docs/topics/keyword-reference.md, docs/topics/ranges.md
This PR updates our Ranges page with the `..<` operator. It also adds this operator the list of keywords and operators.
=> feat: add rangeUntil operator

data/universities.yml
Updated Avans University in Breda geo
=> Update a university location.yml

data/releases.yml, docs/topics/compiler-reference.md, docs/topics/faq.md, docs/topics/maven.md, docs/v.list
Update release and library versions in preparation for release 1.9.0.
=> Update versions for 1.9.0

docs/topics/object-declarations.md
Remove the Experimental warning for data objects as they become Stable in 1.9.0.
=> Update data objects status

.teamcity/BuildParams.kt, .teamcity/builds/apiReferences/BuildApiReferencesProject.kt, .teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmBuildApiReference.kt, .teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmBuildSearchIndex.kt, .teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmPrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/vcsRoots/Kotlin.kt
https://youtrack.jetbrains.com/issue/KTL-1139/Set-up-publishing-of-kotlinx-metadata-jvm-documentation-on-kotlinlang.org
=> KTL-1139 Set up publishing of kotlinx-metadata-jvm documentation on kotlinlang.org

docs/topics/jvm/jvm-create-project-with-spring-boot.md
Wrongly removed by me in #3643
=> fix: use the star sign for spread operator

docs/topics/scope-functions.md
It's as same as [the previous PR](https://github.com/JetBrains/kotlin-web-site/pull/3602).
=> docs: fix grammar

data/user-groups.yml
Remove Hefei KUG from the list
=> Remove Hefei KUG

docs/topics/constructing-collections.md
Just a couple typo / grammatical fixes, thanks
=> chore: fix typos in constructing-collections

docs/topics/basic-syntax.md
To help with onboarding data collection and analysis, this PR adds IDs to runnable sample on the Basic syntax page.
=> Update Basic syntax page with runnable sample IDs

static/js/page/dokka-template/control-pane.scss
=> ktl-1147: filter in sub header has more height than common

docs/topics/strings.md
=> Add link to String class in Strings page

docs/topics/data-classes.md, docs/topics/extensions.md
This PR is to make changes to fix issues highlighted in PRs: #3403 and #3404
=> Small updates to Extensions and Data classes pages

docs/topics/getting-started.md, docs/topics/tour/kotlin-tour-collections.md
To make the Collections chapter of the Kotlin tour more beginner-friendly, more explanation has been given for the key characteristics of lists, sets, and maps.
In addition, the examples given in the Maps section have been updated to make them more relatable to the real world.
=> Update Kotlin tour: Collections

docs/topics/data-classes.md
This PR revises the introduction to Data classes to make it clear that data classes are a type of class that comes with additional member functions.  Other formatting issues have also been tidied up.
=> Revise introduction to Data classes

static/js/page/dokka-template/layout.scss
=> KTL-1175 The new dokka header doesn't fit different screen resolutions

docs/topics/gradle/gradle-compiler-options.md, docs/v.list
This PR updates the table for possible API and language versions for the Gradle compiler options.
=> Update Gradle compiler option API and language versions

package.json, yarn.lock
https://youtrack.jetbrains.com/issue/KTL-1110/Hands-on-remove-from-navigation-and-add-redirect-to-documentaion
=> KTL-1110 Hands-on: remove from navigation and add redirect to documentaion

.teamcity/builds/kotlinlang/buidTypes/BuildReferenceDocs.kt
https://youtrack.jetbrains.com/issue/KTL-1110/Hands-on-remove-from-navigation-and-add-redirect-to-documentaion
=> ktl-1110 Update webhelp to 5.15.0

docs/topics/multiplatform-mobile/multiplatform-mobile-understand-project-structure.md, docs/topics/multiplatform/multiplatform-configure-compilations.md, docs/topics/multiplatform/multiplatform-discover-project.md, docs/topics/multiplatform/multiplatform-dsl-reference.md, docs/topics/multiplatform/multiplatform-hierarchy.md
* [KT-60216](https://youtrack.jetbrains.com/issue/KT-60216)
* [KT-57863](https://youtrack.jetbrains.com/issue/KT-57863)
* [KT-57019](https://youtrack.jetbrains.com/issue/KT-57019)
* [KT-57881](https://youtrack.jetbrains.com/issue/KT-57881)
* [KT-56801](https://youtrack.jetbrains.com/issue/KT-56801)
=> fix: code samples

docs/topics/multiplatform-mobile/multiplatform-mobile-samples.md
Update Realm link to point to Realm Kotlin SDK documentation
=> Update Realm link to point to Realm Kotlin SDK documentation

docs/topics/gradle/gradle-compilation-and-caches.md, docs/topics/gradle/gradle-compiler-options.md, docs/topics/gradle/gradle-configure-project.md, docs/topics/gradle/gradle-plugin-variants.md
=> Fix Gradle getting started links

docs/topics/lambdas.md, docs/topics/whatsnew13.md
- https://kotlinlang.org/docs/lambdas.html#higher-order-functions
- https://en.wikipedia.org/wiki/Higher-order_function
=> Fix term typo: higher-order

blocks/main/info-block/info-block.tsx, blocks/main/kotlin-usage-highlights/kotlin-usage-highlights.tsx
https://youtrack.jetbrains.com/issue/KTL-1135/Main-page-revamp-dynamic-headers
=> KTL-1135 Main page revamp: dynamic headers

docs/topics/native/native-improving-compilation-time.md
* [KT-61242](https://youtrack.jetbrains.com/issue/KT-61242)
=> feat: klib incremental compilation

docs/topics/gradle/gradle-compilation-and-caches.md
* [KT-54362](https://youtrack.jetbrains.com/issue/KT-54362)
=> feat: full support for gradle configuration cache in kmp

docs/topics/multiplatform/multiplatform-share-on-platforms.md
* [KT-58712](https://youtrack.jetbrains.com/issue/KT-58712)
=> feat: connect third-party libs

docs/topics/components-stability.md, docs/topics/multiplatform/multiplatform-expect-actual.md
* [KT-58875](https://youtrack.jetbrains.com/issue/KT-58875/MPP-Stable-release-state-of-components-compatibility-with-other-tools)
=> update: state of kotlin components

docs/topics/native/native-c-interop.md
*  [KT-55578](https://youtrack.jetbrains.com/issue/KT-55578/Custom-user-message-for-linker-error)
=> feat: custom message for linker errors

docs/topics/native/native-binary-licenses.md, docs/topics/native/native-ios-integration.md, docs/topics/native/native-memory-manager.md, docs/topics/whatsnew-eap.md, docs/topics/whatsnew19.md, docs/topics/whatsnew1920.md
* [KT-55364](https://youtrack.jetbrains.com/issue/KT-55364)
* [KT-57771](https://youtrack.jetbrains.com/issue/KT-57771)
* [KT-57772](https://youtrack.jetbrains.com/issue/KT-57772)
* [KT-57773](https://youtrack.jetbrains.com/issue/KT-57773)
* [KT-58851](https://youtrack.jetbrains.com/issue/KT-58851)
=> feat: k/n memory manager updates

docs/topics/multiplatform/multiplatform-hierarchy.md, docs/topics/multiplatform/multiplatform-share-on-platforms.md, docs/topics/whatsnew14.md, docs/topics/whatsnew1530.md, docs/topics/whatsnew1820.md
See https://youtrack.jetbrains.com/issue/KT-60843/Finalize-public-communication-about-hierarchy-templates
=> Update article about Source Set Hierarchies for 1.9.20

docs/topics/kotlin-pdf.md
Add PDF documentation for 1.9.20
=> Add 1.9.20 PDF

docs/topics/advent-of-code.md
https://youtrack.jetbrains.com/issue/KT-61314/Update-Advent-of-Code-page-with-videos-from-2022
=> update: add advent of code events for 2022

docs/topics/native/native-cocoapods.md
Details: https://jetbrains.slack.com/archives/C01BSJ8PDNC/p1698148791352229?thread_ts=1697101031.591259&cid=C01BSJ8PDNC
=> Fix: remove sample from "native-cocoapods" article

data/user-groups.yml
=> add Hangzhou KUG

data/user-groups.yml
=> chore: add user group [Kotlin User Group Tokyo]

docs/topics/multiplatform/multiplatform-compatibility-guide.md, docs/topics/multiplatform/multiplatform-hierarchy.md
=> update: feedback

docs/topics/strings.md
Added String.format() description and fixed code comments.
=> update: add string format

static/js/ktl-component/why-teach/quotes.json
https://youtrack.jetbrains.com/issue/KTL-1217/Swap-educator-quotes-on-Why-teach-page
=> KTL-1217 Swap educator quotes on 'Why teach' page

data/user-groups.yml
=> add Hefei KUG

docs/topics/data-classes.md, docs/topics/inline-classes.md
This PR updates the introductory sentence to inline value classes so that it is easier to understand. It also includes some small changes to data classes.
=> Small update to inline classes

docs/topics/serialization.md
Adding additional links to Serialization to increase findability of information (and some additional clean up).
=> Adding additional links to Serialization

docs/topics/advent-of-code.md
https://youtrack.jetbrains.com/issue/KTL-1272/Add-a-link-to-Advent-of-Code-page
demo: https://branch-nikpachoo-patch-1.kotlin-web-site.labs.jb.gg/docs/advent-of-code.html
=> KTL-1272 Add a link to Advent of Code page

blocks/main/why-kotlin/why-kotlin.tsx, components/code-block/code-block.tsx
https://youtrack.jetbrains.com/issue/KTL-1251/Degradation-Why-Kotlin-section-on-mobile-version
=> KTL-1251 Degradation "Why Kotlin" section on mobile version

package.json, static/js/page/dokka-template/footer/index.jsx, yarn.lock
https://youtrack.jetbrains.com/issue/KTL-1314/Dokka-layout-rollback-Footer
https://staging.kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/
https://staging.kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/
=> KTL-1314 Dokka layout: rollback Footer

docs/topics/booleans.md, docs/topics/characters.md, docs/topics/strings.md, docs/topics/unsigned-integer-types.md
minor updates to boolean and char docs about their respective sizes in JVM and binary incompatibility of changing type from unsigned to its signed counterpart
=> update to boolean and character sizes in memory and about mangling

docs/topics/data-classes.md
updating docs to clarify default behavior of data class methods with class body properties
=> KT-64374 rewriting section to increase clarity

docs/topics/components-stability.md
[KT-64043](https://youtrack.jetbrains.com/issue/KT-64043) Refine description for Alpha Stability Level
=> chore: update Alpha stability level description

docs/topics/basic-syntax.md
=> chore: add a link to lambda expressions

docs/topics/command-line.md
small update in manual install for windows users
=> small update in manual install for windows users

docs/topics/native/native-improving-compilation-time.md, docs/topics/native/native-libraries.md, docs/topics/whatsnew1920.md
[KT-64482](https://youtrack.jetbrains.com/issue/KT-64482) Replace KONAN_DATA_DIR to konan.data.dir or -Xkonan-data-dir
=> update: use Gradle property instead of env var for konan

docs/kr.tree, docs/topics/eap.md, docs/topics/whatsnew-eap.md, docs/v.list
Updated whatsnew-eap.md and eap.md as required by Beta 2.0.0-3 release.
=> Feat: adding what's new Beta 2.0.0-3

docs/topics/maven.md
[KT-54307](https://youtrack.jetbrains.com/issue/KT-54307) 'Maven' page doesn't say how to add Kotlin Plugin to the pom.xml
=> chore: update maven.md

docs/topics/coding-conventions.md
This PR updates the information we share about Android runtime support.
=> Update coding conventions for test method names

docs/topics/js/js-project-setup.md
updating how to set the outputDirectory property
=> updating how to set the outputDirectory property

blocks/main/why-kotlin/why-kotlin.tsx
https://github.com/JetBrains/kotlin-web-site/assets/242514/62e89625-d2e0-4c8f-acbf-aa46d56652d8
=> fix(ktl-1346): set targetPlatform for junit

docs/topics/whatsnew-eap.md
Add 2.0.0-Beta5 as another release to come.
=> Update what's new EAP

docs/kr.tree, docs/topics/eap.md, docs/topics/whatsnew-eap.md, docs/v.list
This PR adds the what's new for 2.0.0-Beta4.
=> Add what's new for 2.0.0-Beta4

docs/topics/data-science-overview.md
https://youtrack.jetbrains.com/issue/KTL-1381/Invalid-link-to-a-library-API
=> KTL-1381 Invalid link to a library API

docs/topics/home.xml
This PR updates topics on the Docs home page.
=> Update Docs home page topics

docs/topics/equality.md, docs/topics/js/js-interop.md
Update equality page. Incorporated external feedback and other minor changes.
=> update: equality page

docs/topics/jvm/jvm-spring-boot-add-db-support.md
Trying to address the issue #4045
=> chore: make note about Spring Boot import more visibly

docs/topics/wasm/wasm-get-started.md
Fixing Gradle command in Get started tutorial
=> chore: fixing Gradle command

docs/topics/whatsnew-eap.md
This PR adds a section to the What's new in Kotlin 2.0.0-Beta4 that describes the Kotlin Multiplatform improvements provided in the K2 compiler .
=> Add Kotlin Multiplatform to K2 section in What's new in Kotlin 2.0.0-Beta4

docs/topics/idioms.md, docs/v.list
This PR finishes what PR #4049 started.
=> Add idiom for inline value classes

docs/v.list
Update the maximum AGP version for 1.9.20-1.9.23.
=> Update max AGP variable

docs/topics/control-flow.md
https://kotlinlang.org/docs/control-flow.html#for-loops
=> chore: make a sentence with a nested list clearer (control-flow.md)

docs/topics/cross-platform-mobile-development.md
Added a sentence with embedded link to multiplatform-introduce-your-team.md. Removed unnecessary comma at the end of a note. Please take a look.
=> chore: add sentence with a link, remove unnecessary comma

data/universities.yml
https://youtrack.jetbrains.com/issue/KTL-138
=> KTL-138 Remove broken links

docs/topics/jvm/comparison-to-java.md
- Java: instead of unnamed variables and record patterns, link to the Java Pattern Matching design document
- Java: package-private visibility
- Kotlin: explicit API mode & Opt-In requirements
=> Update comparison to Java

docs/topics/test-page.md
to ensure proper testing by screenshots
=> fix(ktl-1335): removed kotlin variable from test-page

webpack.config.js
Lately there was problem with js assets builds
This is an attempt to fix it
Could be related to https://github.com/JetBrains/kotlin-web-site/pull/4122
=> fix building js assets

requirements.txt
Reverts JetBrains/kotlin-web-site#4135
=> Revert "fix: removed dependency which does not work with current python version"

docs/topics/ksp/ksp-quickstart.md
The current docs only show how to create your own processor, which is fairly rare. A much more common question is how to add an existing processor and how to apply the KSP plugin.
=> Add examples of how to add an existing KSP processor

CODEOWNERS
Technical Writers now are responsible for redirects
=> update: update CODEOWNERS

docs/kr.tree, docs/topics/k2-compiler-migration-guide.md
This PR contains minor fixes for the K2 compiler migration guide.
=> Update K2 compiler migration guide

docs/topics/native/native-objc-interop.md
Just fixing the typo of the document.
=> Update native-objc-interop.md typo

data/releases.yml, docs/topics/gradle/gradle-configure-project.md, docs/topics/k2-compiler-migration-guide.md, docs/topics/releases.md, docs/v.list
This PR is for the Kotlin 1.9.24 release.
=> Kotlin 1.9.24 release

docs/topics/getting-started.md
This PR updates our Get started page so that the section about creating a powerful app is changed to be about choosing a Kotlin use case. This is a more relevant header now that we have data analysis as a use case.
=> Update get started page powerful app section

docs/topics/typecasts.md
This PR updates smart cast documentation for Kotlin 2.0.0.
=> Update smart cast documentation for Kotlin 2.0.0

docs/topics/kotlin-pdf.md, pdf/_book-cover.html
This PR adds the PDF for Kotlin 2.0.0.
=> Add PDF for Kotlin 2.0.0

docs/topics/k2-compiler-migration-guide.md, docs/topics/whatsnew20.md
=> Fix typo in increment/decrement operator examples

data/user-groups.yml
user group details -
KUG New Delhi
India, Asia
Community page : https://www.commudle.com/communities/kug-new-delhi
=> Added KUG New Delhi to user group data

docs/topics/whatsnew20.md
=> fix: update whatsnew20.md

.teamcity/BuildParams.kt, .teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmBuildApiReference.kt, .teamcity/builds/apiReferences/vcsRoots/KotlinMetadataJvm.kt
https://youtrack.jetbrains.com/issue/KTL-1399/Align-kotlin-metadata-jvm-documentation-releases-with-Kotlin-releases
=> KTL-1399 Align kotlin-metadata-jvm documentation releases with Kotlin releases

docs/topics/k2-compiler-migration-guide.md
This PR adds a new change related to expected/actual classes to the K2 compiler migration guide.
=> Add expected actual classes change to K2 compiler migration guide

docs/topics/multiplatform/multiplatform.md
https://youtrack.jetbrains.com/issue/KT-68914
=> fix: fix the outdated link

docs/topics/k2-compiler-migration-guide.md
This PR adds information about performance improvements to the K2 compiler migration guide.
=> Add performance improvements section to K2 migration guide

docs/topics/native/native-get-started.md
* [KT-57862](https://youtrack.jetbrains.com/issue/KT-57862/Note-about-macOS-and-MPP-setup-in-K-N)
=> feat: macos development note in kotlin/native

docs/topics/multiplatform/multiplatform-dsl-reference.md
- [KT-67308](https://youtrack.jetbrains.com/issue/KT-67308)
=> feat: wasm tagrets in multiplatform dsl

docs/topics/native/native-command-line-compiler.md
* [KT-68317](https://youtrack.jetbrains.com/issue/KT-68317/)
* [KT-49691](https://youtrack.jetbrains.com/issue/KT-49691/)
=> update: java version note

docs/topics/multiplatform/multiplatform-compatibility-guide.md
- [KT-68926](https://youtrack.jetbrains.com/issue/KT-68926/Docs-Incorrect-framework-version-during-Kotlin-upgrade-downgrade)
=> feat: new compatibility issue

docs/topics/multiplatform/multiplatform-ios-dependencies.md, docs/topics/native/native-cocoapods-libraries.md, docs/topics/native/native-cocoapods-xcode.md, docs/topics/native/native-cocoapods.md
* [KT-58694](https://youtrack.jetbrains.com/issue/KT-58694)
* [KT-61264](https://youtrack.jetbrains.com/issue/KT-61264)
=> update: cocoapods instructions improvements

docs/topics/whatsnew-eap.md
This PR fixes a small formatting problem in whatsnew-eap.md.
=> Small fix for whatsnew-eap.md

docs/topics/tour/kotlin-tour-basic-types.md
Keep Long Value Consistent in Exercise & Solution
=> Keep Long Value Consistent in Exercise & Solution

docs/images/k2-compiler-architecture.svg
…and path fix for pdf rendering
=> fix(pdf): update k2-compiler-architecture image with linear gradient

docs/topics/ksp/ksp-faq.md
This PR updates the KSP requirements for Android Gradle plugin and Gradle.
=> Update KSP library requirements in FAQ

docs/topics/multiplatform/multiplatform-dsl-reference.md, docs/topics/multiplatform/multiplatform-ios-dependencies.md, docs/topics/native/native-cocoapods-dsl-reference.md, docs/topics/native/native-cocoapods-libraries.md, docs/topics/native/native-cocoapods-xcode.md
This PR fixes [KT-69612](https://youtrack.jetbrains.com/issue/KT-69612), outdated shortcuts for iOS targets
=> fix: outdated shortcuts

docs/topics/tour/kotlin-tour-basic-types.md, docs/topics/tour/kotlin-tour-classes.md, docs/topics/tour/kotlin-tour-collections.md, docs/topics/tour/kotlin-tour-control-flow.md, docs/topics/tour/kotlin-tour-functions.md, docs/topics/tour/kotlin-tour-hello-world.md, docs/topics/tour/kotlin-tour-null-safety.md, docs/topics/tour/kotlin-tour-welcome.md
This PR adds improvements to the Kotlin tour based on external feedback and review by @serras.
=> Improve Kotlin tour

docs/cfg/buildprofiles.xml
https://youtrack.jetbrains.com/issue/KTL-1610
=> KTL-1610 Hide test page

.teamcity/BuildParams.kt
https://youtrack.jetbrains.com/issue/KTL-1399/Align-kotlin-metadata-jvm-documentation-releases-with-Kotlin-releases
=> Update MetadataJvm Api Reference version

.teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmBuildApiReference.kt
https://youtrack.jetbrains.com/issue/KTL-1399/Align-kotlin-metadata-jvm-documentation-releases-with-Kotlin-releases
=> ktl-1399 Fix metadata reference build

.teamcity/builds/kotlinlang/buidTypes/FetchBlogNews.kt
https://youtrack.jetbrains.com/issue/KTL-1614/News-on-the-main-page-didnt-sync-with-the-latest-blog-state
=> Add notifications about failed loading of news

docs/topics/native/native-memory-manager.md
This PR updates the documentation on the signposts feature, following [KT-68928](https://youtrack.jetbrains.com/issue/KT-68928)
=> feat: changes to monitoring GC performance

docs/topics/whatsnew-eap.md
This PR updates the text in what's new for Kotlin 2.0.20-RC2 for the KGMP + Gradle Java plugins deprecation warning.
Approved by Yahor Berdnikau and Adam Semenenko.
=> Update what's new for Kotlin 2.0.20-RC2 KGMP + Gradle Java plugins deprecation warning

docs/topics/native/native-memory-manager.md
This PR creates a new section that combines GC pause time optimization options, including the new [KT-58865](https://youtrack.jetbrains.com/issue/KT-58865/Native-implement-concurrent-mark-in-GC)
=> feat: concurrent marking in GC

docs/topics/js/js-to-kotlin-interop.md
This PR updates the Kotlin/JS documentation, following
* [KT-67273](https://youtrack.jetbrains.com/issue/KT-67273)
* [KT-18891](https://youtrack.jetbrains.com/issue/KT-18891)
=> feat: new Kotlin/JS features

data/releases.yml, docs/kr.tree, docs/topics/eap.md, docs/topics/home.xml, docs/topics/releases.md, docs/topics/whatsnew2020.md, docs/v.list
This PR adds the final what's new for 2.0.20 and other details needed for the release.
=> Add what's new for Kotlin 2.0.20

data/events.yml
Update titles for the two upcoming events of Kotlin Vienna
=> Update Vienna 2024 Event Titles

data/releases.yml, docs/kr.tree, docs/topics/compiler-reference.md, docs/topics/eap.md, docs/topics/gradle/gradle-compilation-and-caches.md, docs/topics/gradle/gradle-configure-project.md, docs/topics/home.xml, docs/topics/js/js-ir-compiler.md, docs/topics/js/js-to-kotlin-interop.md, docs/topics/multiplatform/multiplatform-android-dependencies.md, docs/topics/multiplatform/multiplatform-compatibility-guide.md, docs/topics/multiplatform/multiplatform-hierarchy.md, docs/topics/multiplatform/multiplatform-native-artifacts.md, docs/topics/native/native-cocoapods.md, docs/topics/native/native-faq.md, docs/topics/native/native-ios-integration.md, docs/topics/native/native-memory-manager.md, docs/topics/releases.md, docs/topics/wasm/wasm-troubleshooting.md, docs/topics/whatsnew-eap.md, docs/topics/whatsnew1420.md, docs/topics/whatsnew20.md, docs/topics/whatsnew2020.md, docs/v.list
This PR adds the new documentation for Kotlin 2.0.20.
=> Update Kotlin 2.0.20 documentation

docs/topics/kotlin-pdf.md, pdf/_book-cover.html
This PR updates the PDF for Kotlin 2.0.20
=> Add PDF for 2.0.20

docs/topics/js/javascript-dce.md
This PR includes a fix to the first mention of "dead code elimination (DCE)"
=> minor: fix dead code elimination (DCE) mention

data/events.yml
Added KoHacks by KUG Chennai to events.yml
Event link: https://lu.ma/rbofnzaf
Event Date: Sept 21
=> Added KoHacks by KUG Chennai to events.yml

blocks/main/hero/hero.module.css, blocks/main/hero/hero.tsx, blocks/main/latest-news/index.tsx, blocks/main/why-kotlin/why-kotlin.tsx
For B variant assign `[data-optimizely-id='hero-ab']` attribute to hero section
=> Ktl 1544 main hero ab

docs/topics/native/native-migration-guide.md, docs/topics/native/native-target-support.md
This PR adds a note about legacy memory model ([KT-69552](https://youtrack.jetbrains.com/issue/KT-69552)) and adjusts the description of the Windows target ([KT-60402](https://youtrack.jetbrains.com/issue/KT-60402))
=> update: MM note and target description

docs/topics/native/native-objc-interop.md
* [KT-67589](https://youtrack.jetbrains.com/issue/KT-67589): This PR adds a section on Obj-C symbols always requiring strong linking
=> feat: strong linking description

data/events.yml, data/user-groups.yml
BordeauxKt was created in 2019 by multiple colleagues of mine. However, due to COVID, the first meetup had to be cancelled.
I'm currently in the process of bringing it back to life! Our first meetup will take place on October 22nd, and will be about Compose Multiplatform.
=> Adds the Bordeaux KUG

docs/topics/getting-started.md
This PR separates the first tab in Get started to "console" and "backend" tabs.
Approved by Anton Arhipov.
=> Update Get started page server-side tabs

docs/topics/data-classes.md, docs/topics/gradle/gradle-configure-project.md, docs/topics/tour/kotlin-tour-classes.md, docs/topics/tour/kotlin-tour-control-flow.md, docs/topics/whatsnew2020.md
This PR makes some changes to the Tour to:
* Correct syntax for data class member functions to not have a `.`
* Add link to API reference
=> Tour improvements

scripts/doindex/lib/parser.mjs, scripts/doindex/parsers/writerside.mjs
https://youtrack.jetbrains.com/issue/KTL-1490/Use-WriterSide-for-the-documentation
=> KTL-1490 Use WriterSide for the documentation

.teamcity/BuildParams.kt, .teamcity/builds/apiReferences/kotlinx/io/KotlinxIOBuildApiReference.kt, .teamcity/builds/apiReferences/vcsRoots/KotlinxIO.kt
=> chore(ci): use release tag for kotlinx-io

docs/v.list
=> chore: bump KSP and libs versions

blocks/main/hero/hero.module.css, blocks/main/hero/hero.tsx
Do not merge before optimizely experiment is finished
=> ktl-1686 feat: make b variant default

docs/topics/tour/kotlin-tour-control-flow.md
Conditional expressions and ranges practice, is only about conditional expressions, so it is better placed nearer to Conditional expressions.
Also, ranges is more suitable to be practiced with loops, so it would make more sense to group it with it, or to have its own practice section.
=> Move conditional expressions and ranges practice section

data/universities.yml
Reverts JetBrains/kotlin-web-site#4503 it breaks the build
=> Revert "Update universities.yml"

docs/topics/gradle/gradle-compiler-options.md, docs/topics/gradle/gradle-configure-project.md, docs/topics/maven.md, docs/topics/multiplatform/multiplatform-dsl-reference.md, docs/v.list
This PR updates the documentation with supported versions for 2.1.0.
=> Update build tool versions for 2.1.0

docs/topics/control-flow.md
This PR fixes [KT-72236](https://youtrack.jetbrains.com/issue/KT-72236/Web-feedback-from-Conditions-and-loops-https-kotlinlang.org-docs-control-flow.html).
=> update: when content about if-else-if

docs/topics/multiplatform/multiplatform-build-native-binaries.md, docs/topics/multiplatform/native-cocoapods.md
This PR fixes an issue [KT-72512](https://youtrack.jetbrains.com/issue/KT-72512/CocoaPods-overview-and-setup-module-not-found) when users immediately ran into red code when creating a project, plus adds minor changes to the XCFrameworks task list
=> update: minor code changes

docs/topics/js/js-project-setup.md
Changes related to this development issue: https://youtrack.jetbrains.com/issue/KT-69628/K-Wasm-Node.js-version-per-project
=> feature: Node.js settings per subproject

docs/kr.tree, docs/topics/eap.md, docs/topics/whatsnew-eap.md, docs/v.list
This PR adds 2.1.0-RC2 release details: update eap.md, kr.tee, what's new, and v.list
=> feat: 2.1.0-RC2 release details

docs/topics/wasm/wasm-js-interop.md
This PR is approved by @igoriakovlev
=> update: Wasm web APIs library

docs/topics/kotlin-brand-assets.md
https://youtrack.jetbrains.com/issue/KTL-1748/Add-a-link-to-the-KF-brand-guidelines-on-kotlinlang.org
=> KTL-1748 Update kotlin-brand-assets.md

.teamcity/BuildParams.kt, .teamcity/builds/apiReferences/BuildApiReferencesProject.kt, .teamcity/builds/apiReferences/kgp/KotlinGradlePluginBuildApiReference.kt, .teamcity/builds/apiReferences/kgp/KotlinGradlePluginBuildSearchIndex.kt, .teamcity/builds/apiReferences/kgp/KotlinGradlePluginPrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/kotlinx/coroutines/KotlinxCoroutinesBuildSearchIndex.kt, .teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmBuildApiReference.kt, .teamcity/builds/apiReferences/vcsRoots/Kotlin.kt, .teamcity/builds/apiReferences/vcsRoots/KotlinKGP.kt, .teamcity/settings.kts
https://youtrack.jetbrains.com/issue/KTL-947/Publish-API-Reference-for-Kotlin-Gradle-Plugin
=> KTL-947 Publish API Reference for Kotlin Gradle Plugin

docs/topics/compose-compiler-options.md
Bringing over labels that were added here: https://github.com/JetBrains/kotlin-web-site/pull/4546
=> chore: removed the Experimental warnings in favor of the labels

docs/topics/android-overview.md, docs/topics/native/native-overview.md
This PR updates references to text that will change on the KMP portal as part of https://github.com/JetBrains/kotlin-multiplatform-dev-docs/pull/281
=> Update KMP tutorial link texts

docs/v.list
This PR is to update the Dokka version to 2.0.0.
=> Update Dokka version to 2.0.0

docs/topics/advent-of-code.md
https://youtrack.jetbrains.com/issue/KTL-1768/Add-a-link-to-Advent-of-Code-page
=> Add Advent of Code '24 playlist

docs/topics/eap.md
Updating the EAP release details for Kotlin 2.1.10-RC
=> update: Kotlin 2.1.10-RC eap release details

blocks/main/hero/hero.module.css
=> feat: protect hero banner from overflow

docs/topics/gradle/gradle-best-practices.md
This PR makes a one-line change to the Gradle best practices page.
=> Add  a minor fix in Gradle best practices

kotlin-website.py, requirements.txt, src/api.py, src/externals.py
Yet another issue in PyYAML: https://github.com/yaml/pyyaml/issues/724
I think it's enough with old yaml parser
=> chore; update python deps

data/releases.yml, docs/topics/eap.md, docs/topics/releases.md, docs/v.list
This PR adds 2.1.10 release details: update eap.md, releases.md, releases.yml, and v.list
=> feat: 2.1.10 release details

pages/404.tsx, pages/index.tsx, templates/pages/index.html
https://youtrack.jetbrains.com/issue/KTL-2048/Update-meta-description-for-kotlinlang
=> KTL-2048 Update meta description for kotlinlang

blocks/main/hero/hero.module.css, data/hero-banner.yml
https://youtrack.jetbrains.com/issue/KTL-2046/Complete-the-AB-experiment-with-Hero-Banner
=> KTL-2046 Complete the AB experiment with Hero Banner

docs/topics/command-line.md, docs/topics/faq.md, docs/topics/kotlin-ide.md, docs/topics/multiplatform/multiplatform.topic, docs/topics/wasm/wasm-debugging.md
This PR removes mentions of Fleet from the documentation.
=> Remove Fleet mentions

docs/topics/kotlin-language-features-and-proposals.md, docs/topics/roadmap.md
Update the language features and proposals as well
=> feat: update Kotlin roadmap Feb 2025

docs/topics/roadmap.md
After double-checking with Sergei Bogolepov, it makes sense to keep the ticket in progress. Let's keep it as ongoing for a while
=> Moved KT-71279 back to in progress section

docs/topics/getting-started.md
This PR fixes the CMP tutorial link on Get started.
=> Minor fix for CMP tutorial link

docs/topics/faq.md, docs/topics/server-overview.md
This PR adds additional mentions of Ktor to the server-side overview and the FAQ.
Approved by Alyona Chernyaeva.
=> Add more links to Ktor

.teamcity/BuildParams.kt
=> Update kotlinx-io version

docs/topics/kotlin-language-features-and-proposals.md
Updating KT-54617 from in preview to stable
=> update: moving KT-54617 from in preview to stable

docs/kr.tree, docs/topics/eap.md, docs/v.list
This PR is for 2.1.20-RC3 updates
=> feat: Kotlin 2.1.20-RC3 release

docs/kr.tree, docs/topics/tour/kotlin-tour-intermediate-classes-part-3.md, docs/topics/tour/kotlin-tour-intermediate-null-safety.md
This PR is to add the fourth chapter of the intermediate tour to the staging branch.
=> Intermediate tour: Null safety chapter

static/js/ktl-component/teach/components/teach-launch-course/teach-launch-course.jsx
=> chore: added link to reflection lecture materials

docs/topics/multiplatform/multiplatform-hierarchy.md
* [KT-75255](https://youtrack.jetbrains.com/issue/KT-75255)
* [KT-66439](https://youtrack.jetbrains.com/issue/KT-66439)
=> update: build file instructions

.teamcity/BuildParams.kt, .teamcity/builds/apiReferences/kgp/KotlinGradlePluginBuildApiReference.kt, .teamcity/builds/apiReferences/kotlinx/coroutines/KotlinxCoroutinesBuildApiReference.kt, .teamcity/builds/apiReferences/kotlinx/datetime/KotlinxDatetimeBuildApiReference.kt, .teamcity/builds/apiReferences/kotlinx/io/KotlinxIOBuildApiReference.kt, .teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmBuildApiReference.kt, .teamcity/builds/apiReferences/kotlinx/serialization/KotlinxSerializationBuildApiReference.kt, .teamcity/builds/apiReferences/vcsRoots/Kotlin.kt, .teamcity/builds/apiReferences/vcsRoots/KotlinKGP.kt, .teamcity/builds/apiReferences/vcsRoots/KotlinxCoroutines.kt, .teamcity/builds/apiReferences/vcsRoots/KotlinxDatetime.kt, .teamcity/builds/apiReferences/vcsRoots/KotlinxIO.kt, .teamcity/builds/apiReferences/vcsRoots/KotlinxSerialization.kt, .teamcity/vcsRoots/KotlinLangOrg.kt, dokka-templates/base.ftl, dokka-templates/includes/header.ftl, dokka-templates/includes/source_set_selector.ftl, static/js/page/dokka-template/control-pane.scss, static/js/page/dokka-template/feedback.scss, static/js/page/dokka-template/layout.scss
Required PRs:
https://github.com/Kotlin/kotlinx.coroutines/pull/4349
https://github.com/Kotlin/kotlinx.serialization/pull/2927
https://github.com/Kotlin/kotlinx-datetime/pull/483
https://github.com/Kotlin/kotlinx-io/pull/432
https://code.jetbrains.team/p/kt/repositories/kotlin/reviews/20141/timeline (KGP)
https://code.jetbrains.team/p/kt/repositories/kotlin/reviews/20142/timeline (stdlib)
cc @whyoleg
=> Update templates for Dokka 2.0.0

.teamcity/BuildParams.kt, .teamcity/builds/apiReferences/kgp/KotlinGradlePluginPrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/kotlinx/coroutines/KotlinxCoroutinesPrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/kotlinx/datetime/KotlinxDatetimePrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/kotlinx/io/KotlinxIOPrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmPrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/kotlinx/serialization/KotlinxSerializationPrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/stdlib/BuildStdlibApiReference.kt, .teamcity/builds/apiReferences/stdlib/StdlibPrepareDokkaTemplates.kt, .teamcity/builds/apiReferences/templates/PrepareDokkaTemplate.kt, dokka-templates/includes/page_metadata.ftl
https://youtrack.jetbrains.com/issue/KTL-1754
=> ktl-1754 chore: Add context to the API refs title

docs/topics/tour/kotlin-tour-intermediate-classes-interfaces.md, docs/topics/tour/kotlin-tour-intermediate-lambdas-receiver.md, docs/topics/tour/kotlin-tour-intermediate-libraries-and-apis.md, docs/topics/tour/kotlin-tour-intermediate-null-safety.md, docs/topics/tour/kotlin-tour-intermediate-objects.md, docs/topics/tour/kotlin-tour-intermediate-open-special-classes.md, docs/topics/tour/kotlin-tour-intermediate-properties.md
This PR makes some headers uniform in the intermediate tour and adds additional print statements to some exercises.
=> Minor updates to intermediate tour

docs/topics/tour/kotlin-tour-intermediate-classes-interfaces.md
This PR fixes samples in the Delegation section of the intermediate tour.
=> Fix Delegation samples in intermediate tour

docs/topics/command-line.md, docs/topics/compiler-reference.md
This PR updates the information about Kotlin REPL for Kotlin 2.2.0.
=> Kotlin REPL changes for Kotlin 2.2.0

docs/topics/jvm/jvm-records.md
This PR adds content  about annotating JVM records as part of Kotlin 2.2.0.
=> Update JVM records for 2.2.0

docs/topics/compiler-reference.md, docs/topics/inline-classes.md, docs/topics/jvm/java-to-kotlin-interop.md
This PR adds information about the `@JvmExposeBoxed` annotation for 2.2.0.
=> Add information about `@JvmExposeBoxed` annotation for 2.2.0

docs/topics/native/mapping-function-pointers-from-c.md, docs/topics/native/mapping-strings-from-c.md, docs/topics/native/native-app-with-c-and-libcurl.md, docs/topics/native/native-c-interop.md
* [KT-77506](https://youtrack.jetbrains.com/issue/KT-77506)
* [KT-77618](https://youtrack.jetbrains.com/issue/KT-77618)
=> update: minor c interop updates

blocks/main/hero/hero.tsx, blocks/main/kotlin-plus-ai/index.tsx, blocks/main/why-kotlin/why-kotlin.tsx, pages/index.tsx, test/page/index-page.ts
=> chore: add test selectors

docs/topics/jvm/jvm-get-started.md
This PR adds a Groovy sample to the Get started with Kotlin/JVM tutorial. Reviewed Ksenia Sergeeva.
=> Updated Get started with Kotlin/JVM with Groovy sample

static/js/page/dokka-template/feedback.js
https://youtrack.jetbrains.com/issue/KTL-2762/Update-fields-in-API-Core-feedback-form
=> KTL-2762 Update fields in API Core feedback form

.teamcity/references/builds/kotlinx/serialization/KotlinxSerializationBuildApiReference.kt
related: https://github.com/Kotlin/kotlinx.serialization/pull/3005
=> Update kotlinx-serialization API Reference task for DGPv2

docs/kr.tree, docs/topics/configure-build-for-eap.md, docs/topics/eap.md, docs/topics/whatsnew/whatsnew-eap.md, docs/v.list
This PR adds details about the 2.2.20-Beta1 EAP release.
=> feat: Kotlin 2.2.20-Beta1 EAP release details

test/production/play-tab.spec.ts, test/production/solutions-tab.spec.ts
Also, there is a small fix for Play tab tests.
=> Add Playwright tests for Solutions tab.

.teamcity/kotlinlang/builds/BuildReferenceDocs.kt, test/production/play-tab.spec.ts
https://youtrack.jetbrains.com/issue/KTL-1690/Create-API-button-on-top-level
=> ktl-1690 chore: Update version of webhelp frontend

docs/topics/eap.md
Updating documentation with Kotlin 2.2.10-RC2 release details
=> update: Kotlin 2.2.10-RC2 eap release details

test/e2e/webhelp.spec.ts
https://youtrack.jetbrains.com/issue/KTL-2871/Docs-Add-test-to-ensure-external-links-open-in-the-same-tab
=> KTL-2871 Docs: Add test to ensure external links open in the same tab

blocks/community/keep-in-touch/keep-in-touch.tsx
https://youtrack.jetbrains.com/issue/KTL-2543
=> KTL-2543 Replace the link to awesome kotlin

test/production/community-overview-rest-buttons.spec.ts
https://youtrack.jetbrains.com/issue/KTL-2543
=> KTL-2543 chore: update community test

.teamcity/common/extensions/playgrounds.kt, .teamcity/kotlinlang/builds/FetchBlogNews.kt, .teamcity/tests/buildTypes/E2EProductionTest.kt
Update to disable slack notifications for playground projects
=> disable slack notifications if project contains playground in its name

data/releases.yml, docs/topics/eap.md, docs/topics/releases.md, docs/v.list
This PR adds information for the 2.2.10 release
=> feat: add Kotlin 2.2.10 release info

pages/index.tsx
```diff
if (!isClosed && !optlyBanner) {
window.optlyBanner = true;
// add Optly banner
utils.waitForElement(extension.insertAfter).then(function (elem) {
//var isHeader = elem.matches("header");
var positionToInsert = extension.positionToInsert;
-        elem.insertAdjacentHTML(positionToInsert, extension.$html);
+        var isOldReactNode = positionToInsert === 'beforebegin' &&
+            elem.previousSibling && elem.previousSibling.nodeType === 8 &&
+            elem.previousSibling.textContent.indexOf('ktl_component:') !== -1;
+        if (isOldReactNode) {
+            var comment = elem.previousSibling;
+            var range = document.createRange();
+            range.setStartBefore(comment);
+            var fragment = range.createContextualFragment(extension.$html);
+ …
```
=> feat(KTL-2272): Double Header on pages when Top Banner is active

docs/kr.tree, docs/topics/eap.md, docs/v.list
This PR adds details about the 2.2.20-RC EAP release.
=> feat: Kotlin 2.2.20-RC EAP release details

docs/topics/basic-types.md, docs/topics/properties.md, docs/topics/tour/kotlin-tour-intermediate-properties.md
This PR improves the Properties page by improving the quality of the examples by making them more reflective of the real world, amongst other things.
=> Improve Properties page

docs/topics/roadmap.md
=> fix: update roadmap.md

docs/topics/roadmap.md
Tooling: Kotlin Notebooks: support new use cases
=> update: add a new roadmap item

docs/kr.tree, docs/topics/eap.md, docs/v.list
This PR adds details about the 2.2.20-RC2 EAP release.
=> feat: Kotlin 2.2.20-RC2 EAP release details

docs/topics/gradle/gradle-configure-project.md, docs/v.list
This PR updates the `v.list` file and gradle docs with version updates for the 2.2.20 release
=> feat: v.list and gradle version updates for 2.2.20 release

docs/topics/native/native-debugging.md
[KT-77332](https://youtrack.jetbrains.com/issue/KT-77332) Native: Improve object summaries in debugger
=> feat: new object summaries
