docs/reference/generics.md

I guess that "return" is rhetorical and not a syntactical. :)

Fix formating error in generics.md

---

docs/tutorials/command-line.md

Trying to run the list_folders.kts script without supplying a path results in a ArrayIndexOutOfBoundsException. Therefore I've added a parameter placeholder to the example command.

Command-line tutorial: Add path parameter to list_folders script command

---

docs/reference/using-gradle.md

The Android gradle plugin was renamed and the "android" one is deprecated.

Use the new Android plugin name for Gradle

---

_data/videos.yml

Added an Android talk, removed one talk in russian (it was added to the events list before).
I'd like to add two more talks, but now I can't (https://youtrack.jetbrains.com/issue/KT-7499).

Changes in 'Learn -> Videos -> Conferences and Events'

---

docs/reference/classes.md

I think the new text is clearer around not needing open on abstract classes and functions.

Clarified abstract classes / functions not needing open

---

_data/events.yml

Slides and videos are already available from:
1. Kotlin - the Swift of Android (DroidCon 2015 Berlin, Germany)
2. Kotlin on Android (ETE'15 Philadelphia, PA, USA)

added video and slides references

---

docs/reference/functions.md

1. Array's size property is deprecated. so It changed to size() method.
2. Character changed to Char because of compile error.

Fixed invalid Example.

---

_layouts/resources.html

Fix github's search query to return kotlin repos

---

docs/reference/delegated-properties.md

method parameter name doesn't match variable used in function's body

fix variable name in delegated-properties.md

---

docs/reference/equality.md

On the page http://try.kotlinlang.org/#/Examples/Hello, world!/Simplest version/Simplest version.kt
the following:
```java
class X(){
fun equals(x:X) = x===this
}
fun main(args: Array<String>) {
var x=X()
println ( x ) 
println ( x.equals(x) )
println ( x == x )
println ( if (x==null) x===null else x==x )
println ( x?.equals(x) ?: x === null ) // this yields "false"
println ( x?.equals(x) ?: (x === null) )
}
```
prints:
```java
X@40bde56d
true
true
true
false
true
```

precedence of "?:" over "===" ?!?!

---

_data/oss-projects.yml

Add another dependency injection library to the list of OSS projects.

Add Kodein to OSS projects

---

INSTALL.sh

On Ubuntu, the install script produces the following syntax error with default shebang `#!/bin/sh`
``` 
./INSTALL.sh: 10: ./INSTALL.sh: [[: not found
```
Default `/bin/sh` on ubuntu is a link to `/bin/dash` and it seems the script is intended for bash shell.
Specifying the shebang explicitly as `/bin/bash` should work on linux and osx

Specify bash shell in INSTALL.sh shebang

---

docs/reference/ranges.md

As per [Operator Overloading](https://kotlinlang.org/docs/reference/operator-overloading.html):
> Functions that overload operators need to be marked with the `operator` modifier.

Add operator keyword to rangeTo methods

---

_data/oss-projects.yml

beust.com doesn't support https so this gives a scary warning to users who click on it.

Remove https from beust.com

---

docs/reference/delegated-properties.md

Change `guaratees` to `guarantees`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jetbrains/kotlin-web-site/305)

Fix typo in delegated-properties.md

---

docs/reference/control-flow.md

Consequently doesn't make sense in this context. I would guess the intention was either "sequentially" or "consecutively" (both work, but I'd say the former is slightly clearer).

Fix typo in control-flow docs

---

docs/reference/properties.md

Aren't getter and setter optional? Probably having square brackets around it in the full syntax could be better?

Adding square brackets to getter/setter

---

docs/reference/functions.md

Changed function calls in a sample code because there are no array method in Kotlin 1.0 beta

Change function calls

---

docs/reference/operator-overloading.md

Not sure, but may be worth it to mention that `get` and `set` have at least one parameter.

clarified that `invoke` may be used without parameters

---

docs/reference/using-maven.md

Since you defined a default phase for the mojos, explicitly configuring a phase is unnecessary.

unnecessary phase configuration

---

docs/reference/null-safety.md

As this is an explicit list of all possible sources of NPEs I think it should also contain the `!!`-operator that is described at the end of this document ("this will [...] throw an NPE if b is null")

add !! operator to the list of sources for NPEs

---

docs/reference/generics.md
docs/reference/java-interop.md

Incorrect init method: array() instead of arrayOf()

Fixed typo with arrayOf

---

docs/reference/properties.md

Usability is better if the relevant words are links.

link relevant words directly

---

docs/reference/basic-types.md

Explain trimMargin with an example. This is an important function to make multiline strings useful.

add trimMargin() example to basic-types.md

---

docs/reference/collections.md

Small typographic error in Map usage sample: 'map' should be 'readWriteMap'

Fix wrong name in Collections/map example

---

docs/reference/classes.md
docs/reference/nested-classes.md

It's hard to find that information in the doc because it's currently in the chapter about objects, which is not where a Java developer looks for it.
I also added a note on how to create instances of Java functional interfaces, and added a link to the nested classes chapter in the section discussing how to instantiate classes.

document how anonymous inner class instances are created in the nested classes section

---

docs/reference/object-declarations.md

I'm using Intellij 2016.1.2, kotlin plugin 1.0.3-release-IJ2016.1-103
The example code on this site did not compile. I got "Error:(11, 1) Kotlin: Right-hand side has anonymous type. Please specify type explicitly".
The type of "val ab" could not be deferred automatically, so a type for it had to be declared.

Object expressions example code does not compile

---

docs/reference/using-maven.md

- pom.xml is more understanable when in context
- the link to examples zip was old so I replaced it with just a link to the repo assuming developers will know what to do there

added a context to xml and fixed broken link

---

docs/reference/reflection.md

The String class does not have a size property by default.

Size should be length

---

docs/tutorials/command-line.md

The more secure way of installing SDKMAN.

Updates SDKMAN URL to be over SSL

---

docs/reference/comparison-to-scala.md

XML support has been removed from the core and was made optional, pending deprecation and replacement with string interpolation.

Remove built-in XML

---

docs/tutorials/android-plugin.md

Code block to config plugin don't have the background on https://kotlinlang.org/docs/tutorials/android-plugin.html. But it has background on github preview. So I hope that specifying language can solve the issue.

Fix code highlighting

---

docs/reference/using-maven.md

Adds a maven example that doesn't require the process-sources hack by switching off the default-compile and default-testCompile targets that are treated specially by maven.
Also add examples of maven configurations that will generate the two types of Jar file, a minimal and a self-contained Jar file.

Add maven example without using process-sources

---

docs/reference/object-declarations.md

The current link points to the wrong page.

Fix link for static JVM fields and methods

---

_data/oss-projects.yml

I added another OSS project – Glimpse Framework.
Basic idea behind this project is to make OpenGL easy – for both desktop and Android.

Add Glimpse Framework

---

docs/reference/classes.md

Actually it doesn't matter what to use, kotlin or java, when you face a library with final classes/members.

Remove irrelevant reasoning

---

pages/docs/tutorials/command-line.md

Kotlin is also available from MacPorts for Mac OS X/macOS users.

Add compiler installation instructions for MacPorts users

---

pages/docs/reference/operator-overloading.md

Otherwise this fails.
```
fun eq(a: Any?, b: Any?): Boolean {
return a?.equals(b) ?: b === null
}
@Test fun testEquals() {
assertTrue(eq("a", "a"))
}
```

Add required parens for == translation.

---

pages/docs/reference/generics.md

Fix issue as the followed snapshot that "Generic functions" & "Generic constraints" should be sub-headings of "Generic" in the TOC of the PDF. While currently they are in same level.

fix heading levels of generics.md

---

pages/docs/reference/classes.md

I feel that the properties section could use expansion. I understand its syntactic sugar to us but to many kotlin users it is likely to be an important feature.
My use-case was in trying to explain to a colleague why creating a kotlin interface with `fun getThingies(): Thingies` was a bad idea, and that he should instead put `val thingies: Thingies` on his interface. I wanted to refer him to the kotlin lang docs, but was a little disappointed with what is here right now, so I figured I would suggest these changes.
My main goal was to explain how properties can be overriden, and some of the specifics around syntax for it. I think this syntax is fairly intuitive, but was not intuitive enough for my afforementioned collegue. In this sense, a few extra words elaborating on the subject I think …

Additional explaination of overriding properties

---

pages/docs/reference/extensions.md

In the current [docs](https://kotlinlang.org/docs/reference/extensions.html#extensions-are-resolved-statically), it says:
> By defining an extension, you do not insert new members into a class, but merely make new functions callable with the dot-notation on instances of this class.
As the next paragraph explains, the current version is misleading: we won't actually *call* the method defined at the instance type, but at the variable type. Proposal:
> [...] on variables of this type.

Clarifies intro of method dispatching for extensions

---

pages/community/user-groups.md

This url (https://kotlin.connpass.com/) is available now. Best regards.

fixed url of Japan Kotlin user group

---

data/cities.yml
data/events.xml

1. Appdevcon
2. Droidcon-boston
3. Kotlin User Group Cologne Kickoff
4. Brooklyn Kotlin Kickoff
5. Warsaw Cloud Native Meetup
6. Android Meetup - Belo Horizonte
7. Kotlin user group Berlin
8. CADEC - CALLISTA DEVELOPER'S CONFERENCE 2017
9. Сodefest
10. Mix-IT
11. JPoint — Java conference (2)
12. Monkey Tech Days
13. Javaday Istanbul
14. KotlinMAD
15. Kotlin Rio
16. Toulouse Java User Group
17. Java User Group Hamburg
18. Mobius conference

Add 19 talks and cities

---

pages/community/user-groups.md

We had to recreate the Chicago Kotlin Users Group, since, while I was out on vacation, the meetup group expired. Unfortunately, Meetup support has not been responsive, so I created a new Meetup and will be re-inviting all the old members. So, I had to update the url for the meetup group.

Update Chicago Kotlin Users Group URL

---

pages/docs/tutorials/getting-started-eclipse.md

The URL of the button image was out-of-date and pointed to a stale image. Therefore you couldn't even drag and drop the link to your Eclipse workspace!
Used the external button given on the eclipse website which works as of writing:
http://marketplace.eclipse.org/content/kotlin-plugin-eclipse#group-external-install-button

Fix Eclipse install button

---

pages/docs/reference/comparison-to-java.md
pages/docs/reference/java-interop.md
pages/docs/reference/lambdas.md
pages/docs/reference/returns.md
pages/docs/reference/typecasts.md

I have written a tool to find all missed hash references in all markdown files and then I fixed them after manually verified.
Here are all the fixes.
I will publish the tool as a opensource project a few days later (and post a comment here too).

Fix hash references in all articles

---

pages/docs/reference/using-gradle.md

Added the information about the setting enabled by default in 1.1.1.
Changed the instructions to both enable and disable use cases.

(1.1.1) Update 'Incremental compilation' section

---

pages/docs/reference/index.md

Change "In is aimed at Java developers..." to "It is aimed at Java developers..." in the description for Programming Kotlin at http://kotlinlang.org/docs/reference

Fix minor typo in Programming Kotlin description

---

data/cities.yml
data/events.xml
pages/community/user-groups.md

Add content
Add 34 talks
1. Explotando delegados y extensiones en Kotlin
2. GDG The Dutch Android User Group
3. Mumbai Android Developers Meetup
4. Brooklyn Kotlin Meetup (2)
5. Genome Campus Software Craftsmanship Community
6. Kotlin-ize your Android Development
7. Kotlin User Group Belgium
8. 日本Kotlinユーザグループ
9. Double feature: Kotlin - Why? and Kotlin Enterprise Edition
10. Android Makers Paris 2017
11. Clean Code Days 2017
12. Helsinki Android Meetup<
13. Kotlin — programming language for the JVM by JetBrains
14. Lima Kotlin User Group
15. D3＝Designer &amp; Developer Division
16. Switching from Java to Kotlin
17. Meetup at Daffodil Software
18. New York Kotlin Meetup
19. Kotlin - átállás tapasztalatok
20. Hands-on Kotlin - Learn some Kotlin by solving coding problems.
21. Kotlin Vienna …

Add usergroups, content, talks

---

data/cities.yml
data/events.xml
pages/community/user-groups.md

41 talks:
1. Voxxed Days Athens UPD -> Svetlana Isakova
2. 第3回Kotlin勉強会 ＠Sansan (2)
3. PHX Android/GDGPhoenix
4. Java User Group Hamburg (2)
5. potatotips #39 (iOS/Android開発Tips共有会)
6. Android Makers Paris 2017
7. 第3回Kotlin勉強会 ＠Sansan
8. Go User Group Atlanta
9. Droidcon Vietnam
10. Kotlin User Group Cologne
11. Google I/O Extended 2017 Budapest
12. Central Florida Android Developers Group
13. Polish Java User Group
14. Android Rennes
15. Kotlin User Group Munich - KUG Munich
16. Kotlin London (2)
17. Spring I/O 2017
18. Lublin Java User Group
19. Kotlin User Group Serbia
20. Great Indian Developer Summit
21. Android Devs Meetup (3)
22. Devoxx US 2017 (2)
23. DevFestDC 2017
24. Open Sourse Convention
25. Istanbul Coders
26. j4Guanatos
27. JUG Milano
28. Twin Cities Kotlin User Group
29. …

Add 41 talks, a UG, content

---

data/_nav.yml

It also need a `description` under `- title: Core Libraries` compared to others.

Minor fix for _nav.yml

---

pages/community/slackccugl.md

#beginner seems to be unused, real beginner questions are in #getting-started.

#beginner -> #getting-started

---

pages/docs/reference/sealed-classes.md

The function `eval(expr)` was repeated in both example code blocks, and the second one still referred to the nested `Const` and `Sum`.

Missed update for 1.1, and remove repeated example

---

pages/docs/reference/idioms.md

An example how to do equivalent of Java’s 
``` java
Mapped mapped = Optional.of(data)
.map(d -> transformData(d)))
.orElse(defaultValue);
```
with Kotlin’s nullable reference for chaining.
I had hard time finding how to do this. I believe more examples of what can be achieved using the `let` method would be helpful.

show how to map nullable values if not null

---

data/oss-projects.yml

Original Yested framework is no longer in the development. It has been replaced by a new version which is being actively developed.

Update link to a new version of Yested framework.

---

pages/docs/reference/server-overview.md

There are some unnecessary spaces between "plugin" and "helps".

Remove unnecessary spaces

---

pages/docs/reference/packages.md

Added a link to the Oracle Java 8 documentation to be able to look up "import static" quickly. Not sure whether this is desired in the Kotlin documentation.

"import static" now hyperlink to Java 8 doc

---

pages/docs/reference/functions.md

A code snippet in the page about functions had a grammatic error. Correcting it.

Minor grammatic correction in functions.md

---

pages/docs/reference/classes.md

Typo error: Closing bracket should by parentheses.

Fixed example code typo error

---

pages/docs/reference/classes.md

"x" property from parent class Foo is Int type, not String.

Error in code example

---

pages/docs/reference/operator-overloading.md

Use a.remAssign(b) instead of a.modAssign(b).

Mark assignment a.modAssign(b) as deprecated

---

pages/docs/reference/inline-functions.md

Add section on public API inline function bodies and `@PublishedApi`.

Explain restrictions for public API inline functions

---

pages/docs/reference/functions.md

Moved Parameters up (it is the most important about functions :), Infix notation — down, because is not as popular as return types, named & default arguments, etc

Moved Parameters to the beginning, Infix notation — later

---

pages/docs/reference/extensions.md

Semicolons are missing in the Java examples on the extensions page.

Fix Java syntax

---

pages/docs/tutorials/android-plugin.md

Updated terminology around which `build.gradle` file to apply the Extensions plugin in to match the usual parlance.

Fixed Gradle terminology

---

pages/docs/reference/basic-syntax.md

In some places the value is referenced as it as  $variable while at some places as  ${variable} .
Like in this snippet, in the first part of the code it is referenced as it is without any braces, while below, in the same code it is used with braces. I think it must follow a single convention.

Using similar convention for referencing variables

---

pages/docs/reference/using-gradle.md

Add section about module names that can clash and the way to resolve it with `archivesBaseName`.

(for 1.1.50, don't merge yet) Add section about module names

---

pages/docs/reference/idioms.md

Though Kotlin allows usage of keywords like `data` and `open` for variable names. The syntax highlighter on the rendered HTML page highlights them as keywords. This could be confusing to developers who are just being introduced to the `data` keyword.

Replace variable named 'data' with 'value'

---

pages/docs/reference/reflection.md

Description of the first code example implies that `x` is immutable, so I changed its declaration to use `val` and added a separate example for a mutable variable.

Fix property references example in the reflection docs

---

pages/docs/reference/functions.md

The expression `2*x` should be formatted as `2 * x`.

Update formatting to match Kotlin style

---

pages/docs/reference/delegated-properties.md

Both of these "this prints:" examples had Kotlin keywords in them, so they were displayed in multicolor.

Remove Kotlin formatting from print statements

---

pages/docs/reference/functions.md

Tailrec part of `if (x == Math.cos(x)) x` is equivalent of `if (x == y) return x` not `if (x == y) return y`, if I get it right...

Fix tailrec example

---

data/events.xml

Organizer UG name fix for the event in Banja Luka form 5th October.

Fixing the name of organizer user group for one event.

---

pages/docs/reference/annotations.md

'Any?' is not compilable with an error message "Type argument is not within its bounds"

Fix sample code

---

pages/docs/reference/delegated-properties.md

Remove apostrophe for plural as per http://www.thepunctuationguide.com/apostrophe.html

Remove apostrophe for plural

---

pages/docs/reference/generics.md

To make them more closely corresponding to Java examples (`interface Source<out T>`) and to Kotlin’s own standard library (`interface Comparable<in T>`).
It’s been confusing for me – why Kotlin examples used `abstract class` instead of `interface` (I believe that’s because of historical reasons, not relevant today).

change abstract classes to interfaces in generics

---

pages/docs/reference/coding-conventions.md

Closing parenthesis in line 27 in file pages/docs/references/coding-conventions.md was missing

Add missing parenthesis in coding-conventions.md

---

pages/docs/reference/coding-conventions.md

It is stated in the description, that only two letter acronyms are capitalized. 
But when scanning over the text, this can be overlooked. 
Therefore a  three-letter-acronym is added to make it clear with the examples, that 
two letters are capitalized, and three ore more are just with capitalized first letter.

Add a three-letter acronym

---

pages/docs/tutorials/native/interop-with-c.md

extra backticks removed
added `?.toKString()` to the curl error, otherwise a pointer message is print

interop c // fix markdown and convert cpointer to KString

---

pages/docs/reference/comparison-to-java.md

There is this endless discussion about whether or not to add the ternary operator to Kotlin https://discuss.kotlinlang.org/t/ternary-operator/2116/122 and someone pointed out, that the docs don't list this as a difference to java. 
It seems like the ternary operator wont be added so I think it is a good idea to state this here, as it makes changing from java easier.

Update comparison-to-java.md Ternary-Operator

---

pages/docs/reference/properties.md

The last word, field, is wrapped to the next line and can be a bit confusing.  This prevents wrapping on standard zoom.

Fix confusing wrapping on backing properties example.

---

pages/docs/reference/type-safe-builders.md

- Update to add callout out to the concept of DSL (popular phrasing in Ruby etc).
- Remove explicit callout to Groovy in header, this page stands on it's own without referencing Groovy content.

Update preamble of type-safe builders to say DSL

---

pages/docs/reference/basic-syntax.md

'kiwi' is a bird, or a person that normally does fly, but for some reason does not (eg: grounded wing commander), or someone from New Zealand, or, sometimes, the nzd/usd currency pair.  just as grapefruit are not called grape (a grape is something else entirely), neither should the kiwifruit be called a kiwi.  yeah, I understand that in many people's minds, kiwi is also the fruit, but, it's just not right.  Have a look at this: https://medium.com/new-zealand-thoughts/kiwi-kiwi-or-kiwifruit-8ac0b30ac447

correct kiwi -> kiwifruit

---

pages/docs/reference/lambdas.md
pages/docs/reference/reflection.md

* Massive reordering of the sections for better logical structure: it's now *Types* -> *Instances* -> *Usages*
* Remove duplicate explanations and examples, including those redundant with the new structure, provide links where needed
* Move sections about `it` and destucturing to the lambdas chapter
* Fix inline functions mentioned as a performance tool, which they are not; Tell about control flow instead
* Better structure of function types explanation, including `suspend` function types and function types with receivers, add a note on associativity, mention typealiases 
* Use `fold` as a single example in *Higher-Order Functions* (instead of `lock` and `map`)
* New section on instantiating a function type, with function type interchangeability explanation
* New section on invoking a …

Improve FP docs

---

pages/docs/reference/classes.md

The page lists the *Design and document for inheritance or else prohibit it* Effective Java entry as being item 17 in "Effective Java".  This is technically an incorrect reference since listing the book as "Effective Java" implies the first edition, in which the mentioned item is #15. The citation should therefore be "Effective Java, 2nd Edition, Item #17". But given that the third edition was released in this past December, I think it, as the latest edition. should be cited. In the third edition it's item #19. Thus I recommend chaining the cite to  "Effective Java, 3rd Edition, Item #19".

Update Effective Java citation in classes.md

---

pages/docs/reference/coding-conventions.md

Just a small edit to fix a missing word in docs.

Add missing 'if' in coding conventions

---

pages/docs/reference/delegated-properties.md

prop declaration in code is generated by compiler should use var keyword instead of val keyword, as it was used var keyword in original Also I add set method.

Fix incorrect property declaration

---

pages/docs/tutorials/android-plugin.md

There is no such thing as the `@Parcelable` annotation, so it's rather a typo. This PR fixes the typo.

Fix typo: @Parcelize, instead of @Parcelable

---

pages/docs/tutorials/android-plugin.md

This class should be named `User` instead of `Value`.

Class name on documentation

---

pages/docs/reference/using-gradle.md

In Gradle Kotlin DSL all configurations are methods.
Means the current documentation is just wrong and lead to issues.
This will fix it 👍

Call compile method for Gradle Kotlin DSL

---

pages/docs/reference/coding-conventions.md

the previous example didn't trim anything, as noted in the documentation:
"In case if there are non-blank lines with no leading whitespace characters (no indent at all) then the common indent is 0, and therefore this function doesn't change the indentation."
The new snippet formatting is the one applied by IntelliJ when choosing formatting based on the Kotlin style guide

fix example usage of trimIndent

---

pages/docs/reference/extensions.md

I don't have prior experience of Java, C#, or Gosu, I'm also not familiar with a concept of extensions and it was **not** obvious to me that an extension declared outside of a class' scope does not have an access to the class' private (and protected?) members.
I was able to deduce an answer to my question about visibility from the following paragraph, though:
> Extensions do not actually modify classes they extend. By defining an extension, you do not insert new members into a class, but merely make new functions callable with the dot-notation on variables of this type.
However, I believe that the documentation would benefit by adding this information explicitly. 
Not sure how to formulate it better -- I'm open to any suggestions.

Add note on visibility for extensions

---

pages/docs/tutorials/native/targeting-multiple-platforms.md

Tested like below:
```
joel@JOEL-LAPTOP C:\users\joel\code
$ kotlinc -list_targets
mingw_x64:                    (default) mingw
wasm32:
zephyr_stm32f4_disco:
joel@JOEL-LAPTOP C:\users\joel\code
$ bash
joel@JOEL-LAPTOP:/mnt/c/Users/joel/code$ ~/.konan/kotlin-native-linux-0.8.1/bin/kotlinc -list_targets
linux_x64:                    (default) linux
linux_arm32_hfp:                        raspberrypi
linux_mips32:
linux_mipsel32:
android_arm32:
android_arm64:
wasm32:
zephyr_stm32f4_disco:
```

Include Windows Subsystem for Linux as environment

---

pages/docs/reference/functions.md

Let's keep the example stylistically good: It seems unwise to do exact floating point comparison in an infinite loop as stated. Let's compare against a target precision of 10^-10 instead (machine epsilon of Double is 2^-52 ~ 1.11e-16, and the result is expected to be < 1.0, so 10^-15 sounds safe, but let's just go for 10^-10). 
Additionally, the loop code optimizes by only calling Math.cos(x) once, but the compiler hopefully won't do that, as the language is not purely functional. So I added the second Math.cos(x) code into the loop, for clarity.
Also fixed something that looks like a russianism in the text (apologies)

Stylistic changes for cos() fixpoint computation

---

kotlin-website.py

We need to split the global `_nav.yml` into parts to share site sources between repositories. We assume the site is included under the `pages/` folder, thus there is no need to change the way `.md` files are rendered.
Right now the following is supported in the root _nav.yml:
```
- title: Native
description: Kotlin Native and iOS
'@include': /docs/reference/native/_nav.yml
'@prefix': /docs/reference/native/
```
The `@include` and `@prefix` elements will be replaced with the `content` element, the included yml file contents are placed under the created `content` element. We assume the imported yml is list.
`.yml` file to import:
```
- url: INTEROP.html
title: C Interop
- url: OBJC_INTEROP.md
title: Objective-C/Swift Interop
```
The `@prefix` parameter helps to fix `url` elements of the …

support for includes in the _nav.yml

---

data/_nav.yml
pages/docs/reference/building-mpp-with-gradle.md
pages/docs/reference/multiplatform.md
pages/docs/reference/platform-specific-declarations.md
pages/docs/reference/using-gradle.md

* Rewrite old MPP page, turn it into an introduction
* Move expect/actual to a separate page
* Add a page for Gradle configuration and DSL, also explaining the
concepts

(WIP) Update MPP docs for 1.3

---

pages/docs/reference/building-mpp-with-gradle.md

A single quote was missing at the end. This has been added.

Enabling experimental Gradle metadata incorrect

---

pages/docs/reference/server-overview.md

Replace dead article link for Corda with link to their homepage.

Fix dead link in server overview docs

---

pages/docs/tutorials/coroutines/async-programming.md

Let's make Erik Meijer clickable again :tada:

Add missing closing parenthesis in markdown link

---

pages/docs/tutorials/kotlin-android.md
templates/pages/index.html

- before the main weg page and the Android sub page were
linking to Android Studio Preview. Since Android Studio 3.0 stable
is out for some time now we really should link to the stable version
instead!

docs(android): Link to Android Studio stable

---

pages/docs/tutorials/build-tools.md

As Griffon now uses Gradle as its recommended build system, there's no need to mention it in the build tools section.

Remove Griffon from build-tools.md

---

pages/docs/reference/platform-specific-declarations.md

Java String.format uses vararg, so we should pass arguments as vararg. Otherwise it compiles ok but throws a runtime exception |java.util.IllegalFormatConversionException: x != [Ljava.lang.Object;"
I banged my head for half a day to understand what's wrong and in the end Andrey Mischenko showed me the answer.

Fix a "bug" in code snippet

---

pages/docs/reference/native-overview.md

Issue does not exist in header of https://kotlinlang.org/docs/tutorials/native/apple-framework.html, but link to the page has the typo.

fix small typo ("a Apple" -> "an Apple")

---

pages/docs/reference/ranges.md

The range 4..1 is empty, thus incorrect. Should use downTo instead

docs(ranges) : remove incorrect example

---

pages/docs/reference/compatibility-guide-13.md

The original rendering on kotlinlang.org was completely unreadable, it
was hard to make out where each point starts or ends.
This is an attempt to fix it by using quotation to make the points
render in a more readable way.

Quote the compatibility guide point bodies to make them render better

---

pages/docs/reference/compiler-plugins.md

TaskRunner is defined as  the sample of SAM with receiver stuff but TaskHandler class, which is not defined, is used.

Fixed a typo in sam-with-receiver samples

---

pages/docs/tutorials/native/interop-with-c.md

I downloaded the Kotlin/Native compiler using the linux artifact on version 0.9.3. I'm running Ubuntu 18.04 with libcurl4 and libcurl4-openssl-dev installed. The original .def file did not work, with `cinterop` saying "Could not find curl/curl.h". I then added `-I/usr/include/x86_64-linux-gnu`, and curl.h was found but it was complaining about a missing definition for the macro `__glibc_clang_prereq`. After adding the second compiler include (`-I/usr/include`) creation of the .klib worked.

Fix broken libcurl.def in tutorial

---

pages/docs/tutorials/coroutines/coroutines-basic-jvm.md

To be consistent with https://github.com/Kotlin/kotlinx.coroutines/blob/master/README.md.
- Versions of Kotlin and coroutine are set to latest
- Avoid deprecated gradle configuration.

Sync to coroutine's README.md.

---

pages/docs/tutorials/httpservlets.md

https://youtrack.jetbrains.com/issue/KT-28714
According to the code in https://github.com/JetBrains/kotlin-examples/blob/master/tutorials/servlet-web-applications/build.gradle , `war` is surrounded by `'`.

KT-28714 Fix plugin statement

---

pages/docs/reference/kapt.md
pages/docs/reference/using-gradle.md

- added multi-language samples with Kotlin DSL
- moved the kapt-gradle part from using-gradle.md to kapt.md
- revised the text.

docs: added multi-language examples, moved kapt part to kapt.md

---

pages/docs/reference/collections.md

I think it's important to note this, as a lot of people (like myself) might come from languages where the standard library has persistent collections (like Scala) and operations on them therefore are completely thread-safe. Given the ones in Kotlin look very similar one might immediately assume they can be used the same way while a little more care needed in practice.

Add note about lack of thread-safety of immutable collection ops

---

pages/docs/reference/building-mpp-with-gradle.md

Unify the language explaining the same thing when describing what host OS-es are supported. 
It's "drier" but may help non-native English speakers as it reduces complexity.

Clean up language for building multiplatform projects

---

README.md

Currently the README has links to `_data` however this is actually the `data` folder.

Fix README to point to correct data folder.

---

pages/docs/reference/delegated-properties.md

Reverts JetBrains/kotlin-web-site#1285

Revert "Fix typo in variable name"

---

pages/docs/reference/null-safety.md

- In the 'Checking for null in conditions' example, type of `b` is `String` by default. So `b != null` is always `true`. So, it will be better to specify the variable's type to `String?`:
- In the 'Safe Calls' example, it will be better to mention that a safe call on non-null receiver of type `String` is unnecessary.

Clarify 'Null Safety' examples

---

pages/docs/reference/nested-classes.md

In according to [coding conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#colon)
> put a space before a colon ... after the object keyword.

Added the space after the object keyword

---

pages/docs/reference/generics.md

In according to [coding conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#colon) there are no cases where a space before a colon is needed.

Removed the space before the colon

---

pages/docs/reference/generics.md

When I read the documentation, I wrongly assumed that a `where` clause created a union type.  If I had looked really carefully, I probably could have figured out that it was an intersection type.  Given how brief the documentation was for this feature, I thought a little clarification would be beneficial.

Added two more sentences about the 'where' clause

---

pages/docs/reference/using-gradle.md

"It is also possible to configure all Kotlin compilation tasks in the project" 
Specified Groovy syntax doesn't work  in Android Studio 3.3.1, while corrected version does

Correct Groovy syntax for all tasks Compiler Options

---

pages/docs/reference/object-declarations.md

Since Java 8,  'final' keyword is not mandatory for variables accessed from anonymous inner classes when variables are effectively final.

Update object-declarations.md to reflect relaxed restriction on final keyword since Java 8

---

pages/docs/reference/exceptions.md

As `finally` can have zero or one block, it is recommended to specify the same here.

Concretize finally block occurrence in Exceptions

---

pages/docs/tutorials/native/mpp-ios-android.md

The purpose of this PR is twofold:
1. Find out for myself whether Kotlin/Native supports LLVM bitcode output for Apple store submission.
2.
a. If bitcode is supported, remove this scary instruction that suggests bitcode is not supported, rendering Kotlin/Native very very risky to ever use in an iOS project. Apple may one day require bitcode for iOS apps (they already do for tvOS and watchOS apps).
b. Perhaps this instruction can be augmented or replaced with https://github.com/JetBrains/kotlin-native/blob/master/FAQ.md#q-how-do-i-enable-bitcode-for-my-kotlin-framework, if there is a problem with removing this section outright.

remove "disable bitcode" instructions from Kotlin/Native iOS+Android tutorial

---

pages/docs/reference/java-to-kotlin-interop.md

Added doc on using `@JvmDefault` annotation.
Added the page intro.
Replaced the meaningless examples.
Staging build: https://branch-doc-jvmdefault.kotlin-web-site.labs.jb.gg/docs/reference/java-to-kotlin-interop.html#default-methods-in-interfaces

docs: jvmdefault annotation

---

pages/docs/reference/basic-types.md

Add some examples for primitive arrays using:
-  `IntArray(N)`
- `IntArray(N, 42)` 
-  `IntArray(size, { it * 1 } ) `

Update to basic-types primitive array

---

pages/docs/reference/java-interop.md

It is not mapped same way as say `kotlin.CharSequence`, because `kotlin.Deprecated` is a separate real annotation class.

Remove java.lang.Deprecated from mapped types

---

pages/docs/tutorials/native/mapping-struct-union-types-from-c.md

Fix the Mapping Struct and Union Types from C tutorial. The navigation at the beginning of the tutorial should be Mapping Function Pointers from C instead of Mapping Struct and Union Types from C.

Fix the Mapping Struct and Union Types from C tutorial

---

pages/docs/reference/delegated-properties.md

Clarified requirements for non-synchronized `by lazy {...}`

Delegated properties: Missing import; Lazy on the same Thread

---

data/oss-projects.yml

TornadoFX is already referenced at the bottom of the page. I removed this section instead of that one because this incorrectly labels it as a library.

Remove duplicate TornadoFX link

---

pages/docs/reference/experimental.md

At the moment, page only mentions the "normal" gradle project syntax, which is not compatible with multiplatform projects.

feat: add gradle multiplatform experimental syntax

---

pages/docs/reference/basic-types.md

Moved the lambda function outside the parentheses for IntArray for the best practice

Moved the lambda function outside the parentheses

---

pages/docs/reference/functions.md

In Kotlin `Set` type denotes read-only set, while this function requires mutation.

Fix wrong type in sample, section "Local functions"

---

pages/docs/reference/lambdas.md

The original description of the 'full' syntax had less code than the 'simple' syntax shown later.

Fix apparent error in 'Lambda Expression Syntax'

---

data/oss-projects.yml

https://github.com/dodyg/AndroidRivers has not been touched in over four years and doesn´t even build with gradle

remove AndroidRivers

---

pages/docs/reference/using-gradle.md

As described in the [Kotlin 1.3.40 announcement](https://blog.jetbrains.com/kotlin/2019/06/kotlin-1-3-40-released/)

Update the Kotlin/JS documentation for the new Gradle plugin

---

pages/docs/reference/classes.md

"many" is ambiguous and implies that there is a certain number of inherited classes required before the behaviour kicks in. On the other hand, "multiple" simply states that if a class inherits more than one class, then it must disambiguate the construction process.

Small change to classes doc

---

pages/docs/reference/kapt.md

Mention that kapt incremental annotation processing is enabled by default starting version `1.3.50`.

Fix kapt incremental annotation processing documentation.

---

pages/docs/reference/annotations.md
pages/docs/reference/classes.md
pages/docs/reference/coding-conventions.md
pages/docs/reference/delegated-properties.md
pages/docs/reference/experimental.md
pages/docs/reference/generics.md
pages/docs/reference/nested-classes.md
pages/docs/tutorials/android-plugin.md

Fix wording according to received feedback 
- _camel case_ instead of _camel humps_
- _can_ instead of _be able to_ where applicable
Fix formatting.

chore: fix wording ("camel humps" and "be able to")

---

pages/docs/reference/basic-types.md

val a=1L //Works
val b=1l // Error : Use 'L' instead of 'l'

The Long only supports 'L' as suffix

---

pages/user-groups/user-group-list.md

Novosibirsk Kotlin User Group (https://vk.com/kotlin54) seems to be nonexistent.

Remove broken link to a user group

---

pages/docs/reference/idioms.md

Renamed `defaultValueIfValueIsNull` to formally correct (and terribly long) `defaultValueIfValueOrTransformationResultIsNull`.
Other possible fixes:
* remove idiom as not correct enough
* replace with `it (value != null) transform(value) else defaultValue`
* find a correct idiom (I was unable to do so)

'Map nullable value if not null' idiom fix

---

data/releases.yml
pages/docs/tutorials/coroutines/coroutines-basic-jvm.md

The coroutines docs didn't have the latest version, so I added a `data` element to hopefully more easily update this information.
I'm assuming more people will be updating the `data` directory more often than digging down into each page and making sure these versions are correct.

Updated coroutines versioning information.

---

pages/docs/reference/functions.md

The examples showing precedence of infix function calls have some ambiguity due to the use of the conjunction `and`, which is also a bitwise operation keyword in Kotlin, to join two equivalent expressions in a sentence. 
The example block is enclosed in indented quoting (>) which drowns the monospace font otherwise differentiating the conjunctive use of the `and` between the expressions. It all appears as though one long expressions and takes you a few minutes to get the gist of what's going on.
see:

Remove ambiguity from infix function calls predence examples

---

pages/docs/reference/using-gradle.md

Updates documentation to use Gradle's lazy task configuration API to configure the `KotlinCompile` task.
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html
CC: @big-guy @bamboo @eskatos

Use Gradle Task Configuration API in Documentation

---

pages/docs/reference/extensions.md

The unused parameter p: Int is confusing. On the first sight the reader might get the impression that p - as the port - is needed, but is actually already set within the constructor.

Deleted unused parameter p

---

pages/docs/reference/multiplatform.md

I've added a link to our [new landing](https://www.jetbrains.com/lp/mobilecrossplatform/). Is it OK here or should I move it elsewhere?

Added a link to Mobile MPP landing page

---

data/oss-projects.yml

Please, this pull request replaces **FunKtionale** by **Arrow** and **Arrow Meta** libraries.
**FunKtionale** and **Kategory** libraries were joined to create **Arrow**.
Thanks in advance!

Replace FunKtionale by Arrow and Arrow Meta

---

pages/docs/reference/using-gradle.md

According to Gradle documentation [1]:
> To apply a community plugin from the portal, the fully qualified plugin id must be used
> All other binary plugins must use the fully qualified form of the plugin id (e.g. com.github.foo.bar), although some legacy plugins may still utilize a short, unqualified form.
`kotlin()` is used in other code snippets on the page. I don't see a reason not to use it in Android snippet as well.
[1] https://docs.gradle.org/current/userguide/plugins.html

Use fully qualified Android Gradle plugin ID

---

pages/docs/reference/classes.md

This is a small change based on the discussion here: https://discuss.kotlinlang.org/t/why-is-by-lazy-not-happy-with-in-construction-property-initialization/15184/8?u=wasabi375
The problem there is 
```kotlin
class A {
val y: Int
val z: Int by lazy {
y // ERROR: variable 'y' must be initialized -- Why?
}
val w: Int
get() = y // No error!
constructor(x: Int) {
y = x
}
}
```
The original author missed that the initializer of `z` ( in this case the lazy delegate) is created before the secondary constructor `y = x` is executed. He suggested the change here.

Clarify constructor and property initializer execution order

---

pages/docs/reference/lambdas.md

Skip redirection from MSDN to Microsoft Docs and link directly to the MS Docs article.

Fixed link to LINQ

---

pages/docs/tutorials/command-line.md

If the mode is omitted the code is treated as kotlin code, and options to compile the code are shown.

Added shell mode to Chocolatey item

---

pages/docs/reference/ranges.md

Removed an inaccurate sentence about the last element of a progression. Clarified the definition of the last element with an example.

fix: progression docs

---

pages/docs/reference/scope-functions.md

Print the results in order to get more feedback from the samples.
This also fixes "variable 'adam' is never used" noticed messages.

Print the results in order to provide feedback

---

templates/pages/index.html

I was writing up an email suggesting the use of Kotlin over Java for a project.
The "Why Kotlin?" section of the site is an excellent showcase of the benefits of Kotlin, so it would be great to be able to link directly there.
Thanks for the amazing work you're all doing with Kotlin!

Add ID to "Why Kotlin?" section

---

pages/docs/reference/collection-write.md

The `sets` should be `maps` according to the context.

fix a typo

---

kotlin-website.py

Because that the timestamps of the assets always changed after `yarn run build`.
Use MD5 digest can prevent that all generated pages have changed in each build even no asset source file change.

Use MD5 digest instead of timestamp as asset version

---

data/events.xml
pages/user-groups/user-group-list.md

Sydney Kotlin User Group was consolidated with other related local meetups into SYDspace last year. This updates all the sydkotlin.space links to sydspace.org/kotlin links.

Update links for Sydney Kotlin UG

---

pages/docs/tutorials/android-plugin.md

YT: https://youtrack.jetbrains.com/issue/KT-36692
Staging: https://branch-android-ext-not-experimental.kotlin-web-site.labs.jb.gg/docs/tutorials/android-plugin.html

fix: Parcelable impl generator is not experimental

---

pages/docs/reference/basic-types.md

I have just started to learn Kotlin. While going through the basic-types section of the docs, it wasn't clear to me what the behavior of the division operator was. 
A quick search led me to https://discuss.kotlinlang.org/t/dividing-integers/1662
I understand any implied consistency with Java, but figured that it would be good to be more explicit about it in the docs since people might be coming to Kotlin from a variety of languages or be new to programming in general.

Update basic-types.md to clarify integer division

---

static/css/playgrounds.scss

**Not intended to be merged as-is.**
Right now, if JS is disabled, code blocks are not visible at all, and leave blank space on the page:
---
---
Obviously just removing the style is not sufficient, so this is more like an issue than a PR (I would have submitted a proper PR, but it's not a quick job for someone unfamiliar with the code base, so I figured I'd try this first).

Make code blocks visible if JS is disabled

---

pages/docs/reference/using-gradle.md

- Source sets should be configured in `kotlin` block
- `compileKotlin2Js` is deprecated task, we need to use `compileKotlinJs`, but it is not important information, and may be confused for users

Actualize Kotlin/JS documentation for 1.3.70

---

pages/docs/reference/using-gradle.md

This was causing the rest of the page to render in the code block despite the closing backticks.

Add missing div end tags

---

pages/docs/reference/exceptions.md

1. Fix minor grammar issue to use "results in" instead of "results into".
2. Update linked blog post that no longer exists (using Wayback Machine).
3. Refer to the `@Throws` annotation in case readers want to explicitly declare exceptions for Java interop.

Update Exceptions reference page with more information

---

pages/docs/reference/object-declarations.md

It was very hard to look for explanations about initialization timing of instances which is declared with `object` keyword usage instead of `class` keyword since the explanations about 'lazy initialization' is located at bottom paragraph when excerpt the part of lazy init stuff.
Most of people who are looking for about initialization timing of object instances will excerpt the part of object class declaration paragraph, not to the end of the document.

Improve readability about object class init timing

---

pages/docs/reference/collection-operations.md

Grammar: "its" instead of "it's"

---

pages/docs/reference/idioms.md

[As suggested in the documentation](https://kotlinlang.org/docs/reference/coding-conventions.html#horizontal-whitespace), `if`s, `when`s, `for`s and `while`s should have a space before its opening parenthesis.

Add space between for and opening parenthesis

---

templates/pages/index.html

Removed link in "Studio 3.0" words, as it's essentially the same as the download link.

Removed link from Android Studio description

---

pages/docs/reference/coding-conventions.md

Factory functions can have same name as the abstract return type.

KT-37943 Use abstract return type as the name of factory function

---

data/oss-projects.yml

Since 4.0 release kotlintest has been renamed to [kotest](https://github.com/kotest/kotest) so changing that name here.

Rename kotlintest to kotest

---

pages/docs/reference/js-project-setup.md

More detailed description around webpack and `webpack.config.d`, DSL,
Add description about .yarnrc (mostly for defining custom registries)
Remove capitalizaion from "webpack" as per branding guideline (https://webpack.js.org/branding/)

Update webpack descriptions

---

pages/docs/reference/inline-classes.md

This commit adds the Kotlin Gradle DSL code snippet for "Enabling inline classes in Gradle"

Kotlin Gradle DSL snippet in inline-classes.md

---

pages/docs/reference/scope-functions.md

The advice causes confusion, as can be seen in:
- https://www.reddit.com/r/Kotlin/comments/g6oq6c/correct_usage_of_also_scope_function/
- https://stackoverflow.com/questions/61367281/whats-the-real-intention-behind-kotlins-also-scope-function

docs: remove controversial advice about 'also'

---

pages/docs/reference/delegation.md
pages/docs/reference/java-to-kotlin-interop.md

I got bit by this caveat today, and I was quite surprised to discover
that this behavior is actually by design, and is clearly documented
on the Java interop page -- I had never even considered looking there.
So I suggest adding a small call-out to the delegation page, so that
others may discover it if they run into the same issue.

Add mention of caveat with default interface methods in delegation page

---

pages/docs/reference/control-flow.md

In the current example:
Both branches are for x, it makes sense to use `when(x)` in it.
But if we switch the example to have two variables, then it makes sense to just use when without arguments.

Improve example for using when without an argument

---

pages/docs/tutorials/javascript/working-with-javascript.md

The link to the "lastest version" in the warning banner was broken without the .html

Fix broken link

---

pages/docs/tutorials/command-line.md

Removed MacPorts and Chocolatey as compiler distribution channels as agreed with Egor Tolstoy and Stas Erokhin

update: updated compiler distribution channels

---

pages/docs/reference/building-mpp-with-gradle.md

Updated metadata publishing for newer Gradle versions; removed Experimental notion.

update: gradle metadata publishing

---

pages/docs/reference/comparison-to-java.md

Non-private fields should be removed because we have them using @JvmField

Add short rationale to Java features that are not present in Kotlin

---

pages/docs/tutorials/spring-boot-restful.md

You either need to use the plugin or implicitly specify the version of `spring-boot-starter-web`

Missing spring dependency-management gradle plugin

---

pages/docs/reference/compiler-plugins.md

The `spring` compiler plugin in Maven depends on the `kotlin-maven-allopen` plugin dependency, so the documentation should mention it explicitly. Otherwise it may have been confusing since the Gradle dependency is called `kotlin-spring`, but there is no such artifact for Maven.

Update spring plugin description for Maven

---

pages/docs/reference/whatsnew14.md

removed the scenario with multiple Kotlin pods since it has issues and users may face an unexpected behaviour. At request of Svyatoslav Scherbina.

fix: removed the scenario with multiple Kotlin pods

---

pages/docs/reference/delegated-properties.md
pages/docs/reference/whatsnew14.md

Documentation for new features of delegated properties in 1.4:
- [KT-27729](https://youtrack.jetbrains.com/issue/KT-27729) Inherit `ReadWriteProperty` from `ReadOnlyProperty`
- [KT-26494](https://youtrack.jetbrains.com/issue/KT-26494) Create an interface with provideDelegate()
- [KT-8658](https://youtrack.jetbrains.com/issue/KT-8658) Add property delegates which call get/set on the given KProperty instance, e.g. a property reference

feat: delegated properties improvements in 1.4

---

pages/docs/reference/data-science-overview.md

ggplot is an R plugin, not a Python one. Fixed this in the text.

Fixed a mistake

---

data/_nav.yml
pages/docs/reference/compatibility-guide-14.md

Add the guide on incompatible changes for Kotlin 1.4 (by @zarechenskiy).
Fix styles, wording, punctuation.
For now, the guide will only be available by direct link. Will add to navigation upon the 1.4 release.

feat: compatibility guide for 1.4

---

pages/docs/reference/whatsnew14.md

Added What's new on using `break` and `continue` inside `when` expressions included in loops. 
Reviewed by Dmitrii Petrov, Thomas Ball, and Robert Leitch

feat: break and continue inside when in loops

---

pages/docs/reference/coding-conventions.md

add `fun` modifier in **coding conventions > modifiers order**.
https://youtrack.jetbrains.com/issue/KT-37781

feat: modifiers order in fun interface

---

pages/docs/reference/whatsnew14.md

* created a separate section about JVM IR back-end
* added links to sub-sections
* updated the title for trailing comma section (removed 'in enumerations')
* updated experimental for Alpha for IR back-ends; added info about Alpha to Kotlin Multiplatform

update: what's new in Kotlin 1.4 updates

---

data/_nav.yml
pages/docs/reference/evolution/migrating-multiplatform-project-to-14.md
pages/docs/reference/migrating-multiplatform-project-to-14.md
pages/docs/reference/whatsnew14.md

Add a new page: "Migrating Multiplatform Project to Kotlin 1.4"

Add "Migrating Multiplatform Project to Kotlin 1.4" guide

---

pages/eap/index.md
pages/releases.md
templates/inc/footer.html

Added a Kotlin Releases page with a general description of releases and details of latest releases. The page is included in the footer for now.

update: added Kotlin Releases page

---

pages/docs/reference/whatsnew14.md

Fixed a typo in `-Xjvm-default` in what's new in Kotlin 1.4.0
Thanks to Jinseong Jeon

fix: fixed a typo in -Xjvm-default 

---

pages/docs/reference/whatsnew14.md

Fixed a link to serialization guide and Java example in What's new in Kotlin 1.4.0

fix: fixed a link to serialization guide and Java example

---

pages/docs/reference/mpp-dsl-reference.md

Because they don't work in kotlin for strings.

Use quotation marks instead of apostrophes

---

pages/docs/tutorials/coroutines/coroutines-basic-jvm.md

This PR updates URL protocol (http -> https) in maven repository section.
Starting January 2020, JCenter only supports HTTPS user interface and REST API requests: https://jfrog.com/blog/secure-jcenter-with-https/.

doc: update protocol to https for jcenter repo

---

pages/docs/tutorials/native/using-command-line-compiler.md

Change "compileKotlin" to "compile Kotlin"

Missing space on Hello Kotlin/Native page

---

pages/docs/reference/serialization.md

According to the documentation of https://github.com/Kotlin/kotlinx.serialization, the version of the compiler plugin is still aligned with the Kotlin version. Additionally, version "1.0.0-RC" does not exist for the plugin. Therefore I assume that this is a mistake on the website.
I couldn't find any contribution guidelines so please let me know if there is anything else I should do.

Use the correct version for serialization compiler plugin on the serialization feature page

---

pages/docs/reference/compiler-plugins.md

One might wrongly understand that *kotlin-spring* is also wrapped on top of *no-arg*, which is not the case since it's a subplugin of *allopen*.
I'm not a native english speaker, so rephrasing suggestions are welcome.

chore: clarify kotlin-jpa plugin introduction

---

pages/docs/reference/whatsnew14.md

The code sample shown in [mixing named and positional arguments section](https://kotlinlang.org/docs/reference/whatsnew14.html#mixing-named-and-positional-arguments) is broken.
Updated the code with the following changes to fix it:
* Replace single quote with double quote for first parameter in `reformat` function
* Replace type of 3rd parameter `Character` to `kotlin.Char`

Fix broken sample in mixing named - position args section

---

pages/docs/reference/javascript-dce.md

Emphasize DCE application only for production assets
Emphasize that names used as arguments should be in terms of the generated JS code
Add note (+ warning) about how to keep whole packages / modules from elimination
Fixes https://youtrack.jetbrains.com/issue/KT-41188

Improve documentation for JS DCE

---

pages/docs/reference/js-project-setup.md

Add info about run being an alias for browserDevelopmentRun, nodeRun
Add information about difference between browserDevelopmentWebpack and browserProductionWebpack
Linkify DCE reference.
Fixes https://youtrack.jetbrains.com/issue/KT-41573

Add explanation around browserDevelopment vs browserProduction tasks + minor wording adjustments

---

pages/docs/reference/serialization.md

Fix incorrect link to serialization formats description

Fix incorrect link

---

pages/docs/reference/serialization.md

Missing version keyword for Gradle plugin

---

pages/docs/reference/java-interop.md

The existing link 404'd, as the file referenced has been moved.

Fix link for JvmAnnotationNames.kt

---

pages/docs/reference/compatibility-guide-14.md

Fixes this glitch and spacing between word and keyword.

Fix broken formatting and typo

---

pages/docs/reference/java-interop.md

The [official website](https://kotlinlang.org/docs/reference/java-interop.html#java-arrays) is correct, but the [markdown format](https://github.com/JetBrains/kotlin-web-site/blob/master/pages/docs/reference/java-interop.md#java-arrays) is broken.

Fix broken newline

---

pages/docs/tutorials/native/using-command-line-compiler.md

Dearest,
I just fixed it to get more impact in the search engines on the Web.
Regards.

Fix typo from SMT32 to STM32

---

pages/docs/reference/classes.md

Added missing `overrde` modifiers in [Classes and Inheritance](https://kotlinlang.org/docs/reference/classes.html) page

Added missing `override` modifiers

---

pages/docs/reference/coding-conventions.md

This PR addresses a few minor grammatical issues on the coding conventions page. Notably:
- The use of `the camel case` should either be `camel case` or `the camel case format`.
- Camel case starting with a capital letter, is commonly referred to as `UpperCamelCase` or `PascalCase`.
- Words separated by an underscore are commonly referred to as `snake_case`. The term `SCREAMING_SNAKE_CASE` is also sometimes used to describe `snake_case` with all caps.
I'm happy to take a more detailed look at some of the other pages; these were just ones we had noticed while using the Kotlin docs.
Thanks!

Coding Conventions Grammar Fixes

---

pages/docs/reference/using-gradle.md

I found the section about `Incremental compilation` in the docs.
It was only documented **how** to change the *default* setting. But it was not mention *what* the default setting is.
I found [this blog](https://blog.jetbrains.com/kotlin/2017/03/kotlin-1-1-1-is-out/) and thought it make sense to mention that it is enabled by default.
I also slightly updated the whole section to reflect more the *is is enabled by default, here is how to disable it* state 🙂 .

Update Incremental compilation section

---

pages/docs/reference/coding-conventions.md

Replace the previous snippet with a better example,
and specify that we're talking about the first line of the expression body.
See misinterpretation of the previous convention wording in this PR: https://github.com/LouisCAD/kotlin-libraries-playground/pull/68#discussion_r505742093

Improve the convention on expresion bodies

---

data/_nav.yml
pages/docs/tutorials/kotlin-for-py/annotations.md
pages/docs/tutorials/kotlin-for-py/classes.md
pages/docs/tutorials/kotlin-for-py/collections.md
pages/docs/tutorials/kotlin-for-py/compiling-and-running.md
pages/docs/tutorials/kotlin-for-py/conditionals.md
pages/docs/tutorials/kotlin-for-py/declaring-variables.md
pages/docs/tutorials/kotlin-for-py/documentation.md
pages/docs/tutorials/kotlin-for-py/exceptions.md
pages/docs/tutorials/kotlin-for-py/extension-functionsproperties.md
pages/docs/tutorials/kotlin-for-py/file-io.md
pages/docs/tutorials/kotlin-for-py/functional-programming.md
pages/docs/tutorials/kotlin-for-py/functions.md
pages/docs/tutorials/kotlin-for-py/generics.md
pages/docs/tutorials/kotlin-for-py/hello-world.md
pages/docs/tutorials/kotlin-for-py/inheritance.md
pages/docs/tutorials/kotlin-for-py/introduction.md
pages/docs/tutorials/kotlin-for-py/loops.md
pages/docs/tutorials/kotlin-for-py/member-references-and-reflection.md
pages/docs/tutorials/kotlin-for-py/null-safety.md
pages/docs/tutorials/kotlin-for-py/objects-and-companion-objects.md
pages/docs/tutorials/kotlin-for-py/packages-and-imports.md
pages/docs/tutorials/kotlin-for-py/primitive-data-types-and-their-limitations.md
pages/docs/tutorials/kotlin-for-py/scoped-resource-usage.md
pages/docs/tutorials/kotlin-for-py/strings.md
pages/docs/tutorials/kotlin-for-py/visibility-modifiers.md

Added stub pages for kotlin-for-py tutorial redirects.
Removed kotlin-for-py from navigation.

feat: Kotlin for py redirects

---

pages/docs/tutorials/command-line.md

Removing unnecessary args from the sample "Hello, world" - generates a warning that may confuse newbies

Fix args for main()

---

pages/docs/reference/coding-conventions.md

because "import ... as ..." can remain unknown when using "typealias".

import as instead of private typealias

---

pages/docs/reference/server-overview.md

It would be great to include http4k in the list of supported technologies for writing serverside apps in Kotlin.

Include http4k in the Kotlin for the Serverside

---

pages/docs/reference/java-interop.md

Three separate things in a single PR because they are small enough, and yet, I believe they are important.
First, the fact that `ClassName.javaClass` is *not* the same as `ClassName::class.java`.
Second, the difference between `Integer::class.java` and `Int::class.javaObjectType` (and the same similar primitive wrapper types).
Third, the difference between `Int::class.java` and `Int::class.javaObjectType` (the previous change to this section only explained the latter).

Java class and primitives

---

pages/docs/reference/control-flow.md

In the example it should be that `x+y` is odd.
In order to get to the `else` clause `x` must even and `y` must be odd, so `x+y` is odd. 
Example `x=2; y=1; x+y=3`.

Fix example

---

pages/docs/reference/functions.md

Fixed a grammatical error where there should be a comma between "In Kotlin" and "functions."

Added a comma between "In Kotlin" and "functions"

---

pages/docs/reference/functions.md

Make tailrec example function definition adhere to the ["Expression Body Formatting" from the coding conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#expression-body-formatting)

fix: adhere to coding conventions in tailrec example

---

pages/docs/reference/serialization.md

My main concern was that when using a field with a default value without `@Require` annotation, this field will not be added to the resulting JSON, so I fixed the code, and now running it will lead to the expected result. Also, I updated naming because in one place the variable was called `b` whereas in another place it was `str`.

Serialization docs fixed

---

pages/docs/reference/idioms.md

Fixed a typo in Line 406. 'toolwindow' to 'tool window'.

Update idioms.md Fixed a typo in line 406."toolwindow" to "tool window"

---

pages/docs/reference/data-classes.md

Clarify that the default `copy` implementation performs a shallow copy.
For people coming from some languages this might not be immediately clear (in C++ the copy constructor usually performs a deep copy, in python there are `copy` and `deepcopy`).
Perhaps the example code is not needed, but I decided to include it in the pull request.

update: clarify propagation of `copy` function

---

pages/docs/reference/javascript-dce.md

The idiomatic way to create JS binaries seems to be after the browser block instead of inside it.

Unify executable creation for the browser target

---

pages/docs/reference/evolution/kotlin-evolution.md

* Roman Elizarov replaces Andrey Breslav.

Updated Lead Language Designer on Kotlin Evolution page

---

docs/topics/roadmap.md

Fixed the Mac Catalyst item in postponed for K/N in the roadmap

fix: fixed the Mac Catalyst item in K/N in the roadmap

---

docs/topics/gradle.md

The content from https://github.com/JetBrains/kotlin-web-site/pull/2024 to WebHelp

update: add doc on Gradle config cache in WebHelp

---

docs/kr.tree
docs/topics/whatsnew1430.md

Transfer changes of https://github.com/JetBrains/kotlin-web-site/pull/2027 to WebHelp

update: what's new in Kotlin 1.4.30 to WebHelp

---

pages/docs/reference/exceptions.md
pages/docs/reference/inline-functions.md
pages/docs/reference/java-to-kotlin-interop.md
pages/docs/reference/typecasts.md

Fix formatting to adhere to https://kotlinlang.org/docs/reference/coding-conventions.html#formatting-control-flow-statements

chore: fix formatting of control flow statements

---

data/_nav.yml
pages/docs/reference/basic-syntax.md

After we changed the target page title in the merge request #1931 (based on the discussion here: https://discuss.kotlinlang.org/t/property-vs-field/8179/10?u=yvolk ), I noticed that we forgot to change titles of the links to that page.
The target page is: https://kotlinlang.org/docs/reference/properties.html

Fix link titles referring to the "Properties" page

---

pages/docs/tutorials/native/using-gradle.md

Result of `gradle nativeBinaries` is actually `build/bin/native` and not `build/native/bin`. This pull request changes that.

Fix inverted directory path in documentation

---

pages/docs/reference/serialization.md

Made some changes to https://kotlinlang.org/docs/reference/serialization.html – since the introduction of Gradle metadata, artifacts aren't imported based on their platform suffix anymore, but only in common code. This reflects that in the instructions (and fixes another incorrect artifact description).

Changes in serialization artifact naming scheme

---

pages/docs/reference/classes.md

fix parameter `i` never used.
https://pl.kotl.in/OBRfEPLzs

fix parameter `i` never used.

---

docs/cfg/buildprofiles.xml
docs/topics/coroutines-overview.md
docs/topics/lambdas.md
docs/topics/whatsnew11.md

fixed for correct work of redirects

update: rename basics.md to coroutines-basics.md

---

docs/topics/native/native-libraries.md

This script is deprecated in https://github.com/JetBrains/kotlin-native/pull/4639

Don't use Native kotlinc script in native-libraries.md

---

docs/topics/coding-conventions.md

Fix typo in coding conventions documentation

---

docs/topics/equality.md

https://kotlinlang.org/docs/(https://en.wikipedia.org/wiki/IEEE_754)/
https://en.wikipedia.org/wiki/IEEE_754

fix link text(IEEE 754) 404 Not Found.

---

docs/topics/classes.md

Fix for https://youtrack.jetbrains.com/issue/KT-33201

fix: KT-33201 rewrite unusable sample of secondary constructor

---

docs/topics/operator-overloading.md

Fix for https://youtrack.jetbrains.com/issue/KT-40021

fix: KT-40021 `operator` modifier is not required when overriding operators

---

docs/topics/this-expressions.md

Correcting the wrong code example indentation in this-expressions document.

fix: correct the wrong indentation in this-exp doc

---

docs/topics/native/native-overview.md

* Remove explicit enumeration of targets. It is not actionable (doesn't answer the question of how to use them) and clutters the list. It will become even more cluttered when we add 4 more targets for Apple Silicon.
* Instead, add a link to the list of Gradle targets because it's the only "officially supported" way of using the compiler.
* Explicitly mention Android NDK to avoid confusion with usual Android development.
* Remove WebAssembly mention because it is going to be deprecated.

Update list of native target platforms

---

docs/topics/control-flow.md

The sample uses `x` for both odd and even checks
where as the even check should be for `y`

Fix sample in when 'else if' documentation

---

docs/topics/sealed-classes.md

The following link text is invalid.
https://kotlinlang.org/docs/sealed-classes.html#additional-location-the-same-package
https://github.com/Kotlin/kotlinx.coroutines/blob/master/visibility-modifiers.html
https://kotlinlang.org/docs/visibility-modifiers.html

Fix linkText(visibility) 404 not found

---

docs/topics/sealed-classes.md
docs/topics/whatsnew1430.md

Doc update reflecting the sealed class changes in 1.5.0:
- Sealed interfaces are stable
- package-wide sealed hierarchies by default
- `when` on `expect sealed` classes is not exhaustive

update: stable sealed interfaces and inheritance

---

docs/topics/fun-interfaces.md

Restore the previously removed example of `suspend fun` in `fun interface` from [this PR](https://github.com/JetBrains/kotlin-web-site/pull/1756/files#diff-b6dc78a878c5aca3482e9b1a842f2ed509f67f6fa717e1a18db3c58f1cf12068R89-R115) because it becomes valid in 1.5 (issue: [KT-44787](https://youtrack.jetbrains.com/issue/KT-44787))

Add example of suspend fun in fun interface

---

docs/topics/gradle.md

[KT-44361 Gradle: deprecate options includeRuntime, noStdlib, noReflect](https://youtrack.jetbrains.com/issue/KT-44361)

update: KT-44361 deprecate Gradle options noStdlib, noReflect

---

docs/topics/object-declarations.md

Doc improvement per feedback in https://youtrack.jetbrains.com/issue/KT-45522

fix: KT-45522 Define an object expression vs. anonymous type

---

docs/topics/data-science-overview.md

Adding londogard-nlp-toolkit.
It's also available through kotlin jupyter notebook via `%use londogard-nlp-toolkit` (see: https://github.com/Kotlin/kotlin-jupyter#list-of-supported-libraries)

Adding londogard-nlp-toolkit

---

docs/topics/generics.md

If I copy and paste the example, I get the exception
```
'operator' modifier is required on 'set' in 'Array'
```
To have a running example, the operator keyword needs to be added.

Add operator keyword to Array<T> class for generics example

---

docs/topics/collection-parts.md

Typo: missing 'd'

---

data/releases.yml
docs/topics/js/js-project-setup.md
docs/topics/releases.md
docs/v.list

- Add 1.5.10 to the releases table
- Update version variables
- K/JS: Add instruction on fallback to webpack 4 (removed previously due to a bug in 1.5.0) 
cc @ilgonmic @dromanov-jb

update: 1.5.10 doc update

---

docs/topics/coding-conventions.md

`value` was introduced in `1.5` and because is very related with `inline` it seems reasonable to have the same priority.

Add `value` in Modifiers order

---

docs/topics/fun-interfaces.md

The current text creates an impression that functional interfaces should be preferred to typealises, since they are more flexible, which is not really the case. Clarification is added to explain in which circumstances the use of functional interfaces is warranted, and in which a plain functional type shall be used.

Clarify fun interfaces vs. type aliases section on which one to use

---

docs/topics/jvm/java-interop.md

There doesn't seem to be a reason why we're capitalizing this on https://kotlinlang.org/docs/java-interop.html.

De-capitalize "interoperability"

---

docs/topics/js/js-ir-compiler.md

As per @ilgonmic's recommendation, and as pointed out by @sashache.

Add Kotlin2JsCompile snippet to enable lazy property init for K/JS

---

docs/topics/basic-types.md

In the section unsigned types of the basic types chapter there is a line that "Unsigned types are implemented using feature that's not yet stable, namely inline classes.".
I removed it because inline classes are stable as of Kotlin 1.5.10

Unsigned types: removed Inline Class warning

---

.github/workflows/validate-user-groups-data.yml
data/schemas/user-groups.json

Issue: https://youtrack.jetbrains.com/issue/KT-47068
It helps ensuring that the data is valid to some extent, e.g. helps
avoid typos in field names or missing fields.
After this commit, it's possible to e.g. point IntelliJ IDEA to use
this schema when editing `data/user-groups.yml` and the IDE will show
warnings in case something's wrong. The second commit also adds a
GitHub action that validates the data on each PR and push to master.
I removed a required property of some user group and checked how it's reported:
via command line:
```
> jsonschema -i <(yq eval --tojson -j data/user-groups.yml) data/schemas/user-groups.json
{'name': 'Athens Kotlin User Group', 'url': 'https://www.meetup.com/Kotlin-Athens/'}: 'country' is a required property
```
in IntelliJ IDEA:
in GitHub actions …

KT-47068: Add schema for data/user-groups.yml

---

data/schemas/user-groups.json
data/user-groups.yml

Issue: https://youtrack.jetbrains.com/issue/KT-47068
After this change, it's possible to specify positions for each user
group and it's recommended to do for newly added groups. Backfill for
existing user groups will be done in a separate change.
Names of the new fields were inspired by what's already in
`kotlinconf.yml`, for consistency.
Tricity Kotlin User Group was augmented with position as an example.
FYI @TinaNEs @zoobestik @meilalina (frequent committers around KUGs data)

KT-47068: Allow specifying positions for user groups

---

docs/topics/lombok.md

The rest of the Kotlin documentation uses the built-in `PluginDependencySpec.kotlin()` method to add Kotlin plugins the lombok plugin should do this too.
Also it's more common to not place a space between the `id` and the arguments as seen in the official Gradle plugin portal

Improve Gradle Kotlin example for lombok plugin

---

docs/topics/properties.md

In the Delegated Properties section, change `to` -> `so`

Fix typo in Properties doc page

---

docs/topics/extensions.md

In the example code in section **Declaring extensions as members**, `printConnectionString()` does not accept any arguments.

Fix extension method call in example

---

docs/topics/extensions.md

`protected` members of the receiver type are not accessible either, to an extension method declared outside its receiver type

Update Note on Visibilty section of extensions

---

data/universities.yml

https://youtrack.jetbrains.com/issue/KTL-262
There were two "Universidad Tecnológica Nacional" on the map.
I've leaved the one with the correct place in Argentina.

KTL-262 Error on the map showing universities teaching Kotlin

---

docs/topics/native/native-c-interop.md

Remove instruction to use `initRuntimeIfNeeded` as said in comment in [KT-44283](https://youtrack.jetbrains.com/issue/KT-44283)

feat: KT-44283 initRuntimeIfNeeded no longer needed

---

docs/topics/generics.md

While reading the generics, I noticed that Joshua Bloch was written as Joshua Block.
In the links provided to the book like: https://www.oracle.com/java/technologies/effectivejava.html we can check the name is Joshua Bloch.
Effective Java
Programming Language Guide
By Joshua Bloch; Forward By Guy L.Steele, Jr.
May 2001

Update generics for fixing Joshua Bloch name

---

docs/topics/mpp/mpp-share-on-platforms.md
docs/topics/native/native-improving-compilation-time.md

Explain how to use new arm64 simulator targets with existing [target shortcuts](https://kotlinlang.org/docs/mpp-share-on-platforms.html#use-target-shortcuts).

feat: target shortcuts and apple silicon

---

docs/topics/classes.md

The current documentation has no simple example for abstract base classes and instead jumps directly into the syntax for overriding an open method in an open class to convert it to abstract in an inheriting classes.
This can confuse users experience for users new to the language especially since the example showed a rectangle class overriding and abstracting a method in the Polygon class.
This change introduces
1. A simple example for an abstract base class
2. A modified version of overriding and converting to abstract an open method in an open class.
This provides a more simple example to abstract classes for newer users.

Add a simple example of abstract classes

---

docs/topics/compatibility-guide-13.md
docs/topics/compatibility-guide-15.md

update: compatibility guide updated with a note about switching to the old jvm backend

Added info on jvm backends to compatibility guide

---

docs/topics/js/js-debugging.md

Fix two links on JS debug page:
- Better link to IDEA doc on JS debugging: [KT-48548](https://youtrack.jetbrains.com/issue/KT-48548)
- Remove link to coroutines debugger (unsupported for JS): (KT-48549)[https://youtrack.jetbrains.com/issue/KT-48549]

fix: links in js-debugging.md

---

docs/topics/collections-overview.md

This PR updates the examples given for a list and a set in this article: https://kotlinlang.org/docs/collections-overview.html
I think that an alphabet is a bad example for a set, because an alphabet is ordered. We even have the term _alphabetical order_. So I changed it to a lottery ticket.
I also changed the example for list, because while a sentence is a collection of words, it also has spaces and punctuation, so I think that example was unclear. I used the example of a telephone number instead, which is just a collection of ordered numbers.
I'm happy to change the examples here,  these were just the better examples I thought of. The main thing that I think should change is the usage of an alphabet as an example of a set.

Update examples for list and set

---

docs/topics/lambdas.md

The "**Anonymous function parameters**" was ambiguous:  
I first thought it meant *parameters of anonymous functions*.

Clarify an ambiguous note about anonymous functions

---

kotlin-features/concise.md

The code below doesn't actually generate setters, because it uses `val`:
https://pl.kotl.in/puHlJh3AI
If I try to use setters: 
```
val c = Customer("Alice", "alice@bob.com", "Jetbrains")
c.setName("Bob")
c.name = "Bob"
```
I get errors:
```
Unresolved reference: setName
Val cannot be reassigned
```

Remove dataclass comment about generating setters

---

docs/topics/mpp/multiplatform-library.md

This fixes an issue: https://kotlinlang.slack.com/archives/C0B8L3U69/p1628876549226400
The issue is likely cause by the project being created by IDEA, which produces
```
js(LEGACY) {
browser {
commonWebpackConfig {
cssSupport.enabled = true
}
}
}
```
in build.gradle.kts. Note that this uses a `browser` instead of `nodejs` target. Because of this, running the tests as described in the document (before this commit) results in failure:
```
ReferenceError: Buffer is not defined
```
This commit fixes that issue by replacing the used Node API for a browser API: `btoa`.

Replace dependency on Node Buffer API

---

docs/topics/control-flow.md
docs/topics/exceptions.md

Following [api](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/parse-int.html) parseInt is deprecated and .toInt() should be used in place

Change parseInt (deprecated) to .toInt()

---

data/universities.yml

It was already added to the "Kotlin Universities List" spreadsheet.

Add Gdansk University of Technology course to the map

---

package.json
webpack.config.js
yarn.lock

Dependabot [has found](https://github.com/JetBrains/kotlin-web-site/security/dependabot/yarn.lock/set-value/open) that "set-value" before 4.0.1 version is vulnerable.
So, "set-value" is used by "svg-transform-loader" which is not updated yet. Moreover, the package has [many issues](https://github.com/JetBrains/svg-mixer/pulls) and looks abandoned.
But we use only the "encode-query" part from "svg-transform-loader" in the webpack pipline and how I undersand, it does nothing because we don't have such URLs.

KTL-520 Upgrade "set-value" dependency to non-vulnerable version

---

docs/topics/classes.md

Mutation to MutableLists should be done not by reassigning the property, but by modifying the list.  Otherwise, you can get nasty ambiguity errors with e.g. +=.

MutableLists should be stored in vals, not vars

---

docs/topics/coding-conventions.md

As there is no "Settings" section on MacOS, mention that on this operating system people should go to the Preferences instead

Clarify the navigation to code conventions

---

docs/topics/mpp/mpp-supported-platforms.md
docs/topics/native/native-improving-compilation-time.md

- compiler caches by default for `linuxX64` and `iosArm64`
- Windows as a cross-compilation target

update: K/N compiler caches and Windows cross compilation

---

docs/topics/kmm/kmm-add-dependencies.md
docs/topics/kmm/kmm-concurrency-and-coroutines.md
docs/topics/kmm/kmm-concurrency-overview.md
docs/topics/kmm/kmm-concurrent-mutability.md
docs/topics/kmm/kmm-configure-sqldelight-for-data-storage.md
docs/topics/kmm/kmm-connect-to-platform-specific-apis.md
docs/topics/kmm/kmm-create-first-app.md
docs/topics/kmm/kmm-getting-started.md
docs/topics/kmm/kmm-integrate-in-existing-app.md
docs/topics/kmm/kmm-introduce-your-team.md
docs/topics/kmm/kmm-plugin-releases.md
docs/topics/kmm/kmm-publish-apps.md
docs/topics/kmm/kmm-samples.md
docs/topics/kmm/kmm-setup.md
docs/topics/kmm/kmm-understand-project-structure.md
docs/topics/kmm/kmm-use-ktor-for-networking.md
docs/topics/whats-new-in-kotlin-for-kmm.md

Old auxiliay IDs on KMM pages break build with new Supernova

fix: remove aux ids from KMM topics

---

docs/topics/idioms.md

`foo` is composed of a single assignment statement, and the `result` value is never used.
I think the intent was to demonstrate with a single-expression function.

Fix "if expression" idiom example returning Unit

---

docs/topics/native/native-objc-interop.md

```kotlin
// your project
package a
class A // will be mapped to A in Swift in a 
package b
class A // will be mapped to A_ in Swift
// dependency x
package a
class A // will be mapped to XA in Swift
```
This algorithm is not (yet) stable and could change between releases.

Add note about name conflicts in the same framework

---

docs/topics/js/js-project-setup.md

Should be `commonWebpackConfig` instead of `commonWbpackConfig`.

fix: typo - commonWebpackConfig

---

docs/topics/gradle.md

The `matching` method unfortunately causes all tasks to be "realized", which impacts the builds where these tasks don't need to be run for the given module.
This commit uses `withType()` along with `configureEach` to avoid this issue.
@melix Did I do this right?

Use configuration avoidance APIs

---

docs/topics/jvm/jvm-records.md

The JVM records tutorial links to the Java documentation for `java.lang.Record`, but that link no longer works. This change updates the link to the current JDK 16 documentation.
(This change does not update the link to point to newer JDK versions' documentation, so that it keeps with the original intention of this page. JVM records came out in JDK 16.)

Fix broken link to java.lang.Record documentation

---

docs/topics/js/js-project-setup.md
docs/topics/whatsnew16.md

The current example syntax is not working.
Got the right one from: https://youtrack.jetbrains.com/issue/KT-39106

fixed Kotlin DSL example for pre-installed Node.js

---

docs/topics/whatsnew16.md

Hello! At https://kotlinlang.org/docs/whatsnew16.html
There is a link that leads to a blog post. It is not valid at the moment. I've fixed that.

Corrected the broken link to the blog post.

---

docs/topics/kotlin-evolution.md

Feature release now happen twice a year so 2 cycles are ~1 year
https://blog.jetbrains.com/kotlin/2020/10/new-release-cadence-for-kotlin-and-the-intellij-kotlin-plugin

Adapt `Compatibility flags` section to new release cadence

---

static/js/components/kto-link.scss
static/js/page/index/kotlin-news-section.scss

https://youtrack.jetbrains.com/issue/KTL-577
https://branch-ktl-577-fix-link-hover-state.kotlin-web-site.labs.jb.gg 
Reverts [this chages](https://github.com/JetBrains/kotlin-web-site/pull/2573/commits/0408cfc820a612ee3768b284fd8472fda18f9ebd)

KTL-577 Kotlinlang - links on the main page lost hover state

---

docs/topics/properties.md

I thought the width times the height of a rectangle was its area, and that a square was a rectangle with equal sides. And that the square of a number was it times itself.
But this could be a localization concept I am not aware of.

Use the term "area" instead of "square"

---

docs/topics/ksp/ksp-overview.md

It is officially released now https://github.com/square/moshi/blob/master/CHANGELOG.md#version-1130

Update Moshi support status

---

docs/topics/kotlin-evolution.md

* forgot to update this part when new API support flow in 1.6 was announced

update: new kotlin support cycle

---

docs/topics/jvm/jvm-records.md

The usage example currently shows the Kotlin property for a record being accessed at the class-level (as if it were static) instead of at the object-level. This change fixes that typo so that the Kotlin property is called on the object-level, since the properties would be at the object-level.

Fix JVM record code showing Kotlin property usage

---

docs/topics/js/js-ir-compiler.md

move `binaries` to be in `js {}`

---

docs/topics/collection-transformations.md

Collections and arrays are different concepts in Kotlin, writing `collection (array)` gives the reader the implication that collections and arrays are one and the same.
Updated it to `collection (or array)` for better reflection.

Update zip() transformation function description

---

docs/topics/typecasts.md

The original text talks about a negative check triggering a cast on on example, then mentions "it" is also triggered on `&&` or `||`, but in this case, "it" can be either a regular or a negative check. The code example clarifies it, but rewriting in these lines may avoid the confusion in the first place, what do you think?
---
(this is my first Kotlin/docs PR 🙂; it seems to abide to the [guidelines](https://docs.google.com/document/d/1mUuxK4xwzs3jtDGoJ5_zwYLaSEl13g_SuhODdFuh2Dc/edit#heading=h.2a2byea1lufz), happy to amend/improve if needed! 🙇)

Clarify that specific checks on the left side are required to cast an expression on the right side of `&&` or `||`

---

docs/topics/coding-conventions.md

The documentation example explicitly talks about how to document return types but the code examples fail to include any return type when one should exist.  Just hoping to clean that up and avoid any confusion

Add return type to the Documentation Comment section examples

---

docs/topics/properties.md

The current docs state what the limitations are and the ability to use constants in annotations, but nothing is said about what actually happens to them in regular code usages (which I think are much common). Having an outright statement in the docs would settle confusion that can arise from outdated/unclear YouTrack Issues and posts in Kotlin Discussions that slightly contradict.

Add note about inlining of const vals

---

docs/topics/control-flow.md

By the way, I found it a little confusing that we declare that "If is an expression", and then show an example where it is used as a statement. Probably it's worth explaining that it can be used in both ways.
For example, compare that with `when`:
> `when` can be used either as an expression or as a statement.

Fix a typo in "Conditions and loops"

---

kotlin-features/safe.md

Hello, I noticed the indentation in the "safe" feature tab is a little off, it should be better like this

fix: indentation in safe.md

---

docs/topics/properties.md

removed repeated `from the initializer` from the getters and setters description and added a comment to the getter custom accessor example to demonstrate the aforementioned optional type.

chore: better property getters description

---

docs/topics/gradle.md

Can revert this after https://youtrack.jetbrains.com/issue/KT-50115 is fixed. The task for it https://youtrack.jetbrains.com/issue/KT-51104

fix: remove part about java extension until KT-50115 is fixed

---

docs/topics/kmm/kmm-samples.md

The praxis base project has a base project structure with minimal features.
1. Ktor APIs to fetch Github Trending Repos
2. Integration with SQLdelight for caching these repositories locally.
3. Used flows to listen to changes in trending repositories locally.
We are planning to add more platform targets in the coming days!

update: add more samples to kmm-samples.md

---

docs/topics/jvm/java-to-kotlin-collections-guide.md

This makes the 2nd level headings consistent with each other (L20: "Operations that are the same in Java and Kotlin﻿" and L92: "Operations that don't exist in Java's standard library") and fixes the grammar of the expression.

fix: missing article on heading

---

docs/topics/sealed-classes.md

the following reference `file` and more clear.
```kotlin
is FileReadError -> { println("Error while reading file ${e.file}") }
```

fix: match the function value parameter

---

docs/topics/keyword-reference.md

fix: operator precedence link to kotlin grammar

---

docs/topics/fun-interfaces.md

* update: single kotlin eap channel (#2823)
* update: added a note for the Gradle task (#2811)
* update: added a warning and details for the embedAndSignAppleFrameworkForXcode task
* update: add info about callable references to SAM interfaces
* fix: more migration to fun interfaces higher
Co-authored-by: Danil Pavlov <danil.pavlov@jetbrains.com>

Doc 1 6 20 method references to fun interface constructors (#2838)

---

docs/topics/native/native-cocoapods.md

Fixes broken link to `CocoapodsExtension.kt`.

fix: link to CocoapodsExtension.kt

---

docs/topics/jvm/jvm-spring-boot-restful.md

This tutorial works fine with select/find queries, but gives "relation "messages" does not exist" error during persisting the messages. This is due to the relation name being case-sensitive e.g. "MESSAGES" vs "messages"
`findMessages` uses implicit query  `@Query("select * from messages")`("messages") and therefore works.
`db.save(message)` uses the generated query from `SimpleJdbcRepository`("MESSAGES") and therefore fails.
This tutorial https://dba.stackexchange.com/questions/192897/postgres-relation-does-not-exist-error
To be transparent, I tested this tutorial on Postgres database running locally, and not on the in-memory H2.

Use lower-case relation name for the data class

---

docs/topics/whatsnew1620.md

Clarifies issues that were causing problems for users using the `-Xir-per-module` flag with this new behavior. Text already validated by @anton-bannykh.

Clarifying paragraph on per-module & lazy initialization combination

---

docs/topics/delegated-properties.md

"Translation rules for delegated properties" and "Providing a delegate" are not subsections of "Property delegate requirements"

fix: paragraph nesting in delegated-properties.md

---

docs/topics/this-expressions.md

The type of `c` and `c1` is mentioned in their comments and this just makes it explicit for `d` as well.

Clarify that the type of "d" is a string

---

docs/topics/js/js-project-setup.md

Documents https://youtrack.jetbrains.com/issue/KT-51414/Allow-set-up-environment-variables-for-JS-tests

Add paragraph on node.js test env variables

---

docs/topics/lambdas.md

```kotlin
map.forEach { key, value -> ... }  // (1)
map.forEach { (key, value) -> ... } // (2)
```
> ... the first line uses Java 8 Map.forEach default method, while the second one Kotlin's extension.
>
> https://youtrack.jetbrains.com/issue/KTIJ-7519

Replace `Map.forEach` with Kotlin's `forEach`

---

docs/topics/fun-interfaces.md

It may not be evident to the reader that the type aliases brought by this section talk about aliasing a functional type.

Add example of typealias to "fun interfaces vs. type aliases" section

---

docs/topics/releases.md
docs/topics/whatsnew17.md

Add info about migration to 1.7.0

update: add compatibility guide links for Kotlin 1.7.0

---

docs/topics/jvm/java-to-kotlin-interop.md
docs/topics/whatsnew1620.md

The API reference was updated after the 1.6.20 release.

update: add links to api reference on @JvmDefaultWithCompatibility

---

docs/topics/native/mapping-strings-from-c.md

In kotlin `1.7.0` the extension function `ByteArray. stringFromUtf8()` referenced in
the `C interop` tutorial is not available anymore. The invalid references are replaced
with `ByteArray.decodeToString()`.

Fix invalid C string conversion references

---

docs/topics/inline-classes.md

Saying "must be `final`" could be misinterpreted as "needs `final` modifier in order to work". Since `final` is the default, I propose rephrasing it to show that finality is _always_ the case.

Rephrase `final` requirement for inline classes

---

docs/topics/multiplatform/multiplatform-library.md

org.junit is not a direct dependency of the sample project

Use kotlin.test.Test in jvmTest sample for multiplatform library tutorial

---

redirects/api.yml

https://youtrack.jetbrains.com/issue/KTL-764/kotlinResult-extension-function-sample-provides-kotlinCollections-samples
It is just a quick fix, and then we will review all redirects to find and remove redundant.

KTL-764 kotlin.Result extension function sample provides kotlin.Collections samples

---

docs/topics/faq.md

> 'compileJava' task (current target is 16) and 'compileKotlin' task (current target is 1.6) jvm target compatibility should be set to the same Java version.
> w: JVM target 1.6 is deprecated and will be removed in a future release. Please migrate to JVM target 1.8 or above
Historically, Kotlin had supported compiling all the way down to JVM 1.6 targets, and you can still find references to this on [StackOverflow](https://stackoverflow.com/questions/48036758/is-the-jdk-required-for-kotlin).
Since this target is deprecated, it makes sense to state the requirement of targeting Java 8 compatible code explicitly.

Explicitly state lack of support for bytecode < Java 8

---

docs/topics/multiplatform/multiplatform-build-native-binaries.md

According to the replacement of the deprecated API made in 1.7.0. See https://kotlinlang.org/docs/whatsnew17.html#changes-in-compile-tasks for details.

Update of destination directory configuration sample

---

docs/topics/js/js-get-started.md
docs/topics/kotlin-and-ci.md
docs/topics/native/mapping-function-pointers-from-c.md
docs/topics/native/mapping-strings-from-c.md
docs/topics/native/mapping-struct-union-types-from-c.md
docs/topics/native/native-get-started.md
docs/topics/no-arg-plugin.md

fix for minor mistakes:
- missing bracket
- incorrect API doc URL
- incorrect words (maybe copied & pasted from other page)

fix for minor mistakes

---

docs/topics/js/js-project-setup.md

Spent about an hour confused by this.

Clarify that webpack configs need to use `config`

---

docs/topics/sealed-classes.md

The final branch was missing an `is` prior to the matched case.

Fix typo in sealed classes `when` example

---

docs/topics/classes.md

The Kotlin [coding conventions](https://kotlinlang.org/docs/coding-conventions.html#horizontal-whitespace) says "Do not put a space before an opening parenthesis in a primary constructor declaration, method declaration or method call.

Removed space before opening parenthesis

---

docs/topics/gradle.md

The Kotlin toolchain feature also effectively sets the toolchain for Java, so it also acts as if the following has been applied to the project as well: https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming.
This means the toolchain applied in the Kotlin extension is applied to Java tasks as well. This fact is included in the Kotlin Gradle Plugin KDoc, and is important enough that I think it should be included in the website docs as well.
The KGP doc for `jvmToolchain` option says it "Configures Java toolchain both for Kotlin JVM and Java tasks."

Add a note about toolchains applying to Java tasks

---

docs/topics/jvm/java-to-kotlin-interop.md

const is in Java a keyword and therefore not a valid identifier.
So the example Java Code 
```java
int const = Obj.CONST;
int max = ExampleKt.MAX;
int version = C.VERSION;
```
about using const properties in Java wouldn't compile.
I propose renaming the variable const to constant.

Replace non-Java-Identifier const by constant

---

docs/topics/home.xml

Hey @koshachy,
let's remove this icon from the "command line compiler" block.

chore: remove unnecessary icon of the home page

---

docs/topics/js/js-project-setup.md

Checked in a new project to see what the real name is.

Fix typo in distribution directory name

---

.github/workflows/qodana-code-quality-check.yml
qodana.yaml

https://youtrack.jetbrains.com/issue/KTL-824/Qodana-Action-on-GitHub-scan-failed

KTL-824 Qodana Action on GitHub: scan failed

---

docs/topics/jvm/jvm-spring-boot-restful.md

This is a minor modification to the url for the `Spring Initializr` link, near the top of the associated tutorial.
The previous version (2.6.0) is no longer offered, so the Initializr website shows a warning and switches to the latest 2.6.x release (currently 2.6.11).

Update version of Spring Boot in tutorial to 2.7.3

---

docs/topics/lombok.md

Clarify the instructions for working with the Lombok compiler plugin and Lombok config file.

fix: correct wording for lombok compiler plugin

---

docs/topics/jvm/java-to-kotlin-nullability-guide.md

Fix "Data class must have at least one primary constructor parameter" compilation error for an example with data classes.

Fix compilation error in java-to-kotlin-nullability-guide.md

---

.gitmodules

https://youtrack.jetbrains.com/issue/KTL-869/Set-up-Lincheck-as-a-part-of-Docs-build
https://branch-ktl-869-remove-lincheck-submodule.kotlin-web-site.labs.jb.gg/docs/lincheck-guide.html

KTL-869 Set up Lincheck as a part of Docs build

---

docs/topics/ksp/ksp-overview.md

Officially supported as of 4.14 – https://github.com/bumptech/glide/issues/4492

Update Glide support for KSP

---

docs/topics/null-safety.md

The subheading to Tony Hoare's apologies and retractions was recently removed. (see https://en.wikipedia.org/w/index.php?title=Tony_Hoare&diff=1114844581&oldid=1108470526)

fix: fixed dead link

---

docs/topics/jvm/jvm-spring-boot-restful.md

Based on the code repository, the table name should be in uppercase in order for H2 to found the table on the H2 database.

fix: use the right case on table name when adding database support

---

docs/topics/multiplatform/multiplatform-full-stack-app.md

I ran into compile errors following these steps of the [multiplatform full stack app tutorial](https://kotlinlang.org/docs/multiplatform-full-stack-app.html#serve-html-and-javascript-files-from-ktor):
```
> Task :compileKotlinJvm
e: file:///<path>/jvm-js-fullstack/src/jvmMain/kotlin/Server.kt:34:7 Unresolved reference: static
e: file:///<path>/jvm-js-fullstack/src/jvmMain/kotlin/Server.kt:35:9 Unresolved reference: resources
> Task :compileKotlinJvm FAILED
...
```
I checked the [Kotr docs on static files](https://ktor.io/docs/serving-static-content.html) and noticed they `import io.ktor.server.http.content.*` . 
After adding this the compile errors were gone and the html page loads as expected :)

Add `import io.ktor.server.http.content.*` to `Server.kt`

---

.teamcity/builds/apiReferences/kotlinx/datetime/KotlinxDatetimeBuildApiReference.kt

https://youtrack.jetbrains.com/issue/KTL-841/Publish-documentation-for-kotlinx-datetime
The problem:
There is SNAPSHOT word in the reference [header](https://staging.kotlinlang.org/api/kotlinx-datetime/).
We remove this word for the rest of the references, but that script doesn't fit this reference because of using versionSuffix.
The result:

KTL-841 Fix kotlinx-datetime version in header

---

docs/topics/collections-overview.md

https://youtrack.jetbrains.com/issue/KT-51602/Web-feedback-from-Overview-httpskotlinlangorgdocscollections-overviewhtml

fix: default implementation of MutableList is ArrayList

---

docs/topics/multiplatform/multiplatform-full-stack-app.md

Please see the resolution in https://youtrack.jetbrains.com/issue/KTOR-453 Removes the definition of `endpoint` and usage in the API code sample.

Removes `endpoint` as related YouTrack incident was resolved

---

docs/topics/native/native-c-interop.md

* [KT-54001](https://youtrack.jetbrains.com/issue/KT-54001/Kotlin-Native-support-header-exclusion-in-cinterop-def-files)

feat: new header filter

---

docs/topics/gradle/gradle-compilation-and-caches.md
docs/topics/gradle/gradle-compiler-options.md
docs/topics/opt-in-requirements.md
docs/topics/whatsnew1620.md

Manual copy of the https://github.com/JetBrains/kotlin-web-site/pull/3187/files because those changes were made before splitting the Gradle page into several.

update: add about usage of freeCompilerArgs in KGP

---

package.json
yarn.lock

https://youtrack.jetbrains.com/issue/KTL-937/Global-Header-no-way-to-navigate-on-the-landscape-format-on-mobile

KTL-937 Global Header: no way to navigate on the landscape format on mobile

---

docs/topics/multiplatform/multiplatform.md

Discussed with @danil-pavlov.
Currently this link points to the general Get started with Kotlin Multiplatform page when it should point to the Get started with Kotlin Multiplatform Mobile page.

Correct Get started with KMM link in Multiplatform overview

---

docs/topics/gradle/gradle-configure-project.md

Doing this again (I already did in https://github.com/JetBrains/kotlin-web-site/pull/3335). Somehow this text block appeared again when merging the release branch

fix: delete "Set custom JDK home" again

---

docs/topics/releases.md

Update Kotlin releases page with proper link to 1.8 compatibility guide

Fix link to 1.8 compatibility guide

---

package.json
static/js/com/dropdown/index.js
static/js/com/dropdown/view.twig
webpack.config.js
yarn.lock

https://youtrack.jetbrains.com/issue/KTL-949/Fix-prototype-pollution-in-webpack-loader-utils
This change aims to fix [this issue](https://github.com/JetBrains/kotlin-web-site/security/dependabot/24) by removing outdated packages.

KTL-949 Fix prototype pollution in webpack loader-utils

---

docs/v.list

There is no KSP version 1.0.7, only 1.0.8, for Kotlin 1.8.0 https://github.com/google/ksp/releases

Update kspVersion to 1.0.8

---

docs/topics/whatsnew18.md

To alleviate any confusion on nesting of the new CSS configuration settings.

Expand cssSupport snippets

---

docs/topics/js/js-project-setup.md

`binaries.executable` is a configuration on the `KotlinJsTargetDsl`, not on the `KotlinJsBrowserDsl`. That means it should generally be placed in the parent scope, like in the other examples:
```
js(IR) {
browser {
// . . .
}
binaries.executable()
}
```
...and not, like in these examples, inside the browser-block specifically:
```
js(IR) {
browser {
binaries.executable()
}
}
```

Remove `binaries.executable` from within `browser` block

---

docs/topics/gradle/get-started-with-jvm-gradle-project.md
docs/topics/gradle/gradle-compilation-and-caches.md
docs/topics/gradle/gradle-configure-project.md
docs/topics/gradle/gradle-plugin-variants.md

Applying [minor suggestions](https://github.com/JetBrains/kotlin-web-site/pull/3333#pullrequestreview-1237071227) from the [Gradle changes 1.8.0 PR](https://github.com/JetBrains/kotlin-web-site/pull/3333) because that PR was reviewed after Kotlin 1.8.0 release.

fix: small "after review" fixes

---

docs/project.ihp

https://youtrack.jetbrains.com/issue/KTL-965/Fix-broken-links-in-the-meta-tags
[The demo branch](https://branch-ktl-965-fix-meta-tags.kotlin-web-site.labs.jb.gg/docs/dokka-introduction.html).
So, changing the prop fixes the issue with canonical and og:url meta tags.

KTL-965 Fix broken links in the meta tags

---

docs/kr.tree
docs/topics/kotlin-doc.md

As we introduce Dokka's documentation, this PR is to update the KDoc and Dokka page to remove any duplicating content and focus scope on KDoc.

Remove Dokka generation content from KDoc and Dokka page

---

docs/topics/sealed-classes.md

Following a [good catch in Slack](https://kotlinlang.slack.com/archives/C02B3PECK6E/p1673514938662269).
Checked at [play.kotlin](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS44LjAiLCJwbGF0Zm9ybSI6ImphdmEiLCJhcmdzIjoiIiwibm9uZU1hcmtlcnMiOnRydWUsInRoZW1lIjoiaWRlYSIsImNvZGUiOiIvKipcbiAqIFlvdSBjYW4gZWRpdCwgcnVuLCBhbmQgc2hhcmUgdGhpcyBjb2RlLlxuICogcGxheS5rb3RsaW5sYW5nLm9yZ1xuICovXG5mdW4gbWFpbihhcmdzOiBBcnJheTxTdHJpbmc+KSB7XG4gICAgdmFyIGVycm9yOiBFcnJvclxuICAgIGVycm9yID0gRmlsZVJlYWRFcnJvcigpXG4gICAgbG9nKGVycm9yKVxuICAgIGxvZzIoZXJyb3IpXG59XG5cbnNlYWxlZCBpbnRlcmZhY2UgRXJyb3Jcblxuc2VhbGVkIGNsYXNzIElPRXJyb3IoKSA6IEVycm9yXG5cbmNsYXNzIEZpbGVSZWFkRXJyb3IoKSA6IElPRXJyb3IoKVxuY2xhc3MgRGF0YWJhc2VFcnJvcigpIDogSU9FcnJvcigpXG5vYmplY3QgUnVudGltZUVycm9yIDogRXJyb3JcblxuZnVuIGxvZyhlOiBFcnJvcikge1xuICAgIHdoZW4gKG …

fix: else is not needed in sealed when independently of is it expression or statement

---

docs/topics/native/mapping-strings-from-c.md

mapping-strings-from-c.md - fix string typo

---

docs/topics/properties.md

fix small typo on [Properties Page](https://kotlinlang.org/docs/properties.html#backing-fields) that lead to misunderstanding

fix: fix small typo from "need" to "want"

---

data/events.yml

This PR adds the [Athens KUG February 2023 meetup](https://www.meetup.com/kotlin-athens/events/291447655/)

Adds Athens KUG February 2023 meetup

---

docs/topics/gradle/gradle-compiler-options.md
docs/topics/maven.md

This PR updates the tables of attributes common to JVM and JS in Gradle and Maven pages. Specifically it marks 1.3 as a language version that is supported but deprecated. In addition, API and language versions 1.9 are marked as experimental.

Update attributes common to JVM and JS in Gradle and Maven compiler options

---

docs/kr.tree
docs/topics/numbers.md

Move Unsigned integer types under Numbers in Basic types section, as the topics are closely related.

Move Unsigned integer types under Numbers in Basic types section

---

static/js/page/index/wh.theme.scss

Fixed unfolded button being offset with the folded one
Before:
After:

fix fold button display

---

docs/topics/lambdas.md

Fix link to LINQ (old link no longer update)

---

docs/topics/kotlin-doc.md

Fix Markdown link syntax in the KDoc page.

Correct Markdown link syntax in KDoc

---

docs/topics/gradle/gradle-configure-project.md

I tried to follow the current documentation and noticed that it didn't compile when using the provided example code in my .kts Gradle project. As far as I can tell, the `it` was simply copy-pasted from groovy and doesn't belong there, which is why I removed it.

fix: gradle languageVersion fix for .kts

---

docs/topics/js/js-debugging.md

We have an old link on the Debug Kotlin/JS code page pointing to content that doesn't exist anymore. So I'm removing the link entirely.

Remove old source maps link on Debug Kotlin/JS code page

---

docs/topics/multiplatform/multiplatform-library.md

There is some erroneous code in the multiplatform-library guide that is replaced.
Also, some clarification to vague parts of the guide is added.

Multiplatform Library Guide Erroneous Code Fix

---

docs/topics/ksp/ksp-overview.md

Fix formatting in ksp-overview

---

data/_nav.yml
docs/kr.tree
docs/topics/edu-tools-educator.md
docs/topics/edu-tools-learner.md
docs/topics/home.xml
docs/topics/jvm/jvm-get-started.md
docs/topics/koans.md
static/js/ktl-component/teach/index.jsx
static/js/ktl-component/why-teach/index.jsx

The EduTools plugin has been rebranded to JetBrains Academy plugin. Some of the links to the plugin documentation are now dead because of this rebrand so this PR will fix that.
[KT-57021](https://youtrack.jetbrains.com/issue/KT-57021/Broken-links-in-Kotlin-Koans)

Rebrand EduTools plugin

---

docs/topics/ksp/ksp-overview.md

This is a small PR to correct old code in the KSP documentation. The existing code sample did not work, both for compile-time reasons (the `functions` collection was of type `String`) and runtime reasons (the `map` command is optimised out by the compiler, so is never executed, replacing it with `forEach` resolves this). The corrected code makes it clearer for new engineers to understand KSP

bugfix : errors in the ksp documentation

---

docs/topics/native/native-cocoapods-libraries.md

* [KT-56366](https://youtrack.jetbrains.com/issue/KT-56366/Error-when-specifying-the-pod-path) the path path to the Podspec in the Podfile is not required anymore.

update: no pod path required anymore

---

docs/topics/kapt.md

[KT-56314](https://youtrack.jetbrains.com/issue/KT-56314) [Docs][JVM] Enable JVM IR for KAPT stub generation by default

Remove kapt.use.jvm.ir=true

---

docs/kr.tree

Google isn't indexing our Kotlin spec page with URL: https://kotlinlang.org/spec/
This is because our current link is set to: https://kotlin.github.io/kotlin-spec/
This PR will fix this issue.

Update menu link to Kotlin spec

---

docs/kr.tree
docs/topics/sealed-classes.md

The page talks about both sealed classes and sealed interfaces. This PR changes the title to reflect this.

Change title for "Sealed Classes" page

---

docs/topics/kotlin-doc.md

Clarify what syntax can be used for internal and external links. Improve the appearance of code blocks.

Update KDoc inline link syntax

---

docs/topics/kapt.md
docs/topics/maven.md

[KT-56317](https://youtrack.jetbrains.com/issue/KT-56317) [Docs][Build Tools] kotlin-maven-plugin + kapt - allow aptMode to be set according to docs
[KT-56316](https://youtrack.jetbrains.com/issue/KT-56316) [Docs][Build Tools] Add components.xml to automatically compile kotlin maven projects

Kotlin maven plugin to 1.8.20

---

docs/topics/gradle/gradle-configure-project.md

There's an extra `[` which is displayed
````
[Learn more about merging...
````

gradle-configure-project.md: Remove extra `[` in link

---

docs/kr.tree
docs/topics/js/js-samples.md
docs/topics/ksp/ksp-faq.md
docs/topics/multiplatform-mobile/multiplatform-mobile-faq.md
docs/topics/multiplatform-mobile/multiplatform-mobile-samples.md

We have pages with the same titles "Samples" and "FAQ". This PR makes changes so that all page titles are unique.

Fix duplicate page titles

---

.github/workflows/verify-samples.yml

The repo https://github.com/AlexanderPrendota/kotlin-compiler-server was transferred to JetBrains.
So the verifier can not work with redirection. (`cannot retry due to redirection, in streaming mode`)

chore(workflow): change push repo for samples

---

.teamcity/builds/kotlinlang/buidTypes/BuildSitePages.kt

use core api reference docs built with legacy Dokka from 1.8.20 project

chore: update core api reference docs (1.8.20)

---

.github/workflows/verify-samples.yml

Kotlin compiler server works on Java 17. (see https://github.com/JetBrains/kotlin-compiler-server/pull/634)

chore: update java in sample verifier

---

docs/topics/components-stability.md

Update some states of components in the component stability table, as part of the 1.9.0 release.

Update components stability for 1.9.0

---

docs/topics/js/js-project-setup.md
docs/topics/js/js-react.md

For Kotlin 1.9.0, this PR updates the default distribution target directory for Kotlin/JS.

Update JS default distribution target directory

---

docs/topics/ksp/ksp-overview.md

Add [SealedX](https://github.com/skydoves/sealedx) to list of KSP-supported libraries.

Add SealedX to list of KSP supported libraries

---

.teamcity/builds/kotlinlang/buidTypes/BuildSitePages.kt
static/js/page/api/api.js

- use core api reference docs built with legacy Dokka from 1.9.0 project
- add version selector 1.9 for stdlib docs

chore: update core api reference docs (1.9.0)

---

docs/topics/jvm/java-interop.md

This PR is to update the compiler option for Java synthetic properties since the release of Kotlin 1.9.0.

Update compiler option for 1.9.0 Java synthetic properties

---

docs/topics/idioms.md

The return statement in the version before this change will not return the value to the run statement but to the enclosing function.

Fix misleading idiom if-not-null-else shorthand.

---

docs/topics/reflection.md

Uses the same dependency declaration scheme as in https://kotlinlang.org/docs/jvm-test-using-junit.html#add-dependencies (and saves people from having to manually specify the version number for the `reflect` artifact)

Use kotlin DSL function to specify reflection dependency

---

docs/topics/tour/kotlin-tour-control-flow.md

This PR updates the Control flow page in the Kotlin tour so that is uses the new rangeUntil operator introduced in 1.9.0.

Replace until with rangeUntil operator in Kotlin tour

---

.teamcity/builds/apiReferences/kotlinx/datetime/KotlinxDatetimeBuildApiReference.kt
.teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmBuildApiReference.kt
.teamcity/builds/apiReferences/templates/BuildApiReference.kt
.teamcity/builds/kotlinlang/buidTypes/BuildSitePages.kt
docs/kr.tree

https://youtrack.jetbrains.com/issue/KTL-1139/Set-up-publishing-of-kotlinx-metadata-jvm-documentation-on-kotlinlang.org

KTL-1139 Set up publishing of kotlinx-metadata-jvm documentation on kotlinlang.org

---

docs/kr.tree
docs/topics/time-measurement.md

Add a guide for the Stable time API introduced in 1.9.0.

feat: add time API guide

---

docs/topics/gradle/gradle-compilation-and-caches.md

Gradle promoted the configuration cache to Stable in 8.1. This PR updates our documentation to reflect this.

Update Gradle configuration cache support

---

docs/topics/time-measurement.md
docs/topics/tour/kotlin-tour-collections.md
docs/topics/tour/kotlin-tour-hello-world.md

There are a couple of runnable examples in the Kotlin tour that have no output to console. This PR adds `println()` to these examples to generate output.

Make all tour examples print something

---

CODEOWNERS

https://youtrack.jetbrains.com/issue/KTL-1166/Add-Code-Owners-file-to-the-website-repository

KTL-1166 Add Code Owners file to the website repository

---

docs/topics/jvm/jvm-create-project-with-spring-boot.md
docs/topics/jvm/jvm-spring-boot-add-data-class.md
docs/topics/jvm/jvm-spring-boot-add-db-support.md
docs/topics/jvm/jvm-spring-boot-using-crudrepository.md

This PR fixes the following issues:
https://youtrack.jetbrains.com/issue/KT-60838
https://youtrack.jetbrains.com/issue/KT-57411
https://youtrack.jetbrains.com/issue/KT-59853
https://youtrack.jetbrains.com/issue/KT-57474
https://youtrack.jetbrains.com/issue/KT-59127
https://youtrack.jetbrains.com/issue/KT-52305

update: update the Spring Boot tutorial

---

docs/topics/classes.md
docs/topics/data-classes.md
docs/topics/eap.md
docs/topics/install-eap-plugin.md
docs/topics/tour/kotlin-tour-functions.md

This PR adds a note to EAP pages explaining that if the Kotlin EAP plugin can't find the latest Kotlin version, users need to check that they are on the latest IDE version. It also clarifies the definition of a primary constructor as the current description is misleading. In addition, there is some formatting fixes for data class member functions.
This PR resolves:
- [KT-57525](https://youtrack.jetbrains.com/issue/KT-57525/Primary-constructor-definition)
- [KT-57864](https://youtrack.jetbrains.com/issue/KT-57864/Web-feedback-from-Install-the-Kotlin-EAP-Plugin-user-cannot-update)

Update EAP and Classes pages

---

docs/topics/compatibility-guide-19.md

This PR adds the ticket to remove language version 1.3 to the compatibility guide.

Update compatibility guide 1.9.0

---

docs/topics/generics.md
docs/topics/jvm/java-to-kotlin-nullability-guide.md
docs/topics/null-safety.md

This PR adds documentation for generic types that are definitely non-nullable. The content is primarily added to the [Generics](https://kotlinlang.org/docs/generics.html) page. A link has been added to the [Null safety](https://kotlinlang.org/docs/null-safety.html) page, and the [Java to Kotlin nullability guide](https://kotlinlang.org/docs/java-to-kotlin-nullability-guide.html) also has a small update.
This PR resolves [KT-54422](https://youtrack.jetbrains.com/issue/KT-54422/Add-documentation-on-website-for-Definitely-non-nullable-types-feature).

Add definitely non-nullable types documentation

---

docs/topics/kotlin-evolution.md

Werner Dietl has replaced William Cook in Kotlin Lanauge Committe.

Update kotlin-evolution.md to mention Werner Dietl

---

docs/topics/gradle/gradle-compiler-options.md
docs/v.list

Similar to #3742, this PR adds `apiVersion` as a variable to make it easier to update in our documentation.

Add Gradle's apiVersion as a variable

---

docs/topics/typecasts.md

This PR updates the Type checks and casts page to make it clear earlier in the page that generics documentation is available on another page. Other changes have been added, like an introduction and other modifications, to tidy up the page a bit.
This PR resolves KT-57270.

Small update to Type checks and casts page

---

data/testimonials.yml

https://youtrack.jetbrains.com/issue/KTL-1182/Fix-404-on-Evernote-link-on-kotlinlang.org-main-page

KTL-1182 Fix 404 on Evernote link on kotlinlang.org main page

---

docs/topics/no-arg-plugin.md

- Provide a sample annotation to illustrate how the plugin should be used.
- Explain how to utilize the plugin using Kotlin DSL in Gradle, as an alternative for Groovy.

improve documentation on no-arg-plugin.md

---

docs/topics/multiplatform-mobile/multiplatform-mobile-understand-project-structure.md

androidTest has been renamed to androidUnitTest in Kotlin 1.9.
https://kotlinlang.org/docs/whatsnew18.html#kotlin-multiplatform-a-new-android-source-set-layout

Update to the latest Android SourceSet

---

docs/topics/multiplatform-mobile/multiplatform-mobile-concurrency-and-coroutines.md
docs/topics/multiplatform-mobile/multiplatform-mobile-concurrency-overview.md
docs/topics/multiplatform-mobile/multiplatform-mobile-concurrent-mutability.md
docs/topics/native/native-immutability.md
docs/topics/native/native-ios-integration.md
docs/topics/native/native-memory-manager.md

* [KT-59547](https://youtrack.jetbrains.com/issue/KT-59547) First result for "Kotlin concurrency" on Google leads to "legacy memory manager" page
* [KT-58582](https://youtrack.jetbrains.com/issue/KT-58582/Web-feedback-from-Kotlin-Native-memory-management-https-kotlinlang.org-docs-native-memory-manager.html)

update: warnings for the new and the legacy memory manager pages

---

docs/topics/js/js-ir-compiler.md

This PR swaps out "of" for "or" to clarify the details about the deprecated legacy compiler.

fix: correct typo in js-ir-compiler.md

---

docs/topics/numbers.md

Fixes [KT-61654](https://youtrack.jetbrains.com/issue/KT-61654).

Clarify that Int is the default range for integer types

---

docs/topics/generics.md

This PR fixes [KT-61381](https://youtrack.jetbrains.com/issue/KT-61381/Web-feedback-from-Generics-in-out-where-https-kotlinlang.org-docs-generics.html).

Clarify covariance example

---

docs/topics/run-code-snippets.md

Menu item in IDEA has been pushed to the "New Kotlin File" submenu.

Fix instructions to create a Kotlin worksheet

---

docs/topics/gradle/gradle-compilation-and-caches.md
docs/topics/gradle/gradle-configure-project.md
docs/topics/gradle/gradle-plugin-variants.md
docs/v.list

This PR updates Gradle versions for 1.9.20 and removes a tip explaining that Kotlin/Native tasks aren't included in Gradle build reports.

Update Gradle versions  for 1.9.20

---

docs/topics/arrays.md
docs/topics/collections-overview.md
docs/topics/equality.md

This PR updates the Arrays page with additional content.
It will resolve the following YouTrack tickets:
- KT-55214
- KT-46054
- KT-46629
- KT-49167
- KT-48481
- KT-50043
- KT-52564
- KT-56228
- KT-57718
- KT-57473
- KT-58318
- KT-58810
- KWHF-18
- KWHF-86
- KWHF-765
- KWHF-934

Update Arrays page

---

docs/topics/whatsnew19.md

At the moment, it's not explicit where to add the Gradle property that allows users to try K2.

Clarify Gradle property location in what's new 1.9.0

---

docs/topics/tour/kotlin-tour-functions.md

fix copy-pasted naming in "kotlin tour > functions > lambda expressions > pass to another function > map()" example
the term "predicate" seems to be copy-pasted from a nearby example of filter() method. 
the suitable term for map() method param is "transformer" I guess

fix kotlin tour functions (lambda expressions) documentation

---

docs/topics/enum-classes.md

This PR adds the Experimental `enumEntries<T>()` generic function to documentation as part of 1.9.20

Add Experimental enumEntries<T>() generic function for 1.9.20

---

docs/topics/gradle/gradle-configure-project.md
docs/topics/kapt.md
docs/topics/maven.md
docs/topics/whatsnew1530.md
docs/topics/whatsnew1620.md
docs/topics/whatsnew17.md
docs/topics/whatsnew18.md

Add CLI option for kapt that is introduced in 1.9.20:
`dumpFileReadHistory`: An output path to dump for each file a list of classes used during annotation processing.

Add kapt CLI option for 1.9.20

---

docs/topics/numbers.md

Solves [KT-62075](https://youtrack.jetbrains.com/issue/KT-62075).

Clarify example for NaNa on Numbers page

---

docs/topics/idioms.md

Open for discussion here @JetBrains/kotlin-technical-writing – I don't understand the original motivation for adding this as a Kotlin "idiom", seeing how this seems like an instance of the [tri-state boolean](https://thoughtbot.com/blog/avoid-the-threestate-boolean-problem) problem.
If there is a reason as to why we're highlighting this as an idiom, I'd appreciate a short explanation – otherwise, it's probably better if it is removed.

Remove nullable boolean "idiom"

---

docs/topics/gradle/gradle-configure-project.md

This PR updates the Gradle transitive dependencies section as a result of the changes in 1.9.20 standard library.

Update Gradle transitive dependencies section for 1.9.20

---

docs/topics/multiplatform-mobile/multiplatform-mobile-ktor-sqldelight.md

This PR updates [this tutorial](https://kotlinlang.org/docs/multiplatform-mobile-ktor-sqldelight.html) with 1.9.20 build script APIs. The corresponding updates in the sample:
* [Initial state](https://github.com/kotlin-hands-on/kmm-networking-and-data-storage/pull/32)
* [Final state](https://github.com/kotlin-hands-on/kmm-networking-and-data-storage/pull/31)

Update the tutorial build scripts with 1.9.20 APIs

---

docs/topics/scope-functions.md

When I was reading the section of Scope functions, [I started to summarize for me to memorize them](https://blog.kotlin-academy.com/kotlin-scope-functions-for-dummies-cb8c8970b8d9). There are good summary sentences about `with`, `apply`, and `also` in the doc. I added summary sentences for `let` and `run`. I hope it's good enough.

Add summary sentences for `let` and `run` functionality

---

docs/topics/native/native-objc-interop.md

* [KT-60545](https://youtrack.jetbrains.com/issue/KT-60545/Documentation-change-on-Interoperability-with-Swift-Objective-C-highlight-that-it-is-not-normal-to-suppress-errors)

update: warning on suppressing errors

---

.teamcity/builds/kotlinlang/buidTypes/BuildSitePages.kt

use core api reference docs built with legacy Dokka from 1.9.20 project

chore: update core api reference docs (1.9.20)

---

docs/topics/data-science-overview.md

Remove the kotlin-statistics library from the Data science overview because the library has been deleted by the author.

Remove kotlin-statistics library from Data science overview

---

docs/topics/object-declarations.md

The `print(helloWorld)` line should be visible on the docs page, otherwise one could only guess why "Hello World" is printed when running the example code.
[See example](https://kotlinlang.org/docs/object-declarations.html#creating-anonymous-objects-from-scratch).

fix: include print statement in object expression example

---

docs/topics/native/native-cocoapods.md

There's a designated DSL property for this, no need to configure the task manually.

Set CocoaPods headers through DSL

---

docs/topics/basic-syntax.md

This ticket fixes [KT-50150](https://youtrack.jetbrains.com/issue/KT-50150/Docs-Basic-syntax-Weird-incorrect-code-sample).

Update the variables in Basic syntax class example

---

docs/topics/gradle/get-started-with-jvm-gradle-project.md
docs/topics/gradle/gradle-configure-project.md
docs/topics/maven.md
docs/topics/whatsnew18.md

This PR resolves [KT-62107](https://youtrack.jetbrains.com/issue/KT-62107/DocsBuild-tools-Warn-users-about-using-mavenLocal-in-Maven-Gradle-projects).

Add mavenLocal() repository warning

---

.idea/vcs.xml

I consulted with @konstantin.chernenko: IDEA complains about this line, which points to a directory that no longer exists.

Remove obsolete mapping

---

docs/topics/enum-classes.md

`.entries` is a stable part of the enum API since 1.9.0, so the featured code snippets should use it. A reference to the soft-deprecated `values()` function can of course remain :)

Put emphasis on enum `entries` rather than `values()`

---

docs/kr.tree
docs/topics/wasm/wasm-get-started.md
docs/topics/wasm/wasm-overview.md
docs/topics/wasm/wasm-troubleshooting.md
docs/topics/whatsnew19.md
docs/topics/whatsnew1920.md

created a new page for troubleshooting, updated content, and removed troubleshooting content from getting started.

Kotlin/Wasm: adding new page for troubleshooting

---

docs/topics/install-eap-plugin.md
docs/topics/jvm/jvm-get-started.md
docs/topics/releases.md
docs/topics/whatsnew1920.md

This PR adds notes to relevant pages explaining that users of new IntelliJ and Android Studio versions don't have to configure the Kotlin plugin separately anymore.

Add notes about the Kotlin plugin being included in new IDE releases

---

docs/kr.tree
docs/topics/eap.md
docs/topics/whatsnew-eap.md
docs/v.list

This PR adds details about the Kotlin 2.0.0-Beta2 release.

Kotlin 2.0.0-Beta2 release

---

docs/topics/multiplatform/multiplatform-add-dependencies.md

I was trying to understand what exactly I was supposed to do: don't use the name like it's used in the example, or don't use the name like it's not used in the example.
I think I get it now, so I tried to clarify this.

fix: clarity in the tip for the specific source set

---

static/js/page/dokka-template/footer/index.jsx

https://youtrack.jetbrains.com/issue/KTL-1306/Footer-in-Api-References-is-not-readable

KTL-1306 Footer in Api References is not readable

---

docs/topics/generics.md

The comments in the example are not sufficient to explain the train of thought preceding it.

fix: clear up the example of usefulness of invariant generics

---

docs/topics/jvm/java-to-kotlin-interop.md

This change fixes [KT-64908](https://youtrack.jetbrains.com/issue/KT-64908/Private-top-level-property-and-function-are-compiled-into-JVM-private-members-while-documentation-says-different).

Update Visibility section in Calling Kotlin from Java page

---

docs/kr.tree
docs/topics/eap.md
docs/topics/whatsnew-eap.md
docs/v.list

Updated whatsnew-eap.md and eap.md as required by 2.0.0-Beta3 release.

Feat: adding what's new 2.0.0-Beta3 (#3974)

---

docs/topics/native/native-ios-symbolication.md

Remove "Decode inlined stack frames" section from "Symbolicating iOS crash reports".
This section seems obsolete. The command no longer works -- it has to be "command script import lldb.macosx" instead of "script import ...".
But even with this change, it is not of much use: it can't find .dSYM bundles for crashlogs copied from iPhone. Some additional manipulations are required to make this work.
Considering that this part is not even Kotlin-specific and there are many tutorials on that topic on the internet, it seems justified to remove the problematic section instead of expanding it.

Remove "Decode inlined stack frames" from native-ios-symbolication.md

---

blocks/main/hero/hero.tsx

Before:
https://github.com/JetBrains/kotlin-web-site/assets/242514/4a476a5f-92c4-4926-92ef-391a2abe6b61

chore: set default height and width of hero image for slow network

---

docs/topics/multiplatform/multiplatform-expect-actual.md

This code was reporting a warning 
> Annotation `@Retention(value = AnnotationRetention.SOURCE)` has different arguments on actual declaration: `@Retention(value = AnnotationRetention.RUNTIME)` ...
> All annotations from expect `annotation class XmlSerializable : Annotation defined in com.example in file Main.common.kt` must be present with the same arguments on actual `annotation class XmlRootElement : Annotation defined in javax.xml.bind.annotation in file XmlRootElement.class`, otherwise they might behave incorrectly.
The proper fix is to set Retention to RUNTIME on expect declaration.

Fix warning about non-matching annotations in code example

---

data/user-groups.yml

The organizer of Guangzhou KUG wants to update the website URL. Just a minor change of user group list yaml file.

Update Guangzhou KUG URL

---

docs/topics/whatsnew-eap.md

This PR tidies up the list of K2 compiler supported plugins by separating Kotlin compiler plugins from the rest and providing versions/information for non-Kotlin compiler plugins.

Update K2 plugin support in whatsnew-eap

---

docs/topics/home.xml

This PR updates the links provided under the Kotlin Multiplatform section on the Docs home page.

Update Docs home page - Kotlin Multiplatform section

---

docs/topics/object-declarations.md

fixing article usage and some markup (e.g.: warning should now show up properly)

chore: markup + small improvements in object expressions document

---

docs/topics/whatsnew-eap.md

This PR removes the Kotlin/Wasm feature from the What's new for 2.0.0-Beta4.

Remove Kotlin/Wasm section from What's new for 2.0.0-Beta4

---

docs/topics/home.xml

This PR is to remove the link collections at the bottom of the Docs home page.

Remove link collections from the bottom of Docs home page

---

docs/topics/wasm/wasm-troubleshooting.md

Rephrased "In addition to updating the browser settings, make sure you use a Kotlin version before 1.9.20 when using a Chrome version older than version 119" sentence.

chore: adding version browser clarification

---

docs/topics/getting-started.md

This PR updates the Get started page by removing the multiplatform library tab from the **Create your powerful application with Kotlin** section.

Remove multiplatform library tab from Get started page

---

docs/topics/numbers.md

Hi!
Launching this example is useless, moreover, when launching it, it becomes visible that the variable is unused:

delete launching example that doesnt print anything

---

docs/topics/multiplatform/multiplatform-add-dependencies.md

The directory is not necessarily named "shared" even in wizard-generated projects.

fix: abstract away the name of the directory

---

docs/topics/gradle/gradle-configure-project.md

This PR adds Kotlin releases 1.9.21-1.9.23 to the supported KGP versions on the Configure a Gradle project page.

Update supported KGP versions

---

.teamcity/builds/apiReferences/kotlinx/metadataJvm/KotlinxMetadataJvmBuildApiReference.kt

"build api reference" step leak a Gradle daemon process which may cause any builds on the same agent to fail 
^KTI-1650

Add --no-daemon flag to "kotlinx-metadata-jvm API reference"

---

docs/topics/strings.md

Added info how templates really works - implicit invocation of toString()

Added a little clarification - implicit invocation of toString() in string templates

---

docs/topics/basic-syntax.md
docs/topics/classes.md

Update Classes page to mention variables when creating an instance, and update Variables section in Basic syntax page to mention initialization and more.

Update classes and basic syntax pages

---

docs/topics/gradle/gradle-configure-project.md
docs/v.list

This PR updates the max/min supported Gradle versions and AGP versions for Kotlin 2.0.0.

Update Gradle supported versions for 2.0.0

---

docs/topics/gradle/gradle-plugin-variants.md

This PR updates the table of KGP variants to include those for Kotlin 2.0.0.

Update KGP variants for 2.0.0

---

docs/topics/gradle/gradle-compilation-and-caches.md

This PR documents the tryNext Gradle property as part of Kotlin 2.0.0.

Document tryNext Gradle property

---

docs/topics/multiplatform/multiplatform-publish-lib.md

This PR documents the new JVM environment attribute that Gradle uses as part of multiplatform library publication and use.

Document JVM environment attribute for multiplatform library publication

---

docs/topics/components-stability-pre-1.4.md
docs/topics/kotlin-evolution.md
docs/topics/releases.md
docs/topics/whatsnew14.md
docs/topics/whatsnew15.md
docs/topics/whatsnew16.md
docs/topics/whatsnew17.md
docs/topics/whatsnew18.md
docs/topics/whatsnew19.md

[KT-67865](https://youtrack.jetbrains.com/issue/KT-67865) [Docs][K2] update Kotlin Release Page
[KT-67944](https://youtrack.jetbrains.com/issue/KT-67944) [Docs][K2][IDE] Update IDE support description for K2

feat: update the Kotlin release information and evolution principles

---

docs/topics/k2-compiler-migration-guide.md

This PR includes updates to the K2 compiler migration guide for Kotlin 2.0.0.

Update K2 compiler migration guide for 2.0.0

---

docs/topics/wasm/wasm-troubleshooting.md

This PR is about adding a new section to the Troubleshooting page about Wasm proposals, according to the 2.0.0 release.

update: adding new section about Wasm proposals

---

docs/topics/kotlin-notebook-overview.md

This PR adds references from the Kotlin Notebook overview in Kotlin docs to the Kotlin Notebook overview in IntelliJ IDEA docs

chore: adding link to IntelliJ docs

---

docs/topics/wasm/wasm-js-interop.md

This PR contains additions to the Wasm interop page about the @JsExport annotation, according to the 2.0.0 release.

update: change wasm interop page

---

docs/topics/k2-compiler-migration-guide.md
docs/topics/whatsnew20.md

This PR synchronizes content between what's new for Kotlin 2.0.0 and K2 compiler migration guide.

update: sync content between what's new and compiler guide

---

docs/topics/whatsnew20.md

* change the link to the Google announcement
* remove 1.5.0 mention as it requires a different setup

fix: Compose compiler mention

---

docs/kr.tree
docs/topics/multiplatform/multiplatform-get-started.md

a temporary workaround for the duplicated Get Started issue: the renamed page will one day be a technical overview with the "How it works" title. For now, the introduction title looks better.

update: rename KMP get started

---

docs/topics/compatibility-guides/compatibility-guide-20.md

This PR fixes the table in the compatibility guide for 2.0.0.

Fix compatibility guide 2.0.0 table

---

docs/topics/k2-compiler-migration-guide.md
docs/topics/tour/kotlin-tour-control-flow.md
docs/topics/typecasts.md
docs/topics/whatsnew20.md

This PR contains minor fixes for content in the K2 compiler migration guide, what's new for Kotlin 2.0.0, type checks and casts, and the tour - control flow.

Fixes for K2 compiler migration guide, type checks and casts, tour - control flow

---

docs/topics/kapt.md
docs/topics/whatsnew20.md

This PR documents how kapt configurations can inherit annotation processors from super configurations in Kotlin 2.0.0.

Document kapt inheritance of super configurations

---

docs/topics/tour/kotlin-tour-functions.md

In general, I think it is a bad idea to use name parameters with the same name of its type. I am coming from C#, and there both `string` and `String` are the reserved words for the type name. It could be confusing and easily avoided using `message`, `word`, or something else instead.

feat: avoid "string" as parameter name to improve readability

---

docs/topics/delegation.md

- renamed the local variables:
name `b` was used as the constructor parameter AND a local variable.
- removed `val` from the constructor parameter

Docs: Improve Sample Code

---

docs/topics/native/apple-privacy-manifest.md

This PR updates the documentation on privacy manifests. We implemented two new tools related to privacy manifests:
* a script to find required reason APIs in the dependencies of a Kotlin librariy
* a plugin to help with embedding of a privacy manifest in a Kotlin framework

Privacy manifests update

---

src/pdf.py

* Fix broken `images/` prefix for external images automatically
* Drop "test page" article
* Drop "Kotlin Night brand assets"

Pdf generator improvements

---

docs/topics/multiplatform/multiplatform-discover-project.md

https://youtrack.jetbrains.com/issue/KTL-1504/No-redirect-from-api-latest-kotlin.test-to-api-latest-kotlin.test
I searched all the documentation for a similar link, but this is the only place to fix it.

KTL-1504 No redirect from /api/latest/kotlin.test to /api/latest/kotlin.test/

---

docs/topics/k2-compiler-migration-guide.md

This PR adds information about how the K2 compiler works with Kotlin libraries and compiler plugins to the K2 compiler migration guide.

Add information about Kotlin libraries and compiler plugins to K2 migration guide

---

docs/topics/home.xml

This PR is to update the Docs home page:
* Move KMP section higher
* Collapse What's new and Featured topics sections into one
* Remove two featured topics
* Replace Public roadmap with Releases

Update Docs home page

---

docs/topics/jvm/java-interop.md

This PR corrects the mapped type for `String[]` on the Java interop page.

Fix String array mapped type on Java interop page

---

docs/topics/native/mapping-primitive-data-types-from-c.md

This is a small fix to change typo in description of C keywords.

Fix typo in mapping-primitive-data-types-from-c.md

---

docs/topics/getting-started.md

This PR removes the outdated Udacity course link from the Android tab on the Get started page.

Remove outdated course from Get started - Android

---

docs/topics/k2-compiler-migration-guide.md
docs/topics/whatsnew20.md

Clearer comments to explain the differences between compiler versions, specifically why we can't call tau() in 2.0 after the inc() operator.

Update K2 inc and dec operators example

---

docs/topics/releases.md
docs/topics/whatsnew20.md

This PR corrects the UI element name to enable K2 Kotlin Mode in the IDE.

Fix IDE instruction for K2 Kotlin Mode

---

docs/topics/js/js-to-kotlin-interop.md

The documentation was ambiguous and led to situations where the developer passed JS arrays directly to `KtList` parameters, thinking the conversion was automatic, or where a returned `KtList` was used as a JS array.

Improve type mapping for exportable Kotlin collections

---

docs/topics/k2-compiler-migration-guide.md

This PR updates the K2 compiler migration guide by:
* Making the support in IntelliJ IDEA section also include information about Android Studio.
* Explain more clearly how to configure the K2 compiler in the build system AND optionally, in the IDE.
Reviewed already by @AlejandraPedroza.

Update support in IDEs section of K2 compiler migration guide

---

docs/topics/roadmap.md

Since we are still working on the Kotlin and its ecosystem strategy after the Kotlin 2.0.0 release, we (the JetBrains team) decided to move the date.

chore: update the roadmap update date

---

docs/topics/gradle/gradle-compilation-and-caches.md
docs/topics/gradle/gradle-compiler-options.md
docs/topics/gradle/gradle-configure-project.md
docs/topics/js/js-project-setup.md

This PR updates any instances in our docs where Groovy syntax uses the `set()` function and replaces it with an assignment operator.

Update Groovy syntax from using the set() function

---

docs/topics/whatsnew-eap.md

This PR fixes a sentence in the what's new for 2.0.20-Beta2 about the old JVM incremental compilation approach for Gradle being deprecated.

Updated text in what's new for Kotlin 2.0.20-Beta2

---

docs/topics/multiplatform/multiplatform-plugin-releases.md

This PR adds the 0.8.3 version of the Kotlin Multiplatform plugin for Android Studio.

Add KMM AS plugin 0.8.3 release notes

---

docs/topics/whatsnew-eap.md

This PR updates some text in the What's new for 2.0.20-RC for the Compose compiler. Approved by Pavel Shishkin and Andrei Shikov.

Update text in What's new for 2.0.20-RC for the Compose compiler

---

docs/topics/whatsnew-eap.md

This PR moved Compose compiler Gradle plugin updates under the Compose compiler section in what's new for 2.0.20-RC.

Restructure the Compose section in whatsnew-eap.md

---

docs/topics/k2-compiler-migration-guide.md
docs/topics/releases.md
docs/topics/whatsnew20.md

This PR updates K2 Kotlin mode from Alpha to Beta and renames "K2 Kotlin mode" to "K2 mode". Approved by Teodor Irkhin.

Change K2 Kotlin mode to Beta

---

docs/topics/gradle/gradle-compilation-and-caches.md
docs/topics/gradle/gradle-configure-project.md
docs/v.list

This PR updates Gradle versions for 2.0.20 and removes the section about the "new" incremental compilation approach.

Add Gradle updates for 2.0.20

---

docs/topics/gradle/gradle-configure-project.md

This PR adds documentation for the `archivesTaskOutputAsFriendModule` Gradle property that comes in Kotlin 2.0.20.

Add archivesTaskOutputAsFriendModule Gradle property

---

docs/kr.tree
docs/topics/eap.md
docs/topics/whatsnew-eap.md
docs/v.list

This PR adds information about the Kotlin 2.0.20-RC2 release.

Add details for Kotlin 2.0.20-RC2 release

---

docs/topics/gradle/gradle-configure-project.md
docs/topics/multiplatform/multiplatform-compatibility-guide.md

For release 2.0.20, add compatible versions and new item about deprecated compatibility with Gradle Java plugins.

Update Multiplatform compatibility guide for 2.0.20

---

docs/topics/wasm/wasm-troubleshooting.md

This PR contains doc updates for the Kotlin 2.0.20 release. The updates include adding information about how to use default import.

Add information about how to use default import.

---

docs/topics/js/js-ir-compiler.md
docs/topics/whatsnew1420.md
docs/topics/whatsnew20.md

This PR updates the documentation on Kotlin/JS IR compiler following [KT-65018](https://youtrack.jetbrains.com/issue/KT-65018)

update: error tolerance removed

---

docs/topics/native/native-ios-integration.md

This PR removes mentions of the restriction on calling suspend functions from non-main threads following [KT-65666](https://youtrack.jetbrains.com/issue/KT-65666)

feat: removed restriction on suspend functions on non-main threads

---

docs/topics/multiplatform/multiplatform-native-artifacts.md
docs/topics/native/native-cocoapods.md
docs/topics/native/native-faq.md

This PR removes mentions of `embedBitcode` parameter and updates the answer in FAQ, following [KT-61875](https://youtrack.jetbrains.com/issue/KT-61875) and [KT-66262](https://youtrack.jetbrains.com/issue/KT-66262)

fix: bitcode embedding removed

---

docs/topics/multiplatform/multiplatform-android-dependencies.md
docs/topics/multiplatform/multiplatform-hierarchy.md

This PR changes the description of the default source set hierarchy, following [KT-56566](https://youtrack.jetbrains.com/issue/KT-56566), plus fixes mentions of the Android target

feat: static accessors for the default hierarchy

---

docs/topics/native/native-target-support.md

The target is now regularly tested on CI to be able to run, and thus matches all the criteria for Tier 1

feat: move iosArm64 target from Tier 2 to Tier 1

---

docs/topics/k2-compiler-migration-guide.md
docs/topics/typecasts.md

This PR adds Kotlin 2.0.20 to the K2 compiler migration guide.

Add Kotlin 2.0.20 to K2 compiler migration guide

---

docs/topics/native/mapping-function-pointers-from-c.md

Update the sentence to be a separate paragraph (I think the visual distinction helps indicate the raised importance), and update the sentence so it reads more naturally.

Tidy grammar for `staticCFunction {}` exceptions warning

---

docs/topics/slack-code-of-conduct.md

docs(slack-code-of-conduct): remove reference to common channels list

---

docs/topics/opt-in-requirements.md

This PR revamps the opt-in requirements page and adds new content about the @SubclassOptInRequired that comes in 2.1.0.

Add @SubclassOptInRequired documentation

---

docs/topics/multiplatform/multiplatform-compatibility-guide.md

Minor clarifications to the compatibility page: even though all of these versions are supposed to be the same, referring to them could be better phrased.

fix: clearer reference to the KMP plugin

---

docs/topics/coding-conventions.md

Adjust grammar usage when describing uppercase, lowercase, camelCase, Pascal case, and other style cases; replace word "case" with synonyms when not describing one of the cases above (e.g. "example", "circumstance", etc.)

Grammar inconsistencies around "cases" (uppercase, lowercase, etc.)

---

docs/topics/gradle/gradle-compilation-and-caches.md
docs/topics/whatsnew20.md

Wrapping the json directory property with quotes results in an error:
```
Kotlin build report cannot be created: '"my/directory/path"' is a file or do not have permissions to create
```
Hit this error while following these docs and also found a relevant ticket on YouTrack that was already closed: https://youtrack.jetbrains.com/issue/KT-71049/Cannot-get-build-report-is-a-file-or-do-not-have-permissions-to-create

fix: invalid kotlin build report config directions

---

docs/topics/tour/kotlin-tour-functions.md

The exercise has a `// Write your code here`in the function body, but the function header needs to be modified too.
Either:
- the correct parameter and return type should be added to the function header.
- the function should be removed entirely and just put the `//Write your code here` block.
- the instruction should be `// modify the next function to meet the requirements`
This suggestion goes with the second one.

The first exercise of Functions practice could be confusing

---

.teamcity/BuildParams.kt

It's unclear how it worked before. 
The fix is on staging.

ktl-1710 fix: update the kotlinx-io tag name

---

docs/topics/gradle/gradle-plugin-variants.md

This PR updates the documentation so that plugin variants that aren't supported in 2.1.0 are removed.

Remove plugin versions for 2.1.0

---

docs/topics/whatsnew2020.md

This PR adds a new section about a Gradle topic to whatsnew2020.md.

Add new section to whatsnew2020.md

---

docs/topics/whatsnew1530.md
docs/topics/whatsnew17.md

This PR fixes some broken anchor links on `2-1-0-doc-update`.

Fix some opt-in links on the 2.1.0 docs branch

---

docs/topics/gradle/gradle-compilation-and-caches.md

I filed [KT-71564](https://youtrack.jetbrains.com/issue/KT-71564/Kotlin-Daemon-JVM-args-behavior-does-not-match-documentation) the other day because my previous understanding (and that of some of the AndroidX team) was that all Gradle JVM args would be inherited if no Kotlin JVM args were specified. I did some digging in the Kotlin Gradle Plugin and Kotlin Daemon sources to find how that process works and think this should clear everything up.

Kotlin daemon JVM args - clearing up inheritance and defaults

---

docs/topics/kotlin-language-features-and-proposals.md

Looks like we could've missed one of the language features on the page back in September, adding lost things now.

Added missed language feature "Expose boxed inline value classes in JVM"

---

docs/topics/advent-of-code.md
docs/topics/basic-syntax.md
docs/topics/control-flow.md
docs/topics/keyword-reference.md
docs/topics/sealed-classes.md
docs/topics/typecasts.md
docs/topics/whatsnew13.md
docs/topics/whatsnew1530.md
docs/topics/whatsnew16.md
docs/topics/whatsnew20.md

This PR updates the `when` section on the Conditions and loops page to make it clearer when exhaustiveness is required and in which cases.

Conditions and loops: Update when section

---

docs/kr.tree
docs/topics/compose-compiler-migration-guide.md
docs/topics/compose-compiler-options.md

Related pull request: https://github.com/JetBrains/kotlin-multiplatform-dev-docs/pull/267

moved Compose compiler from KMP portal

---

docs/topics/multiplatform/multiplatform-compatibility-guide.md
docs/v.list

This PR updates the compatible versions for KMP in the multiplatform compatibility guide for Kotlin 2.1.0.

Update versions in KMP compatibility guide for 2.1.0

---

docs/topics/coding-conventions.md
docs/topics/control-flow.md
docs/topics/sealed-classes.md

This PR adds information about Guard conditions in when expressions and how to use them.

Guard conditions in when expressions

---

docs/topics/multiplatform/multiplatform-compatibility-guide.md

This PR updates the deprecation cycle for the duplicate targets issue in the KMP compatibility guide.

KMP compatibility guide: Update deprecation cycle for duplicate targets

---

docs/topics/multiplatform/multiplatform-configure-compilations.md
docs/topics/multiplatform/multiplatform-dsl-reference.md

This PR adds documentation for the newly stabilized `compilerOptions` DSL as part of Kotlin 2.1.0.

Document new `compilerOptions` DSL for 2.1.0

---

docs/topics/multiplatform/multiplatform-compatibility-guide.md

This PR updates the deprecation cycle of the duplicate targets topic in the KMP compatibility guide.

KMP compatibility guide: Update duplicate targets

---

docs/topics/multiplatform/multiplatform-compatibility-guide.md

This PR aligns the updated KMP compatibility guide changes about duplicate targets on master (needed for EAP what's new) with the `2-1-0-doc-update` branch.

Sync KMP compatibility guide changes on duplicate targets content

---

docs/topics/multiplatform/multiplatform-configure-compilations.md

This PR documents Kotlin 2.1.0's support for the Isolated Projects feature in Gradle.

update: add Gradle's isolated projects feature

---

docs/topics/native/native-binary-licenses.md
docs/topics/native/native-memory-manager.md

This PR removes mentions of the deprecated mimaloc allocator, plus fixes the GC disable option from [KT-71977](https://youtrack.jetbrains.com/issue/KT-71977)

update: deprecating memory allocator

---

docs/topics/multiplatform/multiplatform-compatibility-guide.md
docs/topics/multiplatform/multiplatform-configure-compilations.md
docs/topics/multiplatform/multiplatform-discover-project.md
docs/topics/multiplatform/multiplatform-dsl-reference.md
docs/topics/multiplatform/multiplatform-publish-lib.md

This PR updates the deprecation cycle for the old `android` target and replaces the remaining occurrences in the docs to `androidTarget`

update: deprecating android target

---

docs/topics/tour/kotlin-tour-control-flow.md

```diff
-To declare a range in reverse order, use `downTo.` For example, `4 downTo 1` is equivalent to `4, 3, 2, 1`.
+To declare a range in reverse order, use `downTo`. For example, `4 downTo 1` is equivalent to `4, 3, 2, 1`.
```

fix: wrong period position inside inline code

---

docs/topics/wasm/wasm-troubleshooting.md

This PR adds a section about incremental compilation to the Wasm's Troubleshooting page. This update is part of 2.1.0 release.

Add incremental compilation section in Wasm Troubleshooting

---

docs/kr.tree
docs/topics/compatibility-guides/compatibility-guide-21.md

Compatibility guide for Kotlin 2.1

Compatibility guide for Kotlin 2.1.0

---

docs/kr.tree
docs/topics/compose-compiler-migration-guide.md
docs/topics/compose-compiler-options.md

From this dev issue: https://youtrack.jetbrains.com/issue/KT-71227/Compose-Add-PausableComposition-feature-flag-to-the-Compose-Gradle-Plugin
This PR contains:
* a cherry-pick of https://github.com/JetBrains/kotlin-web-site/pull/4517
* an almost exact copy of approved changes from https://github.com/JetBrains/kotlin-web-site/pull/4546
After the 2.1.0 release we'll replace the warning notes for feature flags with "Experimental" labels.

feature: PausableComposition feature flag for the Compose compiler

---

docs/topics/ksp/ksp-why-ksp.md

The [explanation in the KSP Quickstart page](https://kotlinlang.org/docs/ksp-quickstart.html#make-ide-aware-of-generated-code) seems to contradict that this is not yet implemented:
> Generated source files are registered automatically since KSP 1.8.0-1.0.9.

Remove outdated KSP limitation

---

docs/kr.tree
docs/topics/multiplatform/multiplatform-build-native-binaries.md
docs/topics/native/native-improving-compilation-time.md

This PR adds a few more tips to the document, clarifies existing tips and removes an outdated part.

Update "Tips for improving Kotlin/Native compilation times"

---

docs/topics/control-flow.md

Fix typo in https://kotlinlang.org/docs/control-flow.html#guard-conditions-in-when-expressions
Remove trailing "t"

Fix typo on "control-flow" page

---

docs/topics/jvm/jvm-spring-boot-using-crudrepository.md

This sentence did not make sense:
> The return type of the `findByIdOrNull()` function...
The *return type* of the function is not an extension function. It is <del>`String`</del> `Message`. The function itself is an extension function.

Fix a bad reference in notes for jvm-spring-boot-using-crudrepository.md

---

docs/kr.tree
docs/topics/data-analysis-overview.md
docs/topics/data-analysis/data-analysis-connect-to-db.md
docs/topics/data-analysis/data-analysis-libraries.md
docs/topics/data-analysis/data-analysis-notebooks-output-formats.md
docs/topics/data-analysis/data-analysis-visualization.md
docs/topics/data-analysis/data-analysis-work-with-api.md
docs/topics/data-analysis/data-analysis-work-with-data-sources.md
docs/topics/data-analysis/get-started-with-kotlin-notebooks.md
docs/topics/data-analysis/kotlin-notebook-add-dependencies.md
docs/topics/data-analysis/kotlin-notebook-create.md
docs/topics/data-analysis/kotlin-notebook-set-up-env.md
docs/topics/data-analysis/kotlin-notebook-share.md
docs/topics/kotlin-notebook-overview.md

This PR contains updates to the Data analysis section to test improvement in user navigation according to GA analysis.
[KT-69577](https://youtrack.jetbrains.com/issue/KT-69577) Update Kotlin for data analysis docs

Update: taking Share Kotlin Notebook out of get started.

---

docs/topics/collection-ordering.md

This update affects Ordering and is supposed to explain how to add secondary criteria to custom comparator functions.
Related ticket: [KT-67760](https://youtrack.jetbrains.com/issue/KT-67760)

Adding information on how to introduce secondary criteria to custom comparator functions

---

docs/topics/jvm/java-interop.md

See [the JSpecify Javadoc](https://jspecify.dev/docs/api/org/jspecify/annotations/package-summary.html).

Use the correct package for JSpecify annotations in 1.0.

---

docs/topics/compatibility-guides/compatibility-guide-21.md

This PR adds a note about changes in language versions to the compatibility guide for Kotlin 2.1.0.

Remove language versions 1.4 and 1.5 in Kotlin 2.1.0

---

docs/topics/multiplatform/multiplatform-publish-lib.md
docs/topics/whatsnew21.md

This PR clarifies the current limitations of the klib cross-compilation:
* [KT-73574](https://youtrack.jetbrains.com/issue/KT-73574) cinterop dependencies
* #4597

update: cinterop limitation and test requirements

---

docs/topics/whatsnew-eap.md

This PR adds a warning about Gradle versions 8.7-8.11 in the what's new for 2.1.20-Beta1.

Gradle update for What's new in 2.1.20-Beta1

---

docs/topics/gradle/gradle-best-practices.md

This PR fixes the URL for the Gradle CI cookbook on the Gradle best practices page.

Fix Gradle cookbook URL

---

docs/topics/kapt.md

[KT-73468](https://youtrack.jetbrains.com/issue/KT-73468) Kotlin Website does not document how to enable `kapt.use.k2=true` in Maven

feat: add how to enable kapt with K2 compiler

---

docs/topics/data-analysis/data-analysis-libraries.md

Changing lets-plot link from github to https://lets-plot.org/kotlin/get-started.html in data analysis docs for [KT-69493](https://youtrack.jetbrains.com/issue/KT-69493)

chore: updating lets plot links

---

docs/topics/multiplatform/multiplatform-ios-dependencies.md
docs/topics/multiplatform/native-cocoapods-dsl-reference.md
docs/topics/multiplatform/native-cocoapods-libraries.md
docs/topics/multiplatform/native-cocoapods-xcode.md
docs/topics/multiplatform/native-cocoapods.md

This PR updates iOS deployment versions on CocoaPods integration pages ([KT-73860](https://youtrack.jetbrains.com/issue/KT-73860))

update: new ios deployment version

---

docs/topics/gradle/gradle-best-practices.md

This PR updates the Gradle best practices page with a new link and two edits to fix previous incorrect statements.

Update Gradle best practices

---

docs/topics/multiplatform/multiplatform-configure-compilations.md
docs/topics/multiplatform/multiplatform-dsl-reference.md

[KT-74321](https://youtrack.jetbrains.com/issue/KT-74321): This PR updates the configuration of specific compilation according to [Compilation unit level﻿ docs](https://kotlinlang.org/docs/gradle-compiler-options.html#compilation-unit-level)

fix: outdated compilation configuration

---

docs/topics/tour/kotlin-tour-hello-world.md

According to [Kotlin documentation guidelines - Links to specific places in other articles](https://docs.google.com/document/d/1mUuxK4xwzs3jtDGoJ5_zwYLaSEl13g_SuhODdFuh2Dc/edit?tab=t.0#heading=h.5jqgnjcnsu4w), update link to specific section https://kotlinlang.org/docs/strings.html#string-templates  instead of https://kotlinlang.org/docs/strings.html page itself.
In the following place, it also leads to string template section.
https://github.com/JetBrains/kotlin-web-site/blob/d03e9256d0659486a81367c6805bdbfa774c167a/docs/topics/tour/kotlin-tour-functions.md?plain=1#L72

docs(kotlin-tour-hello-world.md): Update link of string templates to jump to the exact section

---

.teamcity/builds/kotlinlang/templates/DockerImageBuilder.kt
templates/inc/edit-on-github-link.html

https://youtrack.jetbrains.com/issue/KTL-2052/Grammar-build-is-broken

ktl-2052 Return Grammar to the dependency chain

---

docs/topics/jvm/java-interop.md

[KT-73867](https://youtrack.jetbrains.com/issue/KT-73867/): this PR removes the recommendation to use `-Xtype-enhancement-improvements-strict-mode` from Java interop docs

update: outdated Java interop compiler option removed

---

docs/topics/tour/kotlin-tour-classes.md

It seems `secondUser` and `thirdUser` variables of `copy` example are unused and unnecessary.
https://kotlinlang.org/docs/kotlin-tour-classes.html#copy-instance

docs(kotlin-tour-classes.md): Remove unused variables from copy example

---

docs/topics/coding-conventions.md

This update is related to issue asking to clarify capitalization rules for declaration names with acronyms [KT-74339](https://youtrack.jetbrains.com/issue/KT-74339/)

Clarify acronym capitalization rules in declaration names

---

docs/topics/gradle/gradle-compiler-options.md

[KT-74802](https://youtrack.jetbrains.com/issue/KT-74802) Add link to Target level﻿ from JVM in Compiler options in KGP

chore: added internal links for better reference

---

docs/topics/k2-compiler-migration-guide.md

This PR removes one last warning about K2 mode being in Beta, leftover from #4593.

Remove K2 mode Beta notice

---

docs/topics/ranges.md

This PR is created to add some additional description about ranges in the documentation.
Related issue: [KT-74207](https://youtrack.jetbrains.com/issue/KT-74207/)

Clarify range and step definition

---

docs/topics/run-code-snippets.md

Short update to include a note explaining that Kotlin worksheets aren't supported in K2 mode. 
Related issue: [KT-74667](https://youtrack.jetbrains.com/issue/KT-74667)

Add note that worksheets aren't supported in K2 mode

---

docs/topics/type-safe-builders.md

This PR is created to introduce information on how to apply the `@DslMarker` annotation to function types, most commonly lambdas with receivers, to restrict implicit access to outer receivers in Kotlin DSLs and ensure scoped and safe interactions.
Related ticket: [KT-73249](https://youtrack.jetbrains.com/issue/KT-73249/)

Introduce information about DslMarker with function types

---

docs/labels.list
docs/topics/multiplatform/multiplatform-compatibility-guide.md

This PR adds details about the deprecation of the `withJava()` function in 2.1.20-RC in whatsnew-eap.md and the Kotlin Multiplatform compatibility guide.

Add withJava() description to 2.1.20-RC

---

docs/topics/gradle/gradle-configure-project.md
docs/topics/multiplatform/multiplatform-add-dependencies.md
docs/topics/scripting/custom-script-deps-tutorial.md

[KT-69458](https://youtrack.jetbrains.com/issue/KT-69458): This PR removes recommendations on using platform-specific variants of kotlinx libraries in platform source sets

update: recommendations on platform-specific kotlinx libraries removed

---

blocks/main/foundation-preview/foundation-preview.module.css

fix: foundation logo positioning

---

docs/topics/multiplatform/multiplatform-configure-compilations.md

This PR updates the current text for Gradle's Isolated Projects feature to reflect the latest changes in Kotlin 2.1.20.

Update Gradle's Isolated Projects feature text for Kotlin 2.1.20

---

docs/topics/roadmap.md

According to the Compiler folks it makes sense to mark it as done.

Moving the KT-71275 from Removed section to the Done section

---

docs/topics/getting-started.md

This PR updates the cross-platform tab to include the CMP tutorial. It also rearranges the social media icons to put YouTube first. Approved by Pamela Hill.

Add CMP tutorial to KMP tab on Get started

---

docs/topics/gradle/gradle-configure-project.md
docs/topics/ksp/ksp-multiplatform.md
docs/topics/multiplatform/multiplatform-compatibility-guide.md
docs/topics/multiplatform/multiplatform-configure-compilations.md
docs/topics/multiplatform/multiplatform-dsl-reference.md
docs/topics/whatsnew2020.md
docs/topics/whatsnew21.md

This PR updates content around the `withJava()` function that reflects the state of Kotlin 2.1.20.

Update `withJava()` function content for 2.1.20

---

docs/topics/async-programming.md

- in the Callbacks section, there's a typo here: `**titled** christmas tree`. I was going to fix to `tilted` and then decided to update that to `pyramid of doom` since that seemed more well-known. 
- in the Promises/Futures section, the existing wording is unclear re: when the promise is returned: `we're promised that at some point it will return with an object called a Promise`. So I clarified that with a few more words, aiming to keep existing simplicity without overcomplicating.

async docs: CB & promises - sp fix and clarifications 

---

docs/topics/gradle/gradle-compiler-options.md

This PR updates an example with the `compilerOptions{}` block so that it runs correctly.

Update `compilerOptions{}` block example

---

docs/v.list

Latest Dokka version is 2.0.0 :)
While Dokka has it's own `v.list` with `dokkaVersion=2.0.0` ([here](https://github.com/Kotlin/dokka/blob/1554f6efafc0ad099be7fe1d5c55dc9692408327/docs/v.list#L7)), looks like the version specified here is used on kotlinlang.org

Fix version of Dokka

---

docs/topics/js/js-interop.md

From time to time K/JS users make the wrong assumption that the `js()` function is able to accept any JS code.  
However, the truth is the K/JS compiler uses a modified version of the ES3-compliant Rhino library (1.5R3).
This PR clarifies this point, without being explicit about the version of EcmaScript that is supported.

Clarify JS code inlining capabilities

---

docs/topics/js/js-project-setup.md
docs/topics/js/running-kotlin-js.md

Hi folks, I suppose `:jsBrowserDevelopmentRun` is not the correct Gradle task name to be used with the NodeJS build target. From the context of the section, I made an assumption that calling `:run` is the right thing to do :)

Kotlin/JS: Fix typo in docs related to running Kotlin/JS project in NodeJS environment

---

docs/v.list

The minimum version is still 7.3.1 in v2.1.20:
https://github.com/JetBrains/kotlin/blob/v2.1.20/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/internal/diagnostics/AgpCompatibilityCheck.kt#L16

Correct minAndroidGradleVersion for Kotlin v2.1.20

---

docs/topics/multiplatform/native-cocoapods-dsl-reference.md
docs/topics/multiplatform/native-cocoapods-libraries.md
docs/topics/multiplatform/native-cocoapods-xcode.md
docs/topics/multiplatform/native-cocoapods.md

This PR fixes the import error ([KT-75116](https://youtrack.jetbrains.com/issue/KT-75116)), makes option lists in code samples consistent, and adds links between configuration sections ([KT-75114](https://youtrack.jetbrains.com/issue/KT-75114))

update: cocoapods import and links

---

docs/topics/getting-started.md

This PR updates the Get started page to add a link to the Kotlin newsletter. It also restructures the page so that social media and support instructions are taken out of the tabs and placed in their own section. There's also a new link added at the top of the page to help users who are looking for the latest Kotlin release details.
Approved by Daria Voronina.

Add Kotlin news to Getting started page

---

docs/topics/k2-compiler-migration-guide.md
docs/topics/releases.md

This PR updates Kotlin docs to reflect that from IntelliJ IDEA 2025.1 and onwards, the K2 compiler is used by default so opt in via K2 mode is no longer necessary.

IDEs use K2 mode by default

---

docs/topics/functions.md

Makes it clearer that named argument syntax is required and not optional when passing values for parameters following a `vararg` parameter.

Clarify named argument requirement after vararg parameter

---

docs/topics/multiplatform/multiplatform-compatibility-guide.md
docs/topics/whatsnew/whatsnew2120.md

This PR explains that developers should upgrade to 2.1.21 if they are KMP users that use the Java test fixtures Gradle plugin in their projects.

Fix for java-test-fixtures plugin in 2.1.21

---

.teamcity/builds/kotlinlang/buidTypes/BuildReferenceDocs.kt

https://youtrack.jetbrains.com/issue/KTL-2482/Mermaid-diagrams-in-Docs-are-broken

ktl-2482 chore: update webhelp version to clear css cache

---

docs/topics/ranges.md

**Root cause:**
The main title automatically receives the `id="ranges"` based on the file name `ranges.md`. This creates a conflict when the `## Ranges` sub-header which also assigns the same id for chapter.
To avoid this conflict, explicitly assign a different ID to the sub-header that does not match the main title’s auto-generated ID.

Update the id of the Ranges chapter to avoid the conflict (WRS-7029)

---

docs/kr.tree
docs/topics/eap.md
docs/v.list

This PR adds release details for Kotlin 2.2.0-RC2.

Kotlin 2.2.0-RC2 release details

---

docs/kr.tree
docs/topics/build-tools-api.md

This PR adds a page about the experimental Build tools API introduced in Kotlin 2.2.0.

Add Build tools API

---

docs/kr.tree
docs/topics/gradle/gradle-binary-compatibility-validation.md

This PR adds information about how to use binary compatibility validation in the KGP for Kotlin 2.2.0.

Add binary compatibility validation in KGP for Kotlin 2.2.0

---

docs/topics/whatsnew/whatsnew22.md

This PR adds an intro to the Breaking changes and deprecations section of the What's new in Kotlin 2.2.0.

Add intro to Breaking changes and deprecations in What's new in Kotlin 2.2.0

---

docs/topics/returns.md

* [KT-78080](https://youtrack.jetbrains.com/issue/KT-78080) Confusing example with non-local returns

update: returns feedback

---

docs/topics/classes.md

[KT-77990](https://youtrack.jetbrains.com/issue/KT-77990)
When I was going through the documentation, I had a bit of confusion around "When would we include `val` or `var`  vs when we shouldn't?" I could not really find it anywhere in the docs, hence I am proposing to include a section explaining the difference between parameters and properties in the constructor. 
While it may seem obvious, I hope this clarification can help!
I debated between making this it's own tiny section - but figured it flowed naturally from the current description of properties. 
First time contributing to these docs, so happy for any feedback/correction/discussion.

update: Add section about constructor parameters and properties in classes

---

docs/topics/coding-conventions.md
docs/topics/collection-parts.md
docs/topics/collection-transformations.md
docs/topics/compatibility-guides/compatibility-guide-22.md
docs/topics/exceptions.md
docs/topics/functions.md
docs/topics/gsoc-2023.md
docs/topics/js/js-interop.md
docs/topics/jvm/comparison-to-java.md
docs/topics/jvm/java-to-kotlin-nullability-guide.md
docs/topics/k2-compiler-migration-guide.md
docs/topics/keyword-reference.md
docs/topics/whatsnew/whatsnew14.md
docs/topics/whatsnew/whatsnew1720.md
docs/topics/whatsnew/whatsnew2120.md

Two fixes:
1. Parameters refer to the variables on the declaration site. Arguments are the expressions that "fill in" the parameters. That's why it's called "default parameters" not "default arguments". You can even see that further in the paragraph it's already referred as a "default parameter"
2. Lambda is not a parameter. It's an expression, and it's an argument that corresponds to a parameter with functional type.
---
I didn't touch anything in `docs/topics/whatsnew/*` because I don't consider them a part of the documentation but rather a piece of history that is written the way it's written.
Similarly, I didn't touch the following files:
- ./docs/topics/gsoc-2023.md
- ./docs/topics/k2-compiler-migration-guide.md
because they don't feel like a documentation to me. But let me know if …

'Default arguments' -> 'Default parameters'

---

docs/topics/tour/kotlin-tour-functions.md

The predicate doesn't loop, .filter() does
The predicate doesn't do the filtering, .filter() does

kotlin-tour-functions.md : fix filter predicate explanation

---

docs/topics/tour/kotlin-tour-hello-world.md

This PR updates the tour to explain why we recommend using `val` by default.

Update tour statement about variables

---

docs/kr.tree

This PR puts the 2.1.20 release inside earlier versions of the TOC.

Update the order of releases in the TOC

---

docs/topics/jvm/java-to-kotlin-interop.md

This update adds a note to clarify `@JvmExposeBoxed` behavior for inherited functions.
Related ticket: [KT-78928](https://youtrack.jetbrains.com/issue/KT-78928)

update: clarify @JvmExposeBoxed behavior for inherited functions

---

docs/topics/tour/kotlin-tour-intermediate-open-special-classes.md

This is a small typo fix in the documentation example.  
The explanation referred to a variable as `email`, while the actual code uses `myEmail`.

docs: fix minor typo in Email inline class explanation

---

pages/index.tsx
test/production/footer-kotlin-ecosystem-buttons.spec.ts
test/production/footer-social-media-buttons.spec.ts

Tested locally. 
And the second test: one failure, but that’s expected (we don’t have Google tags locally, so the Opt-Out button didn’t work).

fix: add a test selector to the footer

---

docs/topics/control-flow.md
docs/topics/whatsnew/whatsnew22.md

This PR updates the links for stable language features in whatsnew22.md as well as removes the experimental label for guard conditions with `when`.

Update links for stable language features in whatsnew22.md

---

docs/topics/kapt.md

This PR removes the Gradle property to control whether kapt uses the K2 compiler or not. In Kotlin 2.2.20, kapt will use the K2 compiler by default.

Remove kapt K2 Gradle property

---

docs/topics/tour/kotlin-tour-intermediate-classes-interfaces.md

This PR fixes the code samples in the delegation section of the intermediate tour and replaces them with a better example.

Update intermediate tour delegation section

---

docs/topics/compiler-reference.md

This PR adds information about the compiler options DSL added in Kotlin 2.2.20.

Add information about compiler options DSL

---

docs/topics/build-tools-api.md
docs/topics/gradle/gradle-compilation-and-caches.md
docs/topics/maven.md

This PR adds links from the build tools docs to the page on Kotlin daemon.

Add Kotlin daemon links

---

docs/topics/jvm/java-to-kotlin-nullability-guide.md

It's already mentioned in
https://kotlinlang.org/docs/java-interop.html#nullability-annotations,
just not here.

Mention JSpecify in the Java-Kotlin nullability guide.

---

docs/topics/tour/kotlin-tour-intermediate-extension-functions.md

This PR adds additional explanation in the Extensions chapter of the Kotlin tour, to explain in more detail how the `HttpClient` class works with extension functions.

Expand HttpClient explanation in Extensions chapter of the Tour

---

docs/topics/kotlin-evolution-principles.md

This PR clarifies that language features that have the "In preview" status can only have Experimental or Beta stability levels.

Add small clarification for language feature stability levels
